### ISSUE TITLE
Add an option to allow disable/enable the titles position adjustment

### ISSUE THREAD

**Issue by nlpsuge** [G-dH/vertical-workspaces#10]
https://github.com/G-dH/vertical-workspaces/blob/main/verticalWorkspaces.js#L460
`this._title.get_constraints()[1].offset = - 1.3 * WindowPreview.ICON_SIZE;`

Could you please add an option to allow disable/enable the behavior of the above line?

I have developed an extension https://github.com/nlpsuge/Always-Show-Titles-In-Overview to make titles to be always shown. 

When calculating the position of titles, somehow your extension will override my extension. And as a result when our extension are both enabled, the title is just too high to cover some contents of a window thumbnail.
![image](https://user-images.githubusercontent.com/2271720/182636690-fd22e2b4-77d3-402c-8422-e75bfe22c0c5.png)

Extensions probably are loaded by the lexicographical order.

**Comment by G-dH** [comment]
I will change the line to:

    this._title.get_constraints()[1].offset = - 1.3 * WindowPreview.ICON_SIZE * (this._icon.visible ? 1 : 0.5);

to keep the title in the window.

You should fix the issue with visible titles and close buttons in the App Grid state, VW hides it at the end of animation, but it ruins the animation. I've implemented `Always Show Window Titles` to my OFP extension, you can check how I did it:
https://github.com/G-dH/overview-feature-pack/blob/main/overviewFeaturePack.js#L378-L398

**Comment by G-dH** [comment]
If you want to override my injection, you need to make sure your extension inject the function later, you need to add a proper delay. Activation of all my extensions is delayed to avoid overrides from other extensions.

**Comment by nlpsuge** [comment]
> You should fix the issue with visible titles and close buttons in the App Grid state

I notice that problem long time ago, just don't know and also don't have time to fix it.



> I've implemented `Always Show Window Titles` in my OFP extension, you can check how I did it:
> https://github.com/G-dH/overview-feature-pack/blob/main/overviewFeaturePack.js#L378-L398

I will check your implement later, it looks more elegant. :)
