### ISSUE TITLE
[BUG] gnome-shell crashes when a network drive disconnects 

### ISSUE THREAD

**Issue by ErikSteiner** [G-dH/vertical-workspaces#100]
**Describe the bug**
If a network drive (Samba) mounted via fstab is not available, Gnome freezes under certain conditions.

**Basic debug information**
 - Did disabling all other extensions help?
   > Disabling vertical-workspaces solves the issue
 - Did you find conflicting extension?
   > No.

**To Reproduce**
1. Add a Samba share to fstab like `//AnIPAddress/somewhere  /home/user/somewhere  cifs  noauto,x-systemd.automount,x-system.idle-timeout=1min,credentials=...  0 0`
2. Shut down the Samba share, so it is not available anymore
3. Move the mouse to the bottom or use the super key to search for a program like the Gnome Software Center
4. Gnome will freeze after the first few letters, you enter
5. See error

**Expected behavior**
It is possible for me to enter search terms and find and open programs or data.

**Screenshots**

**System:**
 - OS: EndeavourOS
 - Version of V-Shell extension: 37
 - Source of installation: extension.gnome.org
 - Other installed and enabled extensions:
 ```
[erik@pc ~]$ gnome-extensions list --enabled
caffeine@patapon.info
activitiesworkspacename@ahmafi.ir
Vitals@CoreCoding.com
drive-menu@gnome-shell-extensions.gcampax.github.com
native-window-placement@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
just-perfection-desktop@just-perfection
nightthemeswitcher@romainvigier.fr
appindicatorsupport@rgcjonas.gmail.com
openweather-extension@jenslody.de
ding@rastersoft.com
expandable-notifications@kaan.g.inam.org
auto-activities@CleoMenezesJr.github.io
forge@jmmaranan.com
pamac-updates@manjaro.org
```

**System log output**
open terminal, execute:
`journalctl /usr/bin/{gjs,gnome-shell} -fo cat`
I wasn't yet able to do it, because of the freeze.

My main intention is to link this issue with the [TopHat](https://github.com/fflewddur/tophat) extension, where a user has a [similar](https://github.com/fflewddur/tophat/issues/76) experience with that extension. The developer and I were able to reproduce it. Maybe you can fix the issue together?

**Comment by ErikSteiner** [comment]
I disabled all extensions, rebooted and after reboot I entered `Exte` to get the Extension Manager. It works flawless. I enable Vertical Workspaces and from the desktop I move my mouse to the bottom. I enter `Exte`, but it hangs after `Ex` for a minute. Then it shows all applications, all files etc. I click onto the Extension Manager and disable Vertical Workspaces and redo it again. It works flawless again.

I assume, that the extension triggers the file path of the mount point and waits for response. However, as the address to the Samba share is not available, it gets a timeout (wild speculation).

**Comment by G-dH** [comment]
Interesting... The only module that has anything to do with files in V-Shell is `RecentFilesSerchProvider`, you can disable it in Settings.

**Comment by ErikSteiner** [comment]
Thank you, I disabled `RecentFilesSerchProvider`, rebooted and the lag was gone. This "fixes" the problem, but I am curious what is the reason behind it?

**Comment by ErikSteiner** [comment]
Hello there, I don't think that this is the problem. From my personal view, I don't get any thumbnails anyway.
![Bildschirmfoto 2023-08-14 19-42-47](https://github.com/G-dH/vertical-workspaces/assets/2684018/ad9dce05-c916-4b7b-be76-b95ddd7a9171)
I hope that the following logs can help. They are from the `refactor-legacy-imports` branch:
```
[esteban@ThePC ~]$ journalctl /usr/bin/gnome-shell -f
Aug 14 19:37:54 ThePC gnome-shell[11542]: Could not load a pixbuf from icon theme.
                                          This may indicate that pixbuf loaders or the mime database could not be found.
Aug 14 19:37:54 ThePC gnome-shell[11542]: Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.mozilla.firefox.SearchProvider was not provided by any .service files
Aug 14 19:37:54 ThePC gnome-shell[11542]: Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.mozilla.firefox.SearchProvider was not provided by any .service files
Aug 14 19:37:55 ThePC gnome-shell[11542]: clutter_actor_set_mapped: assertion '!CLUTTER_ACTOR_IN_MAP_UNMAP (self)' failed
Aug 14 19:37:55 ThePC gnome-shell[11542]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4600004
Aug 14 19:37:55 ThePC gnome-shell[11542]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4600004
Aug 14 19:37:58 ThePC gnome-shell[11542]: Some code accessed the property 'MonitorGroup' on the module 'workspaceAnimation'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Aug 14 19:37:58 ThePC gnome-shell[11542]: Some code accessed the property 'SecondaryMonitorDisplay' on the module 'workspacesView'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Aug 14 19:37:58 ThePC gnome-shell[11542]: Some code accessed the property 'AppGrid' on the module 'appDisplay'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Aug 14 19:37:58 ThePC gnome-shell[11542]: V-Shell (Vertical Workspaces): enabled
Aug 14 19:38:51 ThePC gnome-shell[11542]: Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.mozilla.firefox.SearchProvider was not provided by any .service files
```

**Comment by G-dH** [comment]
There is only one line in the log related to the search and it's from Firefox. Recent files search provider shows its results only if you use prefix `fq//`, the files we can see in your screenshot belongs to the Files manager. However, the RFSP initial search result set was collected even when the results were not shown, I fixed that.
The RF search provider accessed the files to get thumbnails, and if no thumbnail existed, the app/default icon was used.

Current update should fix it for normal search, only if you trigger the recent files search provider (prefix, icon, hotkey), the problematic code should be used. It needs further investigation from my end.

What version of GNOME are you using?

**Comment by ErikSteiner** [comment]
Even if it is obvious, commit 8a6a023 fixed it.
Yesterday, I guess I checked out around 7 pm, it was still a thing. I guess that was b5da9d606cca963265e02e0a4fa04a33ea2001e7.

If I can do anything, any logs and such, I am happy to help you.
```
$ gnome-shell --version
GNOME Shell 44.3
```

**Comment by G-dH** [comment]
Yeah, I meant the today's commit in the previous comment, I forgot to add reference to the bug report.
You don't have to type `fq//`, just press `Ctrl+Space` or click on the RFSP icon in the dash, it will enter the string automatically.
This search provider offers isolated list of recently used files so you can immediately see last 20 of them without searching. The built-in Files search provider can find them too, but you need to remember their names.

I'll let you know when I fix it, thanks for testing.

**Comment by G-dH** [comment]
I'm going to remove the Recent Files Search provider from V-Shell because importing Gtk into an extension is no longer allowed and I couldn't find any other way to get the file list.
