### ISSUE TITLE
[FEATURE] loop / cycle through workspaces

### ISSUE THREAD

**Issue by cmikovits** [G-dH/vertical-workspaces#101]
**Is your feature request related to a problem? Please describe.**
I have defined 4 workspaces and it would be very convenient if I can loop through all workspaces and the first / last are "connected"

**Additional context**
Afaik some time ago this was directly implemented in gnome (via tweaks)

**Comment by G-dH** [comment]
I didn't implement it in V-Shell because that option is available in my [Workspace Switcher Manager](https://github.com/G-dH/workspace-switcher-manager) extension. But I think I will add this feature directly to V-Shell eventually.
