### ISSUE TITLE
Hi from Workspace Matrix

### ISSUE THREAD

**Issue by mzur** [G-dH/vertical-workspaces#103]
Hi, I'm the maintainer of [Workspace Matrix](https://github.com/mzur/gnome-shell-wsmatrix) and just stumbeld upon your extension. It's really nice what you did here and with your [Workspace Switcher Manager](https://github.com/G-dH/workspace-switcher-manager) extension. Is see lots of overlapping features (starting from a "workspace matrix" with only one row or column). Some of the features of your extensions are on the wishlist of Workspace Matrix users (e.g. a better implementation in the overview, color adjustments) and some features that Workspace Matrix has are planned here (loop modes, thumbnails).

Now, I don't have much time to develop Workspace Matrix and mostly only try to keep it alive. I also don't know to what degree the code of our extensions is compatible. So I just wanted to say hello in case you weren't aware of the other extension 😉 You are very welcome to contribute some features to Workspace Matrix. Or you can take a look how stuff is implemented there to extend your own extensions.

**Comment by G-dH** [comment]
Hi, thanks for stopping by! I'm aware of Workspace Matrix, but unfortunately it is not compatible with V-Shell and I'm not motivated to do anything about it - I don't need it, no requests from V-Shell users, and, of course, the time...

**Comment by mzur** [comment]
Alright :+1:
