### ISSUE TITLE
[BUG] Desktop overview on main panel goes missing on reboot

### ISSUE THREAD

**Issue by jjshoots** [G-dH/vertical-workspaces#104]
**Describe the bug**
The desktop overview is missing on a fresh reboot.

**To Reproduce**
Similar to #91 , basically after a reboot, the desktop overview for the main panel (the right one in the screenshot) disappears.
It works fine after the extension is reloaded.

![image](https://github.com/G-dH/vertical-workspaces/assets/38184875/6ddc343b-5d51-482f-8266-08f64148e2a9)

**System:**
 - OS: Fresh install Ubuntu 22.04 LTS
 - Version of V-Shell extension: 37
 - Source of installation: Tried both
 - Other installed and enabled extensions:
    - Dash to Panel v56
    - Pop Shell v2
    - V-Shell v37

**System log output**
```
cogl_framebuffer_set_viewport: assertion 'width > 0 && height > 0' failed
_st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
_st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Ignoring length property that isn't a number at line 4, col 20
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x60000b
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55b4c694a350] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55b4c9736740] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55b4c973a6d0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55b4c9736350] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55b4c973b850] is on because it needs an allocation.
```

**Comment by G-dH** [comment]
Can you reproduce the bug with the Pop Shell extension disabled?

**Comment by jjshoots** [comment]
Yes it still happens with Pop Shell disabled. It stops happening when I disable DtP. For reference, these are the options I'm using for VShell, trying to create as little conflicts as possible.
![image](https://github.com/G-dH/vertical-workspaces/assets/38184875/94b4ef43-ce43-4c9c-82ac-53710e68b91f)

**Comment by G-dH** [comment]
Please try the latest development branch and let me know if it helps. Also try to enable all modules, panel and dash modules should be disabled automatically, you should see it in the log.

    git clone git@github.com:G-dH/vertical-workspaces.git
    cd vertical-workspaces/
    git checkout refactor-legacy-imports
    make install

To see the full log for the current boot, use:

    journalctl /usr/bin/gnome-shell -b

**Comment by jjshoots** [comment]
I've tried your recommendation, this time the workspace thumbnails disappeared:
![image](https://github.com/G-dH/vertical-workspaces/assets/38184875/e03ecdab-64f4-4b21-8c42-89771db22cfe)

Here is the current boot log:
```
Aug 28 12:42:55 arctic-linx gnome-shell[1468]: Running GNOME Shell (using mutter 42.9) as a X11 window and compositing manager
Aug 28 12:42:55 arctic-linx gnome-shell[1468]: ATK Bridge is disabled but a11y has already been enabled.
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Will monitor session 3
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Telepathy is not available, chat integration will be disabled.
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: loading user theme: /home/jet/.themes/tokyonight_dark/gnome-shell/gnome-shell.css
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: failed to get settings for org.gnome.shell.extensions.pop-cosmic: Error: GSettings schema org.gnome.shell.extensions.pop-co>
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Some code accessed the property 'SecondaryMonitorDisplay' on the module 'workspacesView'. That property was defined with 'l>
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Some code accessed the property 'MonitorGroup' on the module 'workspaceAnimation'. That property was defined with 'let' or >
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: [V-Shell (Vertical Workspaces)] Warning: "Layout" module disabled due to potential conflict with another extension
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: [V-Shell (Vertical Workspaces)] Warning: "Dash" module disabled due to potential conflict with another extension
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: [V-Shell (Vertical Workspaces)] Warning: "Panel" module disabled due to potential conflict with another extension
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: V-Shell (Vertical Workspaces): enabled
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-hotkey-1".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-hotkey-2".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-hotkey-3".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-hotkey-4".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-hotkey-5".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-hotkey-6".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-hotkey-7".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-hotkey-8".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-hotkey-9".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-hotkey-10".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-1".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-2".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-3".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-4".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-5".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-6".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-7".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-8".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-9".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-10".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-1".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-2".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-3".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-4".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-5".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-6".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-7".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-8".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-9".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-10".
Aug 28 12:42:56 arctic-linx gnome-shell[1468]: Window manager warning: Trying to re-add keybinding "shortcut".
```

**Comment by G-dH** [comment]
There is unfortunately nothing useful in the log and I can't reproduce the problem on my system (Ubuntu 22.04/X11 is the system on which I'm developing and using the extension).

So the problem still occurs even with pop shell disabled?
Wayland or X11?
What if you disable the secondary display?

**Comment by jjshoots** [comment]
Ah, no worries then, I can probably live with it until something else updates and inevitably corrects it.

I'm using X11, the bug goes away anytime the display restarts. Ie: when I lock the screen and unlock it, it fixes itself.
I'll let you know soon what happens when I disable the second display.

**Comment by G-dH** [comment]
Yeah, the first screen lock on 42 disables the extension even if it supports unlock-dialog session mode.

**Comment by jjshoots** [comment]
I've just tried it on a laptop owith only a single screen, and the problem persists. I'm wondering if it's anything to do with a shell theme. Do you know if this would have an effect? [This](https://github.com/jjshoots/tokyonight_dark) is what I'm using.

**Comment by G-dH** [comment]
Not on my system.

**Comment by FedeAbella** [comment]
Same thing happens to me:
![Screenshot from 2023-10-08 11-54-43](https://github.com/G-dH/vertical-workspaces/assets/65520926/bbe14fcc-4220-438e-baa8-1b28d59f6443)

Ubuntu 23.04 on XOrg
GNOME 44.3
Dash to Panel 56
V-Shell 37

I have the same setup on another user in the same pc, and I don't have that problem there. This is a new user on that pc.
DtP settings are the same, since I imported them, so there's no differences there. Also went through V-Shell settings and left them the same as the other user has. No luck.

Let me know what other info I can get for you.

Issue doesn't happen is DtP is disabled when you log in, (though there's some other weird thing with overview were some apps go off-screen, but that's for another thread). Comes back again if DtP is enabled and gnome restarted (or log out/in).

**Comment by G-dH** [comment]
@FedeAbella Thanks for reporting this. Please try the latest development version, but the compatibility is still not ideal (can't be without changes in DtP code).

**Comment by FedeAbella** [comment]
@G-dH just installed from the repo. Unfortunately, it's the same. Really weird thing is that I have the same version, settings, and DtP settings on my main user in this machine and it works fine. Got the same in my laptop with Fedora 39 and also works fine.

Best I could find out, if it helps, is it seems to go away when the extension refreshes after changing the position of the workspace thumbnails. No other setting toggles made the issue go away, even if the extension refreshed.

**Comment by G-dH** [comment]
@FedeAbella The difference may be in the order in which the extensions were enabled. That's another thing out of control.

Open looking glass (Alt+F2, lg, Enter) and execute:

    Main.extensionManager._extensionOrder

**Comment by FedeAbella** [comment]
Well, TIL what looking glass is, and painfully how to copy text from it.

Here's my personal user (where it works fine):
```
user-theme@gnome-shell-extensions.gcampax.github.com,unblank@sun.wxg@gmail.com,vertical-workspaces@G-dH.github.com,unredirect@vaina.lt,quarterwindows@troyready.com,CoverflowAltTab@palatis.blogspot.com,appindicatorsupport@rgcjonas.gmail.com,dash-to-panel@jderose9.github.com,Vitals@CoreCoding.com
```

And here's my work user (where it doesn't): 
```
user-theme@gnome-shell-extensions.gcampax.github.com,vertical-workspaces@G-dH.github.com,appindicatorsupport@rgcjonas.gmail.com,CoverflowAltTab@palatis.blogspot.com,dash-to-panel@jderose9.github.com,unredirect@vaina.lt,unblank@sun.wxg@gmail.com
```

Also, since I was following `journalctl` after I restarted GNOME (in the user where the extension doesn't work properly), I noticed this pop up. Not sure if it's relevant or not, but it mentions Workspaces, so I thought I'd share it: https://pastebin.com/aYy5pNs1

Let me know what other info I can get for you!

**Comment by G-dH** [comment]
@FedeAbella @jjshoots Sorry for not responding for so long, do you still have this problem with the latest V-Shell version?

**Comment by FedeAbella** [comment]
Hey, with the ubuntu update to GNOME 45, and V-Shell not being compatible **at that time**, I moved back to horizontal workspaces and haven't tried it again since. I'll try it again once I'm back on my work profile, since I'm now on PTO.

**Comment by one2three4f** [comment]
Strange, I didn't have this problem previously but after a fresh reinstall of pop os this issue started happening.

**Comment by G-dH** [comment]
@jjshoots Does screen the lock/unlock help? I could add an option to re-enable V-Shell after first re-opening of the overview..

**Comment by one2three4f** [comment]
@G-dH could this log be helpful? i also tried going into overview after waiting 15-20 minutes, and also locking/unlocking while in overview and out of it and the issue persists. I'm using pop os and using the pop launcher (pressing super) also gives a blank screen.

```
JS ERROR: TypeError: w._background is undefined
                                          _updateWorkspacesState/<@/home/username/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/workspacesView.js:223:17
                                          _updateWorkspacesState@/home/username/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/workspacesView.js:169:26
                                          _updateWorkspaces@resource:///org/gnome/shell/ui/workspacesView.js:467:14
                                          _init@resource:///org/gnome/shell/ui/workspacesView.js:108:14
                                          WorkspacesViewBase@resource:///org/gnome/shell/ui/workspacesView.js:27:4
                                          WorkspacesView@resource:///org/gnome/shell/ui/workspacesView.js:86:1
                                          _updateWorkspacesViews@/home/username/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/workspacesView.js:703:24
                                          prepareToEnterOverview@resource:///org/gnome/shell/ui/workspacesView.js:993:14
                                          animateToOverview@/usr/share/gnome-shell/extensions/cosmic-workspaces@system76.com/overviewControls.js:315:33
                                          animateToOverview@resource:///org/gnome/shell/ui/overview.js:82:24
                                          _animateVisible@resource:///org/gnome/shell/ui/overview.js:511:24
                                          show@resource:///org/gnome/shell/ui/overview.js:496:14
                                          gnome_40_enable/<@/usr/share/gnome-shell/extensions/pop-cosmic@system76.com/extension.js:251:23
                                          toggle@resource:///org/gnome/shell/ui/overview.js:602:18
                                          _connectOverlayKey/_overlayKeyHandlerId<@/home/username/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/overlayKey.js:105:27
JS ERROR: ReferenceError: workspaceBox is not defined
	_getAppDisplayBoxForState@/usr/share/gnome-shell/extensions/cosmic-workspaces@system76.com/overviewControls.js:104:13 
	vfunc_allocate@/usr/share/gnome-shell/extensions/cosmic-workspaces@system76.com/overviewControls.js:232:26
Can't update stage views actor <unnamed>[<StBin>:0x559e7fc4e570] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_appDisplay_AppDisplay>:0x559e7fd27f70] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x559e7fd54420] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBoxLayout>:0x559e7fd47100] is on because it needs an allocatio
```

**Comment by jjshoots** [comment]
@G-dH yes, it automatically fixes it.

**Comment by ivoruetsche** [comment]
Hi guys

I experience with the same since 2-3 weeks ago on Ubuntu 22.04, installed version is 44.10 - but I have also a red X on my extensions manager:

![image](https://github.com/G-dH/vertical-workspaces/assets/20657383/e925fc4c-4550-4e71-88f9-76fef538923a)

I can't find any logging hints at syslog about this problem...

Thanks 
Ivo

**Comment by ivoruetsche** [comment]
...I figured out:


After reboot (middle screen is main):
![2023-12-18_11-17](https://github.com/G-dH/vertical-workspaces/assets/20657383/f79d5109-7ba6-41e7-996a-e9156ff4f95a)

...then, after screenlock/unlock:
![2023-12-18_11-18](https://github.com/G-dH/vertical-workspaces/assets/20657383/18ed7271-4e93-49dd-8693-227e76ca00e6)

**Comment by G-dH** [comment]
I'm working on a patch for DtD, which will take me less time than trying to work around the mess.

**Comment by G-dH** [comment]
@ivoruetsche For now, try do disable AppDisplay module in V-Shell settings.

**Comment by G-dH** [comment]
The latest V-Shell in the repository should be even more compatible with DtD (the recursion issue) and if you want better experience you can try my DtD patch - the easiest way is to overwrite the `docking.js` file in your extension directory `~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/` with my version:
GS 45: https://github.com/G-dH/dash-to-dock/blob/v-shell-patch/docking.js
GS 40-44: https://github.com/G-dH/dash-to-dock/blob/v-shell-patch-legacy/docking.js

Please, let me know how it works for you. ;)

**Comment by jjshoots** [comment]
Not sure if anyone else is experiencing this or if it's just me with my combination of extensions, but updating V Shell breaks the DE. It just boots to a black screen where the mouse is reactive and I am aware I'm clicking things, but nothing else.

The solution is to delete `.config/dconf/user`, which removes all extensions and customizations, then reconfigure everything else again without VShell.

Again, not sure if this is just a me thing, but it happened on two devices configured in (more or less) the same way. Same plugins as the top of this thread.

**Comment by G-dH** [comment]
@jjshoots Try V-Shell without extensions and if it works, try to find the conflicting extension. Also you don't need to delete the entire dconf db, you can just disable all extensions and restart the session:
```
gsettings set org.gnome.shell enabled-extensions []
sudo systemctl restart gdm (or gdm3 in Ubuntu)
```

**Comment by ivoruetsche** [comment]
> @ivoruetsche For now, try do disable AppDisplay module in V-Shell settings.

I disabled it, but it's still the same, but I didn't tried with a reboot, I have to wait for a reboot...

**Comment by G-dH** [comment]
@ivoruetsche Patch the Dash to Dock and leave AppDisplay module enabled.

**Comment by ivoruetsche** [comment]
@G-dH 

I didn't find the file at:
~/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/

only here:
/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/docking.js

I'm not sure, this is the correct file?

> The latest V-Shell in the repository should be even more compatible with DtD (the recursion issue) and if you want better experience, you can try my DtD patch - the easiest way is to overwrite the `docking.js` file in your DtD directory `~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/` with my version: GS 45: https://github.com/G-dH/dash-to-dock/blob/v-shell-patch/docking.js GS 40-44: https://github.com/G-dH/dash-to-dock/blob/v-shell-patch-legacy/docking.js
> 
> Please, let me know how it works for you. ;)

**Comment by G-dH** [comment]
@ivoruetsche It's a patch for Dash to Dock, not for V-Shell.
- disable Ubuntu Dock (I'm not sure my patch is compatible with it)
- install Dash to Dock from e.g.o (it's compatible with Ubuntu Settings)
- download `docking.js` form my dash-to-dock repository (for Ubuntu 22.04 it's the legacy version i linked above)
- replace the file in `~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/`
- restart session

**Comment by ivoruetsche** [comment]
Hmmm, I just want to try it out, but the extensions manager told me, that there is an update for your extension ready to install after logout, so I did it and now, everything looks fine, Still working with Ubuntu Dock and enabled AppDisplay.


> @ivoruetsche It's a patch for Dash to Dock, not for V-Shell.
> 
> * disable Ubuntu Dock (I'm not sure my patch is compatible with it)
> * install Dash to Dock from [extensions.gnome.org](https://extensions.gnome.org/extension/307/dash-to-dock/) (it's compatible with Ubuntu Settings but also offers much more options, Ubuntu Dock is customized/crippled DtD)
> * download `docking.js` form my [dash-to-dock repository](https://github.com/G-dH/dash-to-dock/blob/v-shell-patch-legacy) (for Ubuntu 22.04 it's the legacy version I linked above)
> * replace the file in `~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/`
> * restart session

**Comment by G-dH** [comment]
@ivoruetsche As I mentioned before, I fixed the cause of the recursion issue in V-Shell. However, Dash to Dock/Ubuntu Dock still overrides code that V-Shell needs to control and it's most important at startup. How big is the conflict depends on which extension is enabled first.
