### ISSUE TITLE
[FEATURE] Include window count in open app indicators

### ISSUE THREAD

**Issue by fotnite-vevo** [G-dH/vertical-workspaces#105]
**Is your feature request related to a problem? Please describe.**
As someone who previously used Latte Dock on KDE Plasma, one of the things I miss is that open app indicators on the dock would show multiple indicators if there were multiple windows of an app open, one indicator per app. Seeing as this extension already customizes the default GNOME open app indicators, it seems like something that makes sense for it to do as well

**Additional context**
Dash to Dock already has their own version of this. For example, here is what it looks like when two windows of Text Editor are open: 
![image](https://github.com/G-dH/vertical-workspaces/assets/68102115/c17c3492-4748-49be-ae39-eb4c80f6cdd2)
The indicator caps at four dots, so 4+ windows always only display 4 dots

Perhaps a version of this could be done, with one of the indicator dots being a pill, similar to how the new Activities button looks in GNOME 45? Then with one window it would look similar to the current implementation.

**Comment by G-dH** [comment]
If you're not sure how many windows you have open, you have several options now:
 - Secondary click on the app icon opens context menu with a list of open windows. This menu also contains item to close all app windows on the current workspace which contains the exact number.
 - Scrolling over the app icon cycles through all app windows (scroll up for MRU order, current workspace first)
 - Click the app icon at the bottom of the app window preview or use secondary mouse click on the window preview (both optional) to activate window search by the app name
 - Press _Space_ key in the overview or click the Search Windows icon in the dash to activate window search that lists all open windows (sorting is optional)

Do you have a good example where the dots are really useful?

**Comment by G-dH** [comment]
I added the number of open windows to the app icon label, along with the title of the current window.

**Comment by fotnite-vevo** [comment]
This seems to be a pretty good solution. Thanks!
