### ISSUE TITLE
[BUG] Cannot access second screen with the mouse pointer

### ISSUE THREAD

**Issue by SustReal** [G-dH/vertical-workspaces#106]
**Describe the bug**
When running vertical-workspaces on a set-up with two screens (extended) and the following settings (see below) I cannot access the second screen anymore. The launcher on the left-hand side of the primary screen seems to "block the way" of the mouse pinter. 

Set-up: (see screenshot below)
Primary screen on the right 
Secondary screen on the left

Settings:
Workspaces on the right-hand side of the primary screen
Dash/Flie laucher on the left-hand side 

Result:
Mouse pointer won't move from the right (primary) screen to the second one. (Additional note: if, however, you make the left screen the primary screen, you don't have the issue and can move the mouse between the screens as expected)

**Basic debug information**
 - Did disabling all other extensions help?

Did not check, but I did not have much other extensions installed (only screenshot-tool)

 - Did you find conflicting extension?

No

**To Reproduce**
1. Use set-up with two screens
2. Screen settings
3. Choose extended screens 
4. Set right screen to "primary"
5. Go to v-shell settings
6. In layout, choose horizontal & workspace right 
7. Try to move the cursor from the right screen to the left screen

**Expected behavior**
Being on the primary screen with your mouse pointer, you would expect the mouse to be able to move the cursor from the right screen to the left screen – bypassing the launcher on the left side of the primary screen.

**Screenshots**
![image](https://github.com/G-dH/vertical-workspaces/assets/51329893/d80eee87-42c4-484e-800a-48116ca5475e)

**System:**
 - OS: Manjaro 23.0 (but also experienced it before in 22.x)
 - Version of V-Shell extension: 37
 - Source of installation: extension.gnome.org
 - Other installed and enabled extensions: screenshot-tool

**System log output**
open terminal, execute:
`journalctl /usr/bin/{gjs,gnome-shell} -fo cat`
reproduce the bug, copy the output from terminal if any.

- none / didn't check

Thanks a lot for the work you are putting into this. That is a very useful tool that is/would be vital for my workflow. Would be great to have it working again as expected. Hope the description wasn't too confusing (and I kind of hope, it actually is a bug and not a setting I overlooked)

**Comment by G-dH** [comment]
Disable hot edge:
Settings > Behavior > Hot Corner Position

**Comment by SustReal** [comment]
Yeah, that's it of course. Thanks a lot. (I was expecting to overlook a setting with all those options available. ;) )

**Comment by G-dH** [comment]
Thanks for feedback and coffee!

**Comment by G-dH** [comment]
On extensions.gnome.org you mentioned "too many issues". These comments are not very helpful...

**Comment by SustReal** [comment]
You are right. That was neither right nor phrased correctly. Sorry 'bout that. Let me try to correct that or at least leave a new more accurate rating.

**Comment by G-dH** [comment]
Thanks, feel free to report anything, but always here and with all details so I can try to fix it. Btw e.g.o does not send notifications about comments, authors must visit the page to see them.

**Comment by SustReal** [comment]
> Thanks, feel free to report anything, but always here and with all details so I can try to fix it. 

Thanks. I will.

> Btw e.g.o does not send notifications about comments, authors must visit the page to see them.

Good to know! Thanks!
