### ISSUE TITLE
Slowing gnome-shell

### ISSUE THREAD

**Issue by sk9la** [G-dH/vertical-workspaces#107]
**Describe the bug**
- The extension is heavily slowing the every part of the gnome shell, especially when I restart it `Alt+F2 -> r`
- The overview doesn't display open windows on main screen
- The AppGrid Columns/Rows are changed upon boot, I set to 10Cx5R, after reboot I get 10Cx2R

**Basic debug information**
 - **Did disabling all other extensions help?** I did, I just left on the "JustPerfection" extension, because it allows me to hide non useful status bar icons
 - **Did you find conflicting extension?** Not really

**System:**
 - **OS**: Kali Linux 2023.3
 - **Gnome Shell**: 44.1
 - **Version of V-Shell extension**: 37
 - **Source of installation**: extension.gnome.org
 - **Other installed and enabled extensions**: JustPerfection, NightThemeSwitcher, DashToPanel

**Comment by G-dH** [comment]
In any case, try V-Shell with all extensions disabled (including JP), try to configure all you need in V-Shell's Settings, then, if everything works as expected, reset all JP options to default values, and only use options that you really need and are not available in V-Shell. One by one to find the ones causing problems.

**Comment by G-dH** [comment]
Enable all V-Shell modules.

**Comment by G-dH** [comment]
You can also try the current development version of V-Shell:

[Installation from the repository](https://github.com/G-dH/vertical-workspaces/tree/esm-modules#installation-from-github-repository)

**Comment by G-dH** [comment]
Please try to install the latest development version, that's what I'm using myself and working on.
Are you using alphabetical sorting? Is `Allow Incomplete Pages` option on the `Behavior` tab of Settings window disabled?

**Comment by G-dH** [comment]
Try [Extensions Sync](https://extensions.gnome.org/extension/1486/extensions-sync/) to export/import extension settings.

To the App Grid - try `Custom` order setting, disable `Allow Incomplete Pages`, use `Remove App Grid Layout` button, drag and drop any app icon back and forth, the app grid should rearrange icons to fill the pages and remember position of all icons.

**Comment by G-dH** [comment]
🤔
