### ISSUE TITLE
[BUG] Apps folders open on secondary monitor

### ISSUE THREAD

**Issue by pcercuei** [G-dH/vertical-workspaces#109]
**Describe the bug**

When opening an application folder in the applications overview, the folder opens on my secondary monitor (my laptop's internal screen) instead of my primary monitor (external display) where the rest of the Gnome Shell UI is.

**Basic debug information**
 - Did disabling all other extensions help? No
 - Did you find conflicting extension? No

**To Reproduce**
1. Connect an external monitor, and use it as the primary display
2. Create an application folder by drag-n-dropping an application onto another one in the applications overview
3. Open the newly created folder by clicking on it

**Expected behavior**
The apps folders should open on the primary monitor.

**Video**
[app_folder_bug.webm](https://github.com/G-dH/vertical-workspaces/assets/403272/6ae1a49b-a05c-44fa-ae72-589b22d63f11)

**System:**
 - OS: Debian testing
 - Version of V-Shell extension: 37
 - Source of installation: extension.gnome.org
 - Other installed and enabled extensions: GSConnect, Hibernate Status Button, Freon, Replace Activities Text, Colored Application Menu Icon

**Comment by G-dH** [comment]
You can [install the latest development version](https://github.com/G-dH/vertical-workspaces#installation-from-github-repository) from the `main` branch, this issue should be already fixed.

**Comment by pcercuei** [comment]
I switched to the latest version from git, that works much better, thanks.
