### ISSUE TITLE
Connecting/Disconnecting second monitor used as Primary breaks layout

### ISSUE THREAD

**Issue by electrofelix** [G-dH/vertical-workspaces#11]
I use a second monitor with my laptop, which I've configured to act as the primary so that Activities and top bar is displayed on that screen:
![image](https://user-images.githubusercontent.com/912324/186894100-4efad562-2ecf-4433-a516-1c51c1f789f5.png)

Each time I disconnect and reconnect my laptop, the vertical workspaces switcher displayed when triggering the hot corner gets messed up, in that the workspace switcher ends up moving to where the horizontal switcher would have been displayed.
![image](https://user-images.githubusercontent.com/912324/186894780-679f2b34-c686-46d7-811e-9cc2e02a1aee.png)

Disabling and re-enabling the extension resolves things so that it displays correctly again:
![image](https://user-images.githubusercontent.com/912324/186894877-21aa51e7-741e-4497-92e7-7fe9bb72e1ea.png)

In fact, in many cases enabling and disabling almost any extension will result in the problem being reoslved.

I can also trigger this by simply switching which display is configured to be the primary.

It seems like gnome is redoing the layout when the monitors are changed, but without applying any changes made by this extension. 
Wonder if this extension needs to add an additional hook to trigger on a monitor layout change event?

**Comment by G-dH** [comment]
The culprit in this case is Ubuntu dock, and solution is already buit-in VW - option Misc > Compatibility > Fix for Dash to Dock. The current version in this github repository automatically enables this option when detects DtD running. It also handles changes in monitors configuration.

**Comment by electrofelix** [comment]
Thanks, I thought I had that option enabled at some point and obviously didn't understand what it was doing. Once I turned it on, it worked straight away.
