### ISSUE TITLE
[BUG] Black Screen after login using Xorg & Nvidia

### ISSUE THREAD

**Issue by stoneC0der** [G-dH/vertical-workspaces#112]
**Describe the bug**
After upgrading to Ubuntu 23.04, I installed this extension has my previous workspace management extension stop working on gnome 44. I also installed a bunch of new extensions to replace the broken one.
But each time I switch off my computer, and restart, choose Gnome classic (xorg), Wayland (both classic & normal) I can login, but when using Gnome on xorg, after login I can see anything, black screen with moving cursor, even f.lux changes my screen at time.

**Basic debug information**
 - Did disabling all other extensions help?
 So I used tty to login & disable extension one by one and tried again, but I was only able to successfully login, and see my desktop when V-shell was disable, and each time I enabled it after login and forget, I get the same issue upon reboot.

 - Did you find conflicting extension?
 Not that I aware of, everything works fine when enabled. 

**To Reproduce**
1. Install V-shell & enable
2. Restart & choose Gnome session (xorg)
3. Login
4. See error (black screen with cursor)

**Expected behavior**
I should be able to see my desktop after login with the extension enable

**Screenshots**

**System:**
 - OS: Ubuntu 24.03 (Vanillla Gnome installed after remove ubuntu-desktop)
 - Version of V-Shell extension: 37
 - Source of installation: extension.gnome.org (extension-manager)
 - Other installed and enabled extensions: *Advanced Volume Control, AppIndicator and KStatus..., Blur mu Shell, Caffeine, Color App Munu Icon..., Compiz alike magic lamp effect, Compiz windows effect, Coverflow Atl-Tab, Custom Hot Corners - Extended, Fullscreen to Empty Workspace, Gesture Improvements, Just Another search bar, Just perfection, Logo Menu, Night Theme Switcher, Rounded Windows Corners, TopHat*

**System log out put**
open terminal, execute:
`journalctl /usr/bin/{gjs,gnome-shell} -fo cat`
reproduce the bug, copy the output from terminal if any.

Don't know if I can successfully reproduce the bug, and have the log, but here is the output after a fail attempt, then disable the extension and reboot

```➜ journalctl /usr/bin/{gjs,gnome-shell} -fo cat
../clutter/clutter/clutter-actor.c:8929: Actor '<unnamed>[<MetaBackgroundGroup>:0x5575ef790230]' tried to allocate a size of -2147483648.00 x 0.00
JS LOG: Characters Application started
clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4800004
JS LOG: Characters Application exiting
JS ERROR: TypeError: event is null
_onLongPress@resource:///org/gnome/shell/ui/windowPreview.js:616:13

Can't update stage views actor <Shadow Actor>[<StBin>:0x5575f32c4230] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5575f1c5dc10] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5575f0e70b80] is on because it needs an allocation.```

**Comment by G-dH** [comment]
- _GNOME Classic_ session includes extensions to imitate GNOME 2 layout, use _GNOME (Xorg)_ or _Ubuntu on Xorg_ session.
- Disable all extensions but V-Shell and try again
- Blur My Shell can be compatible with V-Shell only if you disable blur in the Overview tab of its Settings (both Background and App folder)
- Install the latest development V-Shell from this repository - instructions are in the README on the main page - bug fixes and more features

**Comment by stoneC0der** [comment]
I can confirm that the issue is not Blur My Shell (blur in the Overview was already disable)
The conflicting extension is Just Perfection
However with V-Shell enable I have a black screen for about 10-20 second before I can see my Desktop

I will install the dev version and revert

**Comment by G-dH** [comment]
Yeah, I forgot to mention JP extension, it has some conflicting options that need to be set to default.
Does the delay issue occur if only V-Shell is enabled?

**Comment by stoneC0der** [comment]
With the dev release the screen is now flickering.
I will test the delay with all extension disable & V-shell only.

**Comment by G-dH** [comment]
> What the settings in Just Perfection ext that need to be set to default? I highly depend on that

- reset all JP options (delete its schema settings using _dconf Editor_), enable JP
- restart Shell
- test whether all works well now
- try to find options you're interested in in the V-Shell Settings
- try to enable JP options that are not available (you can ask me) in the V-Shell one by one and see if there's any conflict (you can watch `journalctl /usr/bin/gnome-shell -f` output) during testing
- if you find any conflict, report it here

**Comment by G-dH** [comment]
Closing, feel free to reopen if needed.
