### ISSUE TITLE
[FEATURE] Control Search Background Brightness

### ISSUE THREAD

**Issue by vonHartz** [G-dH/vertical-workspaces#114]
Thanks for this great extension!

**Is your feature request related to a problem? Please describe.**
It appears that one cannot control the background brightness during search in the extension.
Thus, when one has selected a background brightness > 30, the background goes darker once one starts typing into the search field in the overview.

**Describe the solution you'd like**
To be able to match the brightness during search with that of the overview.

**Describe alternatives you've considered**
Setting a lower overview brightness. But that defeats the purpose of having it controllable in the first place.

**Additional context**
![Screenshot from 2023-10-19 14-21-48](https://github.com/G-dH/vertical-workspaces/assets/17391760/f017f1d7-797b-4b68-91a3-629a49f01c88)
![Screenshot from 2023-10-19 14-22-15](https://github.com/G-dH/vertical-workspaces/assets/17391760/bf862a4c-6880-4c47-902f-da609d462771)

**Comment by G-dH** [comment]
Yes, I set the maximum brightness for the search view so the text is always visible on any wallpaper.

**Comment by G-dH** [comment]
@vonHartz Added slider for independent brightness control in search view.

**Comment by vonHartz** [comment]
Awesome. Thank you!
