### ISSUE TITLE
[BUG] Nvidia/X11 dual monitor; pointer will not cross monitors when the secondary monitor is positioned on the left

### ISSUE THREAD

**Issue by jsg001** [G-dH/vertical-workspaces#115]
**Describe the bug**
() Screen layout: 3840x2160 primary screen with a 1920x1080 secondary screen left of the primary.  The workspace does not span the displays (i.e., the secondary monitor is not included in the workspace)
() Once the mouse is visible on the primary screen, it can not be moved left to the secondary screen.  The mouse stays visible on the primary screen and is unable to transition to the the secondary monitor.  To access the secondary monitor, I have to disable the vertical-workspaces extension or reconfigure the secondary display above, below, or to the right of the primary monitor.
() The problem only exist when the secondary screen is on the left.  The top, bottom, and right positions work as expected.
() I experience this bug on an nvidia/X11 configuration but not on intel/wayland
() I believe this bug was introduced about 5 months ago, but I could not identify the cause.  It's not clear to me where the bug is other than it only presents itself only with this extension enabled.

**Basic debug information**
 - Did disabling all other extensions help: No
 - Did you find conflicting extension: No

**To Reproduce**
1. mouse works as expected
2. install and enable vertical-workspaces extension
4. left screen no longer accessible by the mouse
5. disable vertical-workspaces extension
7. mouse works as expected
8. the extension can be enabled and disabled at-will with the same buggy results

**Expected behavior**
Mouse moves freely between displays

**Screenshots**
none

**System:**
 - OS: Fedora 38 and 39
 - Nvidia driver: 470.199.02
 - X11 version: xorg 1.20.14 (12014000)
 - Version of V-Shell extension: 37.5 (git head on 11/1/23) for fedora 39, gnome-extensions for fedora 38

**System log output**
V-Shell (Vertical Workspaces): enabled
Can't update stage views actor <unnamed>[<StBin>:0x5617e25ab400] is on because it needs an allocation.
g_key_file_get_string: assertion 'key_file != NULL' failed
g_key_file_get_string: assertion 'key_file != NULL' failed
V-Shell (Vertical Workspaces): disabled

**Comment by G-dH** [comment]
If you have vertical Dash on the left and _Hot Corner Position_ option set to _Follow Dash - Hot Edge_, then the hot edge trigger blocks the mouse pointer. In this case change the option to _Follow Dash_ or any other position.

**Comment by jsg001** [comment]
Not a bug but rather a bad configuration on my part.

Thank You!  This is by far my favorite Gnome extension!

**Comment by G-dH** [comment]
Thanks for the feedback!
