### ISSUE TITLE
[BUG] Mouse cursor is blocked by dash panel

### ISSUE THREAD

**Issue by PilnyTomas** [G-dH/vertical-workspaces#116]
**Describe the bug**
The dash panel on the side where another display is located blocks the mouse cursor from reaching the other display.

**Basic debug information**
Moving the dash back to the bottom allowed moving the cursor to other displays as expected.
I disabled all other Gnome extensions - the bug still persists.

**To Reproduce**
1. Have multiple displays
2. Layout -> Dash position -> Left (if the other display is on the left)
3. Try to move the mouse cursor out of the main display to another display.

**Expected behavior**
The mouse cursor can reach other displays even when the dash menu is on the side.

**Screenshots**
A screenshot will not demonstrate the issue. Video could...

**System:**
 - OS: Fedora 38 (Workstation Edition)
 - Version of V-Shell extension: 37
 - Source of installation: extension.gnome.org
 - Other installed and enabled extensions: none (I disabled them to test it)

**System log output**
```
V-Shell (Vertical Workspaces): enabled
Source ID 78901 was not found when attempting to remove it
Can't update stage views actor <unnamed>[<StBin>:0x55fee05a3e40] is on because it needs an allocation.
g_key_file_get_string: assertion 'key_file != NULL' failed
g_key_file_get_string: assertion 'key_file != NULL' failed
g_key_file_get_string: assertion 'key_file != NULL' failed
g_key_file_get_string: assertion 'key_file != NULL' failed
Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _promisify/proto[asyncFunc]@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:448:16
  openExtensionPrefs@resource:///org/gnome/shell/ui/extensionSystem.js:254:26
  OpenExtensionPrefs@resource:///org/gnome/shell/ui/shellDBus.js:459:31
  LaunchExtensionPrefs@resource:///org/gnome/shell/ui/shellDBus.js:455:14
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
```

**Comment by G-dH** [comment]
Disable hot edge:
Settings > Behavior > Hot Corner Position

https://github.com/G-dH/vertical-workspaces/issues/115#issuecomment-1789521909

**Comment by G-dH** [comment]
@PilnyTomas: ?
