### ISSUE TITLE
[BUG] [Gnome 45] Transition to workspace overview animation

### ISSUE THREAD

**Issue by marek-ciazynski** [G-dH/vertical-workspaces#117]
**Describe the bug**
Transition to workspace overview animation is broken (see screencast) after the switching to the lower workspace when not on the overview (e.g. using keyboard shortcut Ctrl+Alt+Down or scrolling on the new Activities Indicator). All windows disappear instantly, then after the duration of the transition animation it instantly appears in the correct place on the overview.
This problem doesn't occur when switching to the upper workspace (e.g. Ctrl+Alt+Up). Also, after switching to the lower workspace, the problem doesn't occur if we open a window (e.g using Calculator functional key on keyboard) before opening the overview.

**Basic debug information**
 - Using vertical workspaces
 - Disabling all other extensions doesn't fix the problem
 - Using X11 instead of Wayland doesn't fix this problem

**To Reproduce**
1. Open a window
2. Press Ctrl+Alt+Down 
3. Open overview for example by pressing Meta
4. See that there is no animation for windows

**Expected behavior**
I should see the animation when opening workspace overview.

**Screenshots**
[screencast.webm](https://github.com/G-dH/vertical-workspaces/assets/20818349/02f7b1bb-251b-475f-aac3-fd2839e19e75)

**System:**
 - OS: Arch Linux (fully upgraded as for 25 Nov)
 - Wayland 1.22.0, GNOME Shell 45.1
 - Version of V-Shell extension: `06804d1` commit from `esm-modules` branch
 - Source of installation: GitHub, manually run `make install`
 - Other installed and enabled extensions: Dash to Dock, AppIndicator Support (also tested w/o other extensions)

**System log output**
There is only one error when appearing multiple times when running `journalctl /usr/bin/{gjs,gnome-shell} -fo cat`:
```
value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
```

**Comment by G-dH** [comment]
Can you upload your current V-Shell configuration (output of the following command)?

    dconf dump /org/gnome/shell/extensions/vertical-workspaces/

You can also try to reproduce the issue with other profiles (Settings > Profiles) and let me know if it makes any difference.

**Comment by marek-ciazynski** [comment]
<details>
<summary>dconf dump /org/gnome/shell/extensions/vertical-workspaces/</summary>
<pre>
[/]
aaa-loading-profile=true
always-activate-selected-window=false
animation-speed-factor=100
app-display-module=true
app-favorites-module=true
app-folder-order=0
app-grid-active-preview=false
app-grid-animation=4
app-grid-bg-blur-sigma=40
app-grid-columns=0
app-grid-content=2
app-grid-folder-center=true
app-grid-folder-columns=0
app-grid-folder-icon-grid=2
app-grid-folder-icon-size=-1
app-grid-folder-rows=0
app-grid-icon-size=-1
app-grid-incomplete-pages=false
app-grid-names=1
app-grid-order=0
app-grid-page-width-scale=90
app-grid-performance=true
app-grid-rows=0
app-grid-spacing=12
center-app-grid=true
center-dash-to-ws=false
center-search=true
close-ws-button-mode=2
dash-bg-color=1
dash-bg-gs3-style=false
dash-bg-opacity=20
dash-bg-radius=0
dash-icon-scroll=1
dash-max-icon-size=64
dash-module=true
dash-position=3
dash-position-adjust=0
dash-show-recent-files-icon=2
dash-show-windows-before-activation=1
dash-show-windows-icon=2
enable-page-shortcuts=true
favorites-notify=1
hot-corner-action=1
hot-corner-fullscreen=true
hot-corner-position=6
hot-corner-ripples=false
layout-module=true
message-tray-module=true
new-window-focus-fix=false
notification-position=1
osd-position=6
osd-window-module=true
overlay-key-module=true
overlay-key-primary=1
overlay-key-secondary=1
overview-bg-blur-sigma=50
overview-bg-brightness=50
overview-esc-behavior=0
overview-mode=0
panel-module=true
panel-position=0
panel-visibility=0
profile-data-4={'workspaceThumbnailsPosition': '1', 'wsMaxSpacing': '350', 'wsPreviewScale': '98', 'secWsPreviewScale': '100', 'secWsPreviewShift': 'false', 'wsThumbnailsFull': 'false', 'secWsThumbnailsPosition': '2', 'dashPosition': '3', 'dashPositionAdjust': '0', 'wsTmbPositionAdjust': '0', 'showWsTmbLabels': '0', 'showWsTmbLabelsOnHover': 'false', 'closeWsButtonMode': '2', 'secWsTmbPositionAdjust': '0', 'dashMaxIconSize': '64', 'dashShowWindowsIcon': '2', 'dashShowRecentFilesIcon': '2', 'centerDashToWs': 'false', 'showAppsIconPosition': '1', 'wsThumbnailScale': '13', 'wsThumbnailScaleAppGrid': '13', 'secWsThumbnailScale': '5', 'showSearchEntry': 'true', 'centerSearch': 'true', 'centerAppGrid': 'true', 'dashBgOpacity': '20', 'dashBgColor': '1', 'dashBgRadius': '0', 'dashBgGS3Style': 'false', 'runningDotStyle': '1', 'enablePageShortcuts': 'true', 'showWsSwitcherBg': 'false', 'showWsPreviewBg': 'true', 'wsPreviewBgRadius': '30', 'showBgInOverview': 'true', 'overviewBgBrightness': '50', 'overviewBgBlurSigma': '50', 'appGridBgBlurSigma': '40', 'smoothBlurTransitions': 'false', 'appGridAnimation': '4', 'searchViewAnimation': '4', 'workspaceAnimation': '1', 'animationSpeedFactor': '100', 'winPreviewIconSize': '1', 'winTitlePosition': '0', 'startupState': '0', 'overviewMode': '0', 'workspaceSwitcherAnimation': '0', 'searchIconSize': '96', 'searchViewScale': '104', 'appGridIconSize': '-1', 'appGridColumns': '0', 'appGridRows': '0', 'appGridFolderIconSize': '-1', 'appGridFolderColumns': '0', 'appGridFolderRows': '0', 'appGridFolderIconGrid': '2', 'appGridContent': '2', 'appGridIncompletePages': 'false', 'appGridOrder': '0', 'appFolderOrder': '0', 'appGridNamesMode': '1', 'appGridActivePreview': 'false', 'appGridFolderCenter': 'true', 'appGridPageWidthScale': '90', 'appGridSpacing': '12', 'searchWindowsOrder': '1', 'searchFuzzy': 'false', 'searchMaxResultsRows': '5', 'dashShowWindowsBeforeActivation': '1', 'dashIconScroll': '1', 'searchWindowsIconScroll': '1', 'panelVisibility': '0', 'panelPosition': '0', 'windowAttentionMode': '0', 'wsSwPopupHPosition': '50', 'wsSwPopupVPosition': '95', 'wsSwPopupMode': '1', 'wsSwitcherWraparound': 'false', 'wsSwitcherIgnoreLast': 'false', 'favoritesNotify': '1', 'notificationPosition': '1', 'osdPosition': '6', 'hotCornerAction': '1', 'hotCornerPosition': '6', 'hotCornerFullscreen': 'true', 'hotCornerRipples': 'false', 'alwaysActivateSelectedWindow': 'false', 'winPreviewSecBtnAction': '2', 'winPreviewMidBtnAction': '1', 'winPreviewShowCloseButton': 'true', 'windowIconClickAction': '1', 'overlayKeyPrimary': '1', 'overlayKeySecondary': '1', 'overviewEscBehavior': '0', 'newWindowFocusFix': 'false', 'appGridPerformance': 'true', 'windowThumbnailScale': '20', 'workspaceSwitcherPopupModule': 'true', 'workspaceAnimationModule': 'true', 'workspaceModule': 'true', 'windowManagerModule': 'true', 'windowPreviewModule': 'true', 'windowAttentionHandlerModule': 'true', 'windowThumbnailModule': 'true', 'swipeTrackerModule': 'true', 'searchControllerModule': 'true', 'searchModule': 'true', 'panelModule': 'true', 'overlayKeyModule': 'true', 'osdWindowModule': 'true', 'messageTrayModule': 'true', 'layoutModule': 'false', 'dashModule': 'false', 'appFavoritesModule': 'true', 'appDisplayModule': 'true', 'windowSearchProviderModule': 'true', 'recentFilesSearchProviderModule': 'true'}
profile-name-4='Custom'
recent-files-search-provider-module=true
running-dot-style=1
search-controller-module=true
search-fuzzy=false
search-icon-size=96
search-max-results-rows=5
search-module=true
search-view-animation=4
search-width-scale=104
search-windows-icon-scroll=1
search-windows-order=1
sec-wst-position-adjust=0
secondary-ws-preview-scale=100
secondary-ws-preview-shift=false
secondary-ws-thumbnail-scale=5
secondary-ws-thumbnails-position=2
show-app-icon-position=1
show-bg-in-overview=true
show-search-entry=true
show-ws-preview-bg=true
show-ws-switcher-bg=false
show-wst-labels=0
show-wst-labels-on-hover=false
smooth-blur-transitions=false
startup-state=0
swipe-tracker-module=true
win-attention-handler-module=true
win-preview-icon-size=1
win-preview-mid-mouse-btn-action=1
win-preview-sec-mouse-btn-action=2
win-preview-show-close-button=true
win-title-position=0
window-attention-mode=0
window-icon-click-action=1
window-manager-module=true
window-preview-module=true
window-search-provider-module=true
window-thumbnail-module=true
window-thumbnail-scale=20
workspace-animation=1
workspace-animation-module=true
workspace-module=true
workspace-switcher-animation=0
workspace-switcher-popup-module=true
ws-max-spacing=350
ws-preview-bg-radius=30
ws-preview-scale=98
ws-sw-popup-h-position=50
ws-sw-popup-mode=1
ws-sw-popup-v-position=95
ws-switcher-ignore-last=false
ws-switcher-wraparound=false
ws-thumbnail-scale=13
ws-thumbnail-scale-appgrid=13
ws-thumbnails-full=false
ws-thumbnails-position=1
wst-position-adjust=0
</pre>
</details>

Tried changing to other profiles and the default Profile 1, 2 and 3 works fine. Haven't checked the fourth default profile beacuse I've overridden it.

**Comment by G-dH** [comment]
Thanks for your cooperation, please try the latest update.

**Comment by marek-ciazynski** [comment]
Yes, it does work correctly now :tada: Thanks, that was fast :)
