### ISSUE TITLE
[FEATURE] workspace isolated dash

### ISSUE THREAD

**Issue by robin-a-meade** [G-dH/vertical-workspaces#118]
**Is your feature request related to a problem? Please describe.**

I like my workspaces to be isolated from each other. That's why I use the following dconf setting that restricts the choice of applications when Alt-TABing to apps running on the current workspace only:

```
gsettings set org.gnome.shell.window-switcher current-workspace-only true
```
However, the state of the dash is inconsistent with this approach. The dash shows applications that are running on *other* workspaces.

Minimal example of the problem:
![image](https://github.com/G-dH/vertical-workspaces/assets/1343270/cad82150-048e-490a-9fd9-46b416519bc8)

In the above screenshot, you can see that the dash displays the Calculator app icon and indicates that it is running, even though it is not running on the _current_ workspace. (The Calculator app is not pinned to the dash in this example, btw.)

**Describe the solution you'd like**
In the situation of the above screenshot, I'd like the dash to not show the Calculator application. (Or, if the Calculator app was pinned, the dash should not indicate that it is actively running.) This would make the active applications listed in the dash consistent with the application choices given by hitting Alt-TAB.

**Describe alternatives you've considered**

**1)** I've been using the [**Workspace Isolated Dash**](https://extensions.gnome.org/extension/887/workspace-isolated-dash/) extension (a [fork](https://github.com/wakira/gnome-shell-extension-workspace-isolated-dash/) actually), but it no longer works.

**2)** I considered installing the Dash to Dock extension and using its `isolate-workspaces` setting:

```
gsettings set org.gnome.shell.extensions.dash-to-dock isolate-workspaces true
```
![image](https://github.com/G-dH/vertical-workspaces/assets/1343270/9c302faf-d773-4729-b2ed-2615e3bc193f)

but I'd prefer not installing another extension.

**Additional context**
The existing *Prefer Current Workspace* option for *App Icon - Click Behavior* goes well with this feature request. They both help isolate workspaces.

**Comment by G-dH** [comment]
Try the latest update and let me know how it works. _Behavior > Dash > Isolate Workspaces_

**Comment by robin-a-meade** [comment]
Yes, it works perfectly! Thank you! You can close this feature request.

**Comment by G-dH** [comment]
I'll leave it open for now, if you find any bug, let me know. What GNOME version do you use?

**Comment by robin-a-meade** [comment]
I'm running GNOME 45.1 (Fedora Linux 39 Workstation Edition).
