### ISSUE TITLE
[BUG] Issues on fresh F39 Lenovo T14

### ISSUE THREAD

**Issue by jakub-krysl-ipf** [G-dH/vertical-workspaces#119]
**Describe the bug**
Hello, I installed fresh Fedora 39 on new Lenovo T14 and noticed some seemingly random failures. I use dual monitor setup - external monitor set as primary.

1. From time to time windows reset to where they were after login. The interval is not static, could be every minute or in several hours.
2. 2nd vertical screen is sometimes unusable (shown, but windows cannot be put there). Screens are labeled 1 - 0 - 2 - 3 ..., where the screen with index 0 is shown but unusable.
3. Plus there were some graphics issues exclusive to the notebook screen which seem to be linked to Electron app (only seen them in Slack and teams-for-linux). Random flickering and some parts of lines were not rendering properly for a second (always the same) and even once the whole screen died and needed restart. HW test is fine. I did not see them after I installed this extension from git source (commit 43dcb8c22383afae0f705b2b817a62df938ece20).
4.  Moving app from laptop to between screen 1 and 2 to spawn a new screen with the app fails and places app window on existing screen 2 instead.

**Basic debug information**
 - Did disabling all other extensions help? No 
 - Did you find conflicting extension? No

**To Reproduce**
1. Based on logs wait for `[V-Shell (Vertical Workspaces)]: Updating extension ...`
2. Observe windows reset

Regarding the unused screen `0` I could not see any logs pop up, seems to happen randomly when moving windows to new screen. I'd love to get a screenshot, but failed to reproduce it when I started writing.

And regarding app window moving: It does not happen every time but when it does, I get this in log:
```clutter_actor_set_child_above_sibling: assertion 'sibling->priv->parent == self' failed```

Those 2 stack traces are easily reproducible and do not cause windows reset without the update before them:
1. Press Super key
2. Click on any anything (does not need to be window) on secondary (laptop) screen. Does not reproduce when clicking on primary screen at all. Does not matter which window is active on which screen.
4. Both stack traces appear in log

**Expected behavior**
App windows stay where I put them.

**Screenshots**

**System:**
![image](https://github.com/G-dH/vertical-workspaces/assets/150897693/784196ac-585f-4ea9-9161-c2a6468da941)
 - Source of installation: GitHub commit 43dcb8c22383afae0f705b2b817a62df938ece20
 - Other installed and enabled extensions: Only other enabled is Background Logo

**System log output**
```
Dec 12 19:11:56 fedora gnome-shell[230568]: value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
Dec 12 19:11:56 fedora gnome-shell[230568]: value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
Dec 12 19:12:21 fedora gnome-shell[230568]: value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
Dec 12 19:12:22 fedora gnome-shell[230568]: value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
Dec 12 19:12:22 fedora gnome-shell[230568]: value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
Dec 12 19:12:22 fedora gnome-shell[230568]: value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
Dec 12 19:12:22 fedora gnome-shell[230568]: value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
Dec 12 19:12:22 fedora gnome-shell[230568]: value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
Dec 12 19:12:22 fedora gnome-shell[230568]: value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
Dec 12 19:12:28 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:28 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:29 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:30 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:30 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:30 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:32 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:32 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:34 fedora gnome-shell[230568]: [V-Shell (Vertical Workspaces)]: Updating extension ...
Dec 12 19:12:34 fedora gnome-shell[230568]: Object .Gjs_ui_workspaceThumbnail_ThumbnailsBox (0x55db617a1040), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                            == Stack trace for context 0x55db50be60c0 ==
                                            #0   7ffd4824ee70 I   file:///home/theta/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/workspacesView.js:391 (1f606539c4c0 @ 453)
                                            #1   7ffd48250660 b   resource:///org/gnome/shell/ui/workspace.js:856 (221ee0ec0a10 @ 378)
                                            #2   7ffd48250710 b   resource:///org/gnome/shell/ui/workspace.js:808 (221ee0ec0970 @ 17)
                                            #3   7ffd48253150 b   resource:///org/gnome/shell/ui/workspacesView.js:1014 (2b9d9b0b0b0 @ 129)
                                            #4   55db50caf908 i   resource:///org/gnome/shell/ui/overviewControls.js:699 (221ee0e7bd30 @ 50)
                                            #5   55db50caf880 i   resource:///org/gnome/shell/ui/layout.js:373 (1f60653cefb0 @ 22)
                                            #6   55db50caf7f0 i   resource:///org/gnome/shell/ui/overview.js:650 (221ee0e77ba0 @ 164)
                                            #7   7ffd48256230 b   file:///home/theta/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/util.js:83 (221ee0eeed80 @ 73)
                                            #8   55db50caf770 i   resource:///org/gnome/shell/ui/overview.js:636 (221ee0e77b50 @ 12)
                                            #9   55db50caf6f0 i   resource:///org/gnome/shell/ui/overviewControls.js:750 (221ee0e7bf60 @ 55)
                                            #10   7ffd48256c50 b   resource:///org/gnome/shell/ui/environment.js:84 (1f606537d100 @ 39)
                                            #11   55db50caf668 i   resource:///org/gnome/shell/ui/environment.js:250 (1f606537d600 @ 14)
                                            #12   55db50caf5d8 i   resource:///org/gnome/shell/ui/init.js:21 (1f6065370ba0 @ 48)
Dec 12 19:12:34 fedora gnome-shell[230568]: Object .Gjs_ui_workspaceThumbnail_ThumbnailsBox (0x55db617a1040), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                            == Stack trace for context 0x55db50be60c0 ==
                                            #0   7ffd4824ee70 I   file:///home/theta/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/workspacesView.js:392 (1f606539c4c0 @ 468)
                                            #1   7ffd48250660 b   resource:///org/gnome/shell/ui/workspace.js:856 (221ee0ec0a10 @ 378)
                                            #2   7ffd48250710 b   resource:///org/gnome/shell/ui/workspace.js:808 (221ee0ec0970 @ 17)
                                            #3   7ffd48253150 b   resource:///org/gnome/shell/ui/workspacesView.js:1014 (2b9d9b0b0b0 @ 129)
                                            #4   55db50caf908 i   resource:///org/gnome/shell/ui/overviewControls.js:699 (221ee0e7bd30 @ 50)
                                            #5   55db50caf880 i   resource:///org/gnome/shell/ui/layout.js:373 (1f60653cefb0 @ 22)
                                            #6   55db50caf7f0 i   resource:///org/gnome/shell/ui/overview.js:650 (221ee0e77ba0 @ 164)
                                            #7   7ffd48256230 b   file:///home/theta/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/util.js:83 (221ee0eeed80 @ 73)
                                            #8   55db50caf770 i   resource:///org/gnome/shell/ui/overview.js:636 (221ee0e77b50 @ 12)
                                            #9   55db50caf6f0 i   resource:///org/gnome/shell/ui/overviewControls.js:750 (221ee0e7bf60 @ 55)
                                            #10   7ffd48256c50 b   resource:///org/gnome/shell/ui/environment.js:84 (1f606537d100 @ 39)
                                            #11   55db50caf668 i   resource:///org/gnome/shell/ui/environment.js:250 (1f606537d600 @ 14)
                                            #12   55db50caf5d8 i   resource:///org/gnome/shell/ui/init.js:21 (1f6065370ba0 @ 48)
Dec 12 19:12:34 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:34 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:44 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:44 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:50 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:50 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:58 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed
Dec 12 19:12:58 fedora gnome-shell[230568]: g_closure_unref: assertion 'closure->ref_count > 0' failed

```

**Personal Note**
Thank you so much for this extension, it is awesome! I've been using it for very long time on several machines and this is the 1st time I'm seeing issues. If you need any more testing, I will be happy to do it :)

**Comment by G-dH** [comment]
Hello and thanks for the feedback!

> Did disabling all other extensions help? No

This information seems to be misleading - if you can reproduce this issue without V-Shell then the "No" is correct and you should report it to GNOME. If you haven't tested it properly, please do so.

> Moving app from laptop to between screen 1 and 2 to spawn a new screen with the app fails and places app window on existing screen 2 instead.

What is the meaning of "screen" here? Display, workspace, or both?

Generally, some errors in the log are inevitable when monitors configuration change (monitor connected or disconnected), V-Shell waits couple of seconds to avoid fatal conflicts with the Shell and then restarts its modules to adapt to the change.

**Comment by jakub-krysl-ipf** [comment]
Hi @G-dH , sorry it took me so long. I was testing the bugs without any plugins at all (that includes Vertical Workspaces) as you suggested. I understood `disablind OTHER extensions` means keeping Vertical Workspaces but nothing else and since I saw it in stack trace, I assumed the issue is there.

I was wrong.

I reproduced all the issues without Vertical Workspaces which means they are in GNOME and I will go and report them there. Vertical Workspaces only seem to make the issues a bit worse, but there is probably little you can do about it.

> What is the meaning of "screen" here? Display, workspace, or both?

In this case it means workspace. I click super key, take an app window from laptop screen and move it to external (primary) screen between workspace 1 and 2 to spawn a new workspace in between them.

> Generally, some errors in the log are inevitable when monitors configuration change (monitor connected or disconnected), V-Shell waits couple of seconds to avoid fatal conflicts with the Shell and then restarts its modules to adapt to the change.

All the errors in logs are without touching any configuration. I did not dis/connect any monitor. I can see the error logs even with just open terminal, tailing the logs and not touching a thing. There are some actions that produce more error logs, but generally speaking there is something going on on background that produces them by itself.

Thanks for you suggestions, I'll close this since it's in GNOME. Sorry for raising it here :)
If there is any development in GNOME pointing back, I will reopen it.
