### ISSUE TITLE
Gestures are not applied immediately on startup

### ISSUE THREAD

**Issue by UltimateBoomer** [G-dH/vertical-workspaces#12]
When Vertical Workspaces is enabled, the new gestures are not applied immediately until I perform an original gesture. For example, the gesture to switch workspaces (three finger up/down swipe) does not work right after gnome session starts, I have to perform the three finger left/right swipe once before the new gestures start working.

**Comment by G-dH** [comment]
Distro? Does the problem persist if  all other extensions are disabled?

**Comment by UltimateBoomer** [comment]
I'm using Pop OS 22.04 with vanilla Gnome 42.2 on Wayland (not Pop session), and this problem does still happen with all other extensions disabled. I've tested other vertical workspace extensions (vertical overview and pop workspaces) and their gestures work immediately on enabling them.

Just to further clarify the problem, when I log in with vertical workspaces enabled or when I enable vertical workspaces, none of the gestures from vertical workspaces work. But when I perform a three finger swipe left or right, which triggers switch workspace by Gnome default, the problem goes away and all vertical workspaces gestures work. A similar situation happens when I disable vertical workspaces. All of the vertical workspaces gestures still work even after the extension is disabled, until I perform any of the gestures and then the default gestures take over.

**Comment by G-dH** [comment]
Thanks for info. The issue exists on Fedora too. I don't use computer with trackpad, so I didn't notice, even if tested the swipeTracker orientation before. I don't know how to fix this yet.
