### ISSUE TITLE
[BUG] Turned off OsdWindow module "overwrites" custom css

### ISSUE THREAD

**Issue by meybonomme** [G-dH/vertical-workspaces#120]
**Describe the bug**
I have custom css in `./themes` folder to change OSD window position, because default position overlaps partially Dash to Dock: `.osd-window { margin-bottom: 120px; }`. It works fine, until I will activate V-Shell extension. Even if OsdWindow module is turned off, OSD window will stay in default location.

**To Reproduce**
1. Use custom CSS in ./themes folder to change OSD window position
2. Turn on V-Shell extension: OSD window is back in default position, custom CSS will not work anymore.
3. Turn off OsdWindow module: OSD window is still in default location, custom CSS will not work
4. Turn off whole V-Shell extension: custom CSS will work again and OSD window position is changed

**System:**
 - Fedora 39, Gnome 45.2
 - Version of V-Shell extension: 43
 - Source of installation: extension.gnome.org

**Comment by meybonomme** [comment]
Sidenote: why extension won't have ability to change OSD window position in pixels from bottom or top?

**Comment by G-dH** [comment]
V-Shell adds `margin: 4em` in its `stylesheet.css`, that's the reason disabling the module doesn't help you. You can overwrite it there for now.

> why extension won't have ability to change OSD window position in pixels from bottom or top?

You can open a feature request or send PR.

**Comment by G-dH** [comment]
I've increased the bottom margin to make it usable for most dock users.

**Comment by meybonomme** [comment]
I got extension update to v48, but still the same:

```css
.osd-window {
	margin: 4em;
}
```

**Comment by G-dH** [comment]
It's not yet on e.g.o, you can install it from this repository ;)

**Comment by meybonomme** [comment]
Thank You! :slightly_smiling_face: 

I think this solution is good enough and I will close this issue.
