### ISSUE TITLE
[BUG] Extension stopped working, after Dec 19 update - missing gschemas.compiled

### ISSUE THREAD

**Issue by camerongoodman** [G-dH/vertical-workspaces#121]
**Describe the bug**
Extension stopped working, after an update I believe.  The error is

`
GLib.FileError: Failed to open file “/home/user/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/schemas/gschemas.compiled”: open() failed: No such file or directory
`

When I navigate to that location the file gschemas.compiled does not exist.

**Basic debug information**
Uninstalled and reinstalled the extension - file still missing.
If I manually add gschemas.compiled to the folder the extension works.

**System:**
 - OS: Ubuntu 23.10
 - Version of V-Shell extension: 45
 - Source of installation: From gnome extension manager by Matthew Jakeman https://github.com/mjakeman/extension-manager

**Comment by fnordmorph** [comment]
same or similar issue. Fedora 39 WSE up to date as of this morning. Only other user installed gnome extensions are custom hot corners and power profile switcher.  V-Shell working off and on since updating to F39/gnome 45. Tried manual install methods after experiencing the above issue, unable to get any of them to work.

**Comment by G-dH** [comment]
Sorry, the schema should be compiled on your system.. In any case, I've already uploaded the updated package on e.g.o., it's waiting for reviewer. Thanks for reporting this.

**Comment by G-dH** [comment]
The fixed package is available on e.g.o, does it work for you?

**Comment by Vermoot** [comment]
Hey, I did have the exact same issue and yes, it's fixed now :+1: Thanks for your reactivity!

**Comment by G-dH** [comment]
Thanks for the feedback!
