### ISSUE TITLE
How to set wallpaper for each workspace i didn't see any particular setting 

### ISSUE THREAD

**Issue by Mikasa8324** [G-dH/vertical-workspaces#122]
How to set different wallpaper for each workspace using v shell I am using gnome shell 45.1 can somebody tell me how to do this

**Comment by G-dH** [comment]
There is no such option in the V-Shell.

**Comment by Mikasa8324** [comment]
> There is no such option in the V-Shell.

Ooh sorry by looking at pictures i think this feature also exists  
Soory for that
