### ISSUE TITLE
[BUG] Notification dots are too close to app name in App Grid

### ISSUE THREAD

**Issue by meybonomme** [G-dH/vertical-workspaces#125]
Notification dots are too close to app name in App Grid.

Can you add also more bottom margin to App Grid page indicator dots for dock users? Dock won't overlap dots but these are too close to the dock.

**Screenshots**
![Screenshot from 2024-01-18 00-45-58](https://github.com/G-dH/vertical-workspaces/assets/147217565/2c178a93-cd3c-446c-9470-bef7e8d507f9)

**System:**
 - OS: Fedora 39
 - Version of V-Shell extension: 48
 - Source of installation: extension.gnome.org

**Comment by G-dH** [comment]
I'll fix it. Thanks.
