### ISSUE TITLE
[BUG] Black background in application menu on second monitor

### ISSUE THREAD

**Issue by Majo111** [G-dH/vertical-workspaces#126]
The background of app menu is often black on second monitor. There is a shot:

![Snímka obrazovky zo dňa 2024-01-15 16-13-06](https://github.com/G-dH/vertical-workspaces/assets/31368840/d2dde063-1221-4a98-997a-a127cb022194)

**System:**
 - OS: Manjaro
 - Version of V-Shell extension: 48
 - Source of installation: [Extension manager]

**Comment by Majo111** [comment]
Yes, you are right. It happens randomly. Sometimes there is all OK and sometimes not. In most cases is background in overview OK. Problem is only app grid. Reopen overview has no effect on app grid background. My extensions are Burn my windows, Coverflow alt-tab, Disable unredirect fullscreen windows, Hide activities button, Hide top bar, Transparent top bar, Vitals, V-shell, Custom accent colors, Dash to dock, Gnome 4x UI improvements, Legacy (GTK3) Theme scheme Auto Switcher, User themes and Pamac updates indicator. My theme is Colloid.

Output from journalctl /usr/bin/{gjs,gnome-shell} -fo cat:

Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Terminal without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Terminal without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
JS LOG: Characters Application exiting
value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed

**Comment by G-dH** [comment]
Have you tried my [patched Dash to Dock for V-Shell](https://github.com/G-dH/dash-to-dock/tree/v-shell-patch)? You can install it along with the original one, it has a different uuid.

**Comment by G-dH** [comment]
Can you add `export SHELL_DEBUG=backtrace-warnings` to your `~/.profile` or `~/.bash_profile` so we can see source of the warnings when the background disappears? Requires reboot.

**Comment by meybonomme** [comment]
> Have you tried my [patched _Dash to Dock for V-Shell_](https://github.com/G-dH/dash-to-dock/tree/v-shell-patch)?

Sorry for off topic, but I'm curious what exactly has been patched? I can see code, but in human readable format please.

**Comment by G-dH** [comment]
@meybonomme DtD's `docking` module overrides the same code as V-Shell does, including startup animation and overview allocation.

**Comment by G-dH** [comment]
@meybonomme V-Shell does a lot to mitigate potential conflicts, but at startup it's about the order in which both extensions are enabled. Which cannot be easily set, unfortunately.

**Comment by meybonomme** [comment]
@G-dH so your recommendation is to use patched DtD to avoid all possible conflicts?

**Comment by G-dH** [comment]
@meybonomme My recommendation is to not use DtD at all with V-Shell ;)

**Comment by G-dH** [comment]
@meybonomme My recommendation is to not use DtD at all with V-Shell.

Sorry for the duplications, some error in my GitHub app..

**Comment by G-dH** [comment]
@Majo111 Are you still experiencing this issue?

**Comment by G-dH** [comment]
Feel free to reopen if you need.
