### ISSUE TITLE
[BUG] Application menu disappears

### ISSUE THREAD

**Issue by rendgineer** [G-dH/vertical-workspaces#127]
After rebooting, the application menu disappears.

![Снимок экрана от 2024-01-26 12-16-27](https://github.com/G-dH/vertical-workspaces/assets/157794833/ff4f7d42-db27-4563-befe-c96f1f98702e)

**Comment by G-dH** [comment]
Sorry, update is pending on e.g.o. It's in the windows/recent files search modules.
