### ISSUE TITLE
[FEATURE] Option to expand "new workspace at start" area in workspace selector.

### ISSUE THREAD

**Issue by karol-haltenberger** [G-dH/vertical-workspaces#128]
When in overview mode using dynamic workspaces I keep struggling with dragging windows to a new workspace a the start of the list. The drop area where gnome accepts the window is too small to be used comfortably.

It would be great if the drop area could be expanded....maybe even styled with a border, color etc.

Alternatively adding another empty workspace to the beginning (like the one at the end) would work too, if it's possible to do from an extension.

Thanks.

**Comment by G-dH** [comment]
You can drag the window to the last empty workspace or between the first and second workspaces, then switch to that workspace and move it to the first position using scroll wheel or PageUp key while holding down the Shift key.

**Comment by karol-haltenberger** [comment]
Thanks for the tip, I didn't know the shift-scroll switch.

But this "trick" just replaces one precise movement with three or more less precise ones.
I would say it breaks the "flow" even more.


Great extension BTW.

**Comment by G-dH** [comment]
Try dragging the window to the workspace thumbnails from the top/left (depending on the workspace orientation), like from outside the thumbnails, the drop zone should be longer in this direction.

**Comment by karol-haltenberger** [comment]
Again, thanks for trying to help work around the problem...and if you can't or won't "fix it" that's fine...but the in the end the drop area is just too small.
I can drag windows around, up and down (vertical in my case) and all with ease, it's just this SOB that is "slippery" (see video).
In my view one should be able to just "throw" the window there, as one can to the last empty workspace.

[Screencast from 2024-01-29 10-49-17.webm](https://github.com/G-dH/vertical-workspaces/assets/1299074/68ca5c09-24b9-491b-94cd-1e86494847a6)

**Comment by G-dH** [comment]
Thanks for your feedback. Unfortunately, increasing the size of the placeholder requires more than just changing one property.

**Comment by G-dH** [comment]
I found something. If you wan to improve your experience, you can try this:
Open `~/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/workspaceThumbnail.js`,
edit `WORKSPACE_CUT_SIZE` constant, it's in pixels.
GS developers note to this constant:
> When we create workspaces by dragging, we add a "cut" into the top and bottom of each workspace so that the user doesn't have to hit the placeholder exactly.

Save the file and restart session. Let me know what number is acceptable for you. It's a compromise, and the bigger the 'cut', the smaller the area for dropping a window on an existing workspace, which can be a problem with smaller thumbnails. Maybe I could recalculate the size as a percentage of the thumbnail size..

**Comment by G-dH** [comment]
@karol-haltenberger ^

**Comment by karol-haltenberger** [comment]
Although not a perfect solution, this definitely helps.

For my current monitor/resolution of x1440 , where the thumbnails are 180-ish pixels (vertical) it's best in the range of 25 to 50, where 25 is somewhat of an improvement and more than 50 starts to interfere with placement inside the actual workspaces.

In percentages I would say more than 25% is too much.

This adjustment also improves placement between the workspaces IMHO.

**Comment by G-dH** [comment]
It increases the cuts on both sides of each ws thumbnail. I'll try to do something about it.

**Comment by G-dH** [comment]
If you're still interested, you can try the latest update from the `main` for GNOME 45+ or `gnome-42-44` for older GNOME versions.
