### ISSUE TITLE
[Feature Request] Scroll workspaces on window edges

### ISSUE THREAD

**Issue by lonix1** [G-dH/vertical-workspaces#13]
Please consider adding support for switching to the workspace above/below when scrolling the mouse over the window's top/bottom.

The same as the [Desktop Scroller](https://github.com/BrOrlandi/Desktop-Scroller-GNOME-Extension) extension, which doesn't work anymore on gnome 42.

**Comment by G-dH** [comment]
If you mean screen edge, you can use my other extension [Custom Hot Corners - Extended](https://github.com/G-dH/custom-hot-corners-extended), which allows you that and much more. This feature is out of scope of VW.

**Comment by lonix1** [comment]
That extension is incredible. Thank you!

I suggest you put a link to that other extension, so people won't miss it.

**Comment by G-dH** [comment]
Glad you like it :)

**Comment by G-dH** [comment]
Btw, I'm also working on the [OFP](https://github.com/G-dH/overview-feature-pack) extension that adds useful features and options to the Activities overview and extends VW's capabilities. Also check the rest of my extensions here on GitHub or [e.g.o](https://extensions.gnome.org/accounts/profile/GdH).
