### ISSUE TITLE
[FEATURE] toggle for alt+mousewheel workspace switcher

### ISSUE THREAD

**Issue by wfleurant** [G-dH/vertical-workspaces#130]
**Is your feature request related to a problem? Please describe.**

cannot determine how to disable key/mouse combination ALT + MouseWheel. with v-shell, it allows user to scroll up/down between workspaces. this is perfect using a mouse but with touchpad it can get in the way.

it seems to interfere with existing ALT + TwofingerTap (right click) and followed by dragging the window to resize it.
   
so, on the touchpad. user must hard-press without any vertical scrolling motion in order to trigger window resize. this is a problem because its very easy to trigger mousewheel on touchpad vs. mouse (obviously).. so its sort of a pebble in the shoe.

**Describe the solution you'd like**

i would like to toggle enable/disable alt+mousewheel.  
when docked, i would keep it enabled.  
when mobile, i would disable it.

**Describe alternatives you've considered**
no, i cant live without vertical workspaces =)

**Comment by G-dH** [comment]
The only related thing that V-Shell does is switching trackpad orientation according to the workspaces orientation. I don't know about Alt+Wheel shortcut, but there is Super+Wheel in GNOME for switching workspaces. Don't forget to check other enabled extensions.

**Comment by wfleurant** [comment]
aah.. strange.  

i disable v-shell and it does not trigger. when enabled, it is alt + two-finger down (mouse-wheel down?)

i can try some more things thanks for the hints and active development i'll take a closer look.

**Comment by wfleurant** [comment]
resolved with: gnome-tweaks >> Windows >> Window Action Key = disabled.

**Comment by G-dH** [comment]
Are you using vertical orientation of workspaces? Have you tried V-Shell with horizontal orientation if it makes a difference?
