### ISSUE TITLE
[BUG] unable to move cursor between monitors

### ISSUE THREAD

**Issue by scr4bble** [G-dH/vertical-workspaces#131]
**Describe the bug**

I have two monitors. 1 is on left side, 2 is on right side. 2 is primary. When I am in 2 and I want to move to left monitor, my cursor bumps into left side of the primary monitor and opens the app grid (windows overview) instead of transitioning into the second monitor on the left side.

**Basic debug information**
 This extension causes the app overview to display when bumping into left side of the primary monitor.

_I believe it should stay on the default behavior when app overview only opens when moving cursor to the top-left side of the screen._

**Expected behavior**
I would expect to be able to move my cursor to the second monitor instead of bumping to the left side and opening app grid.

**System:**
 - OS: Fedora 39
 - Version of V-Shell extension: 45.3/52
 - Source of installation: extension.gnome.org
 - Other installed and enabled extensions: many, but most of them (if not all) are probably irrelevant

**Comment by scr4bble** [comment]
Seems like this can be resolved by changing "Hot Corner Position" from "Follow Dash - Hot Edge" to "Default".
"Default" wasn't interestingly preselected by default.

So this issue should probably be _make the "Default" option default_.

**Comment by G-dH** [comment]
The "Default" in V-Shell means behavior in vanilla GNOME Shell.

**Comment by scr4bble** [comment]
Ok, I understand. But is there a good reason why in this particular case the default is not the same in V-shell? People can still use keyboard to open the applications overview and having whole side as hot position seems to be quite disrupting also for one monitor setup, not talking about this breaking behavior in multi monitor setup where such side cannot be used as passage to the second monitor.

**Comment by G-dH** [comment]
I believe that the hot edge option is set only for the profile 4 with the dash on the bottom...

**Comment by scr4bble** [comment]
Ok, I am not aware of loading any particular profile from the list of the predefined profiles. I just installed the extension and started editing the settings directly as they were.
So I still think this might be considered a bug that affects multi-monitor setups because the "default" settings (meaning the settings user gets after extension installation) are breaking passage to the second monitor in case that monitor is on the left side of the primary monitor.

IMHO the left top corner is a better default fot hot corner settings.

**Comment by G-dH** [comment]
You're right, the default configuration of the latest public version includes the hot edge that follows dash. I changed it some time ago, the next release default will be different.
