### ISSUE TITLE
[FEATURE] intelligente overview

### ISSUE THREAD

**Issue by JE-Amouel** [G-dH/vertical-workspaces#134]
hi,
I often work with several workspaces each having several windows, so I wanted to give you a suggestion for an option that will go really well with everything that this extension already offers that is exceptional, so there you have it, an intelligent scrolling workspace option, oft the goal would be that when we scroll on a workspace which has more than one window that we switch to overview on this workspace (like this we can select a window) and when there is only one window the scroll will do this normally.
that was my feature suggetsion.
 
thamks.

**Comment by G-dH** [comment]
I'm not sure I understand well... How do you "scroll on a workspace"?

**Comment by JE-Amouel** [comment]
for the moment I no longer use the keyboard shortcuts Ctlr+Alt+up|down arrow to change workspaces, well suppose I have 2 workspaces, on the first I have an enlarged application window , and on the other I have two enlarged windows, and suppose I am on the first workspace, normally if I use the keyboard shortcuts to move to the second workspace (the one which contains two enlarged windows), I would like when switching to the second workspace to have the choice of selecting one of the two windows, via the overview,
in fact the overview will be triggered when scrolling, if the target workspace contains more than one window.
