### ISSUE TITLE
Question - Virtual workspaces for verical and horizontal

### ISSUE THREAD

**Issue by Diakonix** [G-dH/vertical-workspaces#135]
Hi guys, is it possible to set virtual workspaces both vertically and horizontally at once?

**Comment by G-dH** [comment]
Hi. No, it's not possible.

**Comment by Diakonix** [comment]
Thank you for your answer. 
In my opinion, adding this feature would be a great idea.

**Comment by G-dH** [comment]
Do you mean a classic matrix or workspaces arranged in two vectors?

**Comment by Diakonix** [comment]
Oh thank you! I was looking for [Workspace Matrix](https://extensions.gnome.org/extension/1485/workspace-matrix/).
