### ISSUE TITLE
[FEATURE] Middle-click behaviour control for dash

### ISSUE THREAD

**Issue by DanMan** [G-dH/vertical-workspaces#136]
**Describe the solution you'd like**

After booting I usually open multiple programs from my dash. But if you click them with the left mouse button, the overview closes and I have to invoke it again to access the dash so you can launch the next one. That's distracting and annoying.

**Describe alternatives you've considered**

I know a ctrl-click already does what I want, but I'd prefer, if clicking an icon with the middle mouse button caused the overview to stay open, too. Why require 2 hands, if one is enough?

**Comment by G-dH** [comment]
What about using drag-and-drop?

**Comment by DanMan** [comment]
Didn't know that was a thing. Would have expected that to be the way to remove an icon from the dash, kinda like Apple.

But yeah, I guess that works for me, too. Cheers.

**Comment by G-dH** [comment]
The advantage is that you can launch new windows directly onto any workspace by dropping the icon onto a workspace or workspace thumbnail.
