### ISSUE TITLE
[BUG] GNOME 46 compatibility

### ISSUE THREAD

**Issue by jeames00** [G-dH/vertical-workspaces#137]
**Describe the bug**
The extension doesn't load/function after upgrading to GNOME 46

**Basic debug information**
 - Disabling all other extensions didn't help
 - "Extension Manager" reports that it is incompatible when running its "Upgrade Assistant"

**To Reproduce**
- Install the extension with current version of GNOME 46

**Expected behavior**
Extension should operate as it did in GNOME 45

**Screenshots**
![image](https://github.com/G-dH/vertical-workspaces/assets/42809499/04091fa9-baf7-41b5-88e3-0b50d5c266df)

**System:**
 - OS: openSUSE Tumbleweed
 - Version of V-Shell extension: 52
 - Source of installation: extension.gnome.org
 - Other installed and enabled extensions: Alphabetical App Grid

**Comment by G-dH** [comment]
The V-Shell that supports 46 has not yet been released on e.g.o. You can install the development version from this repository (Instructions are in the README) and help me by reporting bugs, if you find any.

**Comment by kimitrois** [comment]
> The V-Shell that supports 46 has not yet been released on e.g.o. You can install the development version from this repository (Instructions are in the [README](https://github.com/G-dH/vertical-workspaces?tab=readme-ov-file#installation-from-github-repository)) and help me by reporting bugs, if you find any.
> 
> Disable the Alphabetical App Grid extension while running V-Shell, as V-Shell handles the app grid sorting itself.

Hi there , but I am not able to find a development version. Any specific link?
Thanks

**Comment by G-dH** [comment]
Use the `main` branch.

**Comment by axxapy** [comment]
Thank you for your work!

I installed `main` branch and, from the first glance it works fine with a couple exceptions:
 - dash is not vertically/horizontally centered
 - workspace thumbnails do not show wallpaper anymore

_/note/ I've just upgraded to gnome 46. Before today I had gnome 45 with vertical-workspaces enabled => when I installed `main` branch previous extension's settings got applied_

![image](https://github.com/G-dH/vertical-workspaces/assets/3088476/c9d2fa02-13e2-4830-ab68-89102264bdfe)

**Comment by G-dH** [comment]
@axxapy Thanks for the feedback. Some settings may change after the update due to modifications in their default values. Therefore, if the user hasn't applied any custom profiles and left these settings at their defaults, this scenario can occur.

**Comment by Aqua1ung** [comment]
@G-dH, thank you for your hard work! Any ETA when this'll show up in e.g.o.? Did you submit it already?

**Comment by G-dH** [comment]
Soon :)

**Comment by G-dH** [comment]
Version 46.0 is now available on ego.

**Comment by kloczek** [comment]
Is it any plan to release new version of this extension .. sone? 🤔

**Comment by G-dH** [comment]
@kloczek I'll try to release it this week.

**Comment by coldtobi** [comment]
> @kloczek I'll try to release it this week.

Thanks! That will be awesome!
I'm currently preparing to[ package this extension for Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1068957), and an official release would be helpful.

Cheers, tobi
