### ISSUE TITLE
tag versions

### ISSUE THREAD

**Issue by carlwgeorge** [G-dH/vertical-workspaces#14]
I can see that versions are being declared in the metadata.json file, but no tags exist in this repo.  Adding tags to commits that change the version would make it easier for distro maintainers to package this extension.  My particular interest is in adding this to the Fedora repos.  Adding all the historical commits isn't necessary, but could you please at least tag aa6a3e17bc8920fc5d1cfd0db110b4f2a78fb38f as `10.5` and tag future versions going forward?

**Comment by G-dH** [comment]
So far the code in the repository shouldn't be considered stable since it's actually my dev branch and 10.5 is just a transition version. I'll add a release tag with the next release for e.g.o, v11 should be available this weekend.

**Comment by G-dH** [comment]
I've just added the release for v11.
https://github.com/G-dH/vertical-workspaces/releases

**Comment by carlwgeorge** [comment]
Awesome, thank you.  I've packaged that version up and submitted it for inclusion into Fedora.  Once it's available would you like a pull request to add instructions to the README for installing the Fedora package?
