### ISSUE TITLE
[BUG] workspace thumbnail alignment inconsistancy against `dash-to-panel`

### ISSUE THREAD

**Issue by bartoszek** [G-dH/vertical-workspaces#141]
**Describe the bug**
The `Workspace Thumbnail` column switches sides depending on which monitor the `Activities` indicator is clicked when `dash-to-panel` extension is configured to show `Activities` indicator on each monitor.

**Basic debug information**
 - Did disabling all other extensions help? `yes`
 - Did you find a conflicting extension? [dash-to-panel](https://github.com/home-sweet-gnome/dash-to-panel)

**To Reproduce**
Steps to reproduce the behaviour:
- set `Workspace Thumbnail` to the inner/outer edge a dual-monitor setup.
- set `dash-to-panel` to show `Activities` indicator on each monitor.
- click `Activities` indicator on each monitor.

**Expected behavior**
`Workspace Thumbnail` columns location being deterministic.

**Screenshots**
[Screencast from 2024-04-09 16-37-55.webm](https://github.com/G-dH/vertical-workspaces/assets/1213348/2e9fe5af-a197-401c-a249-50a4f80ec890)

**System:**
 - OS: [e.g. Arch]
 - Version of V-Shell extension: [e.g. 46]
 - Source of installation: [extension.gnome.org]
 - Other installed and enabled extensions: `$gsettings get org.gnome.shell enabled-extensions`
 ```'nvidiatemp@baco'
'pixel-saver@deadalnix.me'
'text_translator@awamper.gmail.com'
'customcorner@eccheng.gitlab.com'
'brightness_control@lmedinas.org'
'TaskBar@zpydr'
'system-monitor@paradoxxx.zero.gmail.com'
'places-menu@gnome-shell-extensions.gcampax.github.com'
'drive-menu@gnome-shell-extensions.gcampax.github.com'
'screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com'
'glassygnome@emiapwil'
'TopIcons@phocean.net'
'apps-menu@gnome-shell-extensions.gcampax.github.com'
'simple-dock@nothing.org'
'indicator-sensors@alexmurray.github.com'
'maximus@luis.pabon.auronconsulting.co.uk'
'openweather-extension@jenslody.de'
'overview-navigation@nathanielsimard.github.com'
'LogOutButton@kyle.aims.ac.za'
'workspaces-to-dock@passingthru67.gmail.com'
'unite@hardpixel.eu'
'multi-monitors-add-on@spin83'
'activities-config@nls1729'
'arch-update@RaphaelRochet'
'cast-to-tv@rafostar.github.com'
'gse-haguichi-indicator@ztefn.github.com'
'vertical-overview@RensAlthuis.github.com'
'pano@elhan.io'
'emoji-copy@felipeftn'
'pamac-updates@manjaro.org'
'miniview@thesecretaryofwar.com'
'gTile@vibou'
'steal-my-focus-window@steal-my-focus-window'
'user-theme@gnome-shell-extensions.gcampax.github.com'
'clipboard-indicator@tudmotu.com'
'EndSessionTimer@pratap.fastmail.fm'
'ShutdownTimer@deminder'
'xwayland-indicator@swsnr.de'
'TeaTimer@zener.sbg.at'
'uptime-indicator@gniourfgniourf.gmail.com'
'otp-keys@osmank3.net'
'wiggle@mechtifs'
'runcat@kolesnikov.se'
'weatherornot@somepaulo.github.io'
'burn-my-windows@schneegans.github.com'
'freon@UshakovVasilii_Github.yahoo.com'
'EasyScreenCast@iacopodeenosee.gmail.com'
'windows-search-provider@G-dH.github.com'
'vertical-workspaces@G-dH.github.com'
'dash-to-panel@jderose9.github.com'
'azclock@azclock.gitlab.com'
```

**Comment by G-dH** [comment]
Have you tried `Layout` -> `Secondary Monitors` -> `Shift Workspace Preview by Panel Height` option?

Some notes regarding your extension list:
I assume that the list contains extensions that you have already removed from the system, otherwise, I wouldn't believe that you only have issues with aligning workspace thumbnails. If you remove an extension without disabling it first, it will remain in the list of enabled extensions.
- The `Vertical Overview` extension is obviously not compatible with V-Shell
- You don't need the `Steal My Focus` extension, V-Shell provides the `Window Attention Handler` setting in the `Notifications` section on the `Behavior` tab
- Instead of `Miniview`, try my `WTMB (Window Thumbnails)` extension

**Comment by bartoszek** [comment]
* `Layout` -> `Secondary Monitors` -> `Shift Workspace Preview by Panel Height` option has no effect on after mentioned issue.
* `Vertical Overview` just a leftover I forgot to remove after gnome-shell update (it's been disabled for ages)
* `WTMB` nice way of starting PiP with a shortcut, but it's missing drag resize and scroll to switch previews for me 👍🏽

**Comment by G-dH** [comment]
OK, I'll look into it.
Regarding WTMB, you can configure the scroll wheel to switch between source windows in the Settings. Since it offers adjustable default scale and provides full-size preview on click and hover, resizing may not be as crucial. However, I'll probably add drag resizing in the future. Right now, I'm adding media controls support.

**Comment by bartoszek** [comment]
* Regarding `Shift Workspace Preview by Panel Height` options: it causes `Workspace Thumbnail` to jiggle up and down when hovering over the second screen window previews.

**Comment by G-dH** [comment]
I wasn't able to reproduce your issue, the workspace thumbnails are stable on my system. The allocation code reads the panel height, so if this property changes for some reason, this issue may occur. Have you tried disabling all other extensions except for V-Shell and DtP?

**Comment by G-dH** [comment]
I did some tests, and I found that DtP causes various allocation issues that I cannot compensate for. For me, DtP never worked well, especially with secondary monitors. I will refactor the secondary monitors allocation, but don't expect special compensations for the DtP mess.

**Comment by G-dH** [comment]
@bartoszek Please try the latest update from the `main` branch. The `Shift Overview by Panel Height` option should now work better for your configuration.

**Comment by G-dH** [comment]
@bartoszek Are you not interested anymore?

**Comment by G-dH** [comment]
Feel free to reopen or give feedback about the fix.
