### ISSUE TITLE
[BUG] Adaptive grid folders no longer expand past 4x4, don't overflow to second page since GNOME 46

### ISSUE THREAD

**Issue by fotnite-vevo** [G-dH/vertical-workspaces#142]
**Describe the bug**
On GNOME 45, adaptive grid folders were able to have multiple pages, and (I think) get larger than 4x4. Since GNOME 46, this is no longer the case, and large folders don't display properly and might not display all the apps inside them, since all apps will be attempted to display on one page.

I usually use fractional scaling, but using 100% scaling doesn't change anything, folders still won't go past 4x4 etc.

**Basic debug information**
 - Did disabling all other extensions help? _No_
 - Did you find conflicting extension? _No_

**To Reproduce**
1. Set Folder Columns per Page and Folder Rows per Page in Appearance - App Grid to 0 
2. Create a folder with more than 16 apps on the app grid

**Expected behavior**
Apps that don't fit when displaying the folder should overflow to subsequent pages, or the folder should become larger to accomodate

**Screenshots**
![Screenshot from 2024-04-10 00-06-10](https://github.com/G-dH/vertical-workspaces/assets/68102115/1ee3844c-f688-418e-8a83-17c95dc5bda4)

**System:**
 - OS: Arch Linux
 - Version of V-Shell extension: 46.1
 - Source of installation: extension.gnome.org
 - Other installed and enabled extensions: None

**System log output**
open terminal, execute:
`journalctl /usr/bin/{gjs,gnome-shell} -fo cat`
reproduce the bug, copy the output from terminal if any.
_I've included the output just in case, but I don't think it's relevant_
```
libinput error: event20 - Microsoft Surface 045E:09AF Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.25.0/touchpad-jumping-cursors.html for details
libinput error: event20 - Microsoft Surface 045E:09AF Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.25.0/touchpad-jumping-cursors.html for details
libinput error: event20 - Microsoft Surface 045E:09AF Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.25.0/touchpad-jumping-cursors.html for details
libinput error: event20 - Microsoft Surface 045E:09AF Touchpad: WARNING: log rate limit exceeded (5 msgs per 24h). Discarding future messages.
```

**Comment by fotnite-vevo** [comment]
I'm unsure if this should be considered a duplicate of #92, since this only began happening to me recently and it does present a bit differently than what was shown in the screenshots on the other issue.

**Comment by G-dH** [comment]
Thanks. Please update V-Shell from the `main` branch and let me know how the fix works for you.

**Comment by fotnite-vevo** [comment]
Yes, this seems to fix the issue. Thanks!
