### ISSUE TITLE
[BUG] Crashes gnome on Ubuntu 24.04 (BETA) with Ubuntu Dock extension enabled

### ISSUE THREAD

**Issue by 64knl** [G-dH/vertical-workspaces#145]
**Describe the bug**
When enabling both vertical-windows and the default 'Ubuntu dock' extension GNOME will just display a white screen after logging in.

**Basic debug information**
 - Did disabling all other extensions help?
Yes
 - Did you find conflicting extension?
Yes, Ubuntu dock

**To Reproduce**
1. Enable both extensions (everything still works)
2. Log out 
3. Log back in
4. Screen is all white with no usable elements 

**System:**
 - OS: [e.g. Fedora 38]
 - Version of V-Shell extension: main (compiled just now) and store version
 - Source of installation: GIT
 - Other installed and enabled extensions: 

1. burn-my-windows@schneegans.github.com
2. grand-theft-focus@zalckos.github.com
3. wifiqrcode@glerro.pm.me
4. pano@elhan.io
5. vertical-workspaces@G-dH.github.com
6. blur-my-shell@aunetx
7. azclock@azclock.gitlab.com
8. monitor@astraext.github.io
9. ControlBlurEffectOnLockScreen@pratap.fastmail.fm
10. ubuntu-appindicators@ubuntu.com
11. ubuntu-dock@ubuntu.com
12. pomodoro@arun.codito.in
13. apps-menu@gnome-shell-extensions.gcampax.github.com
14. drive-menu@gnome-shell-extensions.gcampax.github.com
15. system-monitor@gnome-shell-extensions.gcampax.github.com
16. tiling-assistant@ubuntu.com

**System log output**
```
Execution of main.js threw exception: Module resource:///org/gnome/shell/ui/init.js threw an exception
Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Terminal without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
JS LOG: Characters Application started
Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Terminal without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
```

**Comment by G-dH** [comment]
Please, try to reinstall V-Shell from the `main` branch and let me know how it works for you.
Now if V-Shell detects conflicting extension (for now it's Ubuntu Dock, Dash to Dock and Dash to Panel) it delays the activation and waits for the `startup-complete` signal.
