### ISSUE TITLE
[BUG] No translucent overlay surrounding the folder

### ISSUE THREAD

**Issue by meybonomme** [G-dH/vertical-workspaces#147]
Default GNOME Shell app grid have translucent overlay surrounding the folder, but V-Shell is missing it:

![Screenshot from 2024-04-28 16-52-57](https://github.com/G-dH/vertical-workspaces/assets/147217565/3cdab021-4b16-464c-bebc-fb5c09d5b8f9)

I don't know, is it bug or feature, but with opened folder and surrounding translucent overlay app grid seems much nicer. Without it, the folder's surroundings will look empty and flat.

**Comment by G-dH** [comment]
It wouldn't be so nice because V-Shell uses a transparent background in folder dialogs.

**Comment by meybonomme** [comment]
Of course, I didn't come up with this, as I myself prefer to use a solid gray background without wallpaper.

Now this is more of a feature request, but would it be possible to make a change, if Overview Background > Show Wallpaper is switched off, then the background of the folder is not translucent, but the background surrounding the folder is translucent and the app icons in the background are shown?

**Comment by G-dH** [comment]
I don't like the default folder view at all :)

**Comment by G-dH** [comment]
The truth is that a nice background can help with the emptiness :) For me, it's the difference in overall screen brightness that irritates me the most.

**Comment by meybonomme** [comment]
The truth is always very subjective :)

For me, the wallpaper in the app grid is distracting. The solid gray background creates better contrast and colored icons stand out better. In addition, I use the Wallpaper Slideshow extension, which changes the background images. For some wallpapers, the contrast would become very poor. Plus when Wallpaper Slideshow changes the wallpaper, the blurring is gone from the app grid. So I definitely prefer a solid gray background. I'd rather accept this emptiness.

**Comment by G-dH** [comment]
The wallpaper is distracting, but icons aren't? My solution is actually better for you, you just haven't realized it yet ;)

**Comment by meybonomme** [comment]
I've tried few times with wallpaper and I don't like it. I think it's perfectly okay to disagree, people have different tastes ;)

I like the contrast between the gray background and the colorful icons. By the way, I use Papirus icons, which are more colorful and contrasty than Adwaita icons. The clean, simple and contrast-enough look is what really appeals to me about the GNOME desktop.

I don't mean to say you have bad taste, it's just different :) You are doing a very good job with V-Shell and I appreciate it!

**Comment by G-dH** [comment]
I'm not talking about wallpaper,  I'm talking about the distraction-free folder view.

**Comment by meybonomme** [comment]
Sorry for misunderstood, probably you are right :)
I think I can close this issue.

**Comment by G-dH** [comment]
I appreciate your feedback. Even if I disagree, it can help.

**Comment by meybonomme** [comment]
I'm always happy to help and contribute!

I really like GNOME desktop and open source software, clean and visually nice GUI is my big weakness. Even though I can't code (yet) I have already contributed in one project as a GUI designer and I am happy to contribute in other projects as well. If you want to chat privately about these topics and discuss details, my Matrix address is @meybonomme:matrix.org
I think all discussions are not best suited here :)

**Comment by G-dH** [comment]
I'm not a big debater, it takes me more effort than most people, but I'm glad when someone challenges my work, it allows me to realize things I wouldn't otherwise see.

**Comment by meybonomme** [comment]
I think you can handle it pretty well and we understand each other's opinions. Anyway, if you want, I'm here to help and think along :)
