### ISSUE TITLE
[FEATURE] With adaptive grid folder maximum size is too big

### ISSUE THREAD

**Issue by meybonomme** [G-dH/vertical-workspaces#148]
The folder fits on the screen, but it is too big and there is basically almost no empty area that you can click on to exit the folder with the mouse/touchpad.

![Screenshot from 2024-04-28 16-55-55](https://github.com/G-dH/vertical-workspaces/assets/147217565/0ab99699-dd56-4a98-a705-95284bac4832)

**Comment by G-dH** [comment]
You can use the secondary mouse button inside the folder to close it or you can click on panel or dash. You can also set the grid size dimensions.

**Comment by meybonomme** [comment]
Thanks, I didn't realize that a second click inside the folder can also be used to exit the folder. That said, the maximum folder width could be narrower, as the app grid aren't stretched with adaptive grid from edge to edge of the screen either. I suggest that with an adaptive grid, the maximum number of icons per row in a folder could be the same as the main app grid.

**Comment by G-dH** [comment]
Btw, I've been refactoring and fixing the whole app grid module for the last couple of days. What about changing the folder grid dimensions options to Max Columns/Rows, so it will stay adaptive within the limits, instead of the fixed grid?

**Comment by meybonomme** [comment]
Sounds like a very good idea!

The built-in screen of my laptop is 15.6" 1920x1080 and I use 100% scaling there, while the external 24" 2560x1440 uses 125% scaling, so a fixed grid is not suitable for both. In the case of your proposed solution, it would be possible to adjust the folder grid to suit both.

**Comment by G-dH** [comment]
Please, let me know how the latest update works for you.

**Comment by meybonomme** [comment]
- Overlay styling conflict with DtD is gone
- Folders have more empty surrounding area, very nice
- App folders - maximum number of columns/rows - even better!
- The startup conflict between V-Shell and DtD is significantly less noticeable and desktop loading is much smoother
- I found one potential bug, but I will test a little bit more and then will report to you
- Overall, the updates are very positive and I like the app grid even more with V-Shell now, because it looks cleaner and more professional
- Very good job! :slightly_smiling_face:

**Comment by G-dH** [comment]
Thanks. I sent another commit that fixes app search results highlighting and adds close button to app folder dialogs.
