### ISSUE TITLE
[FEATURE] Add function to close the overview / app grid by clicking empty space

### ISSUE THREAD

**Issue by meybonomme** [G-dH/vertical-workspaces#149]
Currently I'm using "Click To Close Overview" extension: https://extensions.gnome.org/extension/3826/click-to-close-overview/

This small and simple extension adds the possibility to close overview / app grid by clicking empty space. I think this is something that could be integrated into V-Shell. It only contains a few dozen lines of code:

```
import * as Main from 'resource:///org/gnome/shell/ui/main.js';
import Clutter from 'gi://Clutter';

export default class ClickToCloseOverview {
	enable() {
		/* create new click action */
		this._clickAction = new Clutter.ClickAction();
		this._clickAction.connect('clicked', action => {
			/* ignore non-primary clicks */
			if (action.get_button() !== 1 && action.get_button() !== 0)
				return;

			/* clicked actor */
			const [x, y] = global.get_pointer();
			const actor = global.stage.get_actor_at_pos(Clutter.PickMode.ALL, x, y);

			/* ignore clicks inside search box */
			const searchBox = Main.overview._overview._controls._searchEntry;
			if (actor === searchBox || actor.get_parent() === searchBox
					|| actor.get_parent().get_parent() === searchBox)
				return;

			Main.overview.toggle();
		});
		/* connect click action to the overview */
		Main.layoutManager.overviewGroup.add_action(this._clickAction);
	}

	disable() {
		/* disconnect click action from the overview */
		Main.layoutManager.overviewGroup.remove_action(this._clickAction);
		delete this._clickAction;
	}
}
```

**Comment by meybonomme** [comment]
Installed your update, but it only works in overview, but not in app grid.

**Comment by G-dH** [comment]
It works outside the app grid, preventing closing the overview when interacting with it.

**Comment by meybonomme** [comment]
Please make it work with app grid too, at least optionally. This is the main feature of the "Click To Close Overview" extension I use, but unfortunately it doesn't work with V-Shell now either.

> It works outside the app grid, preventing closing the overview when interacting with it.

**Comment by G-dH** [comment]
It works in the app grid view, but you need to click an empty space, not the app grid. I added this feature only because it's more consistent behavior if you disable workspace preview background. But honestly, I don't understand why anyone would open the app grid just to close it. How often do you actually use the app grid, and how often do you need to close it without launching an application?

**Comment by G-dH** [comment]
OK, I've removed the app grid blocker and added the option to disable it.

**Comment by meybonomme** [comment]
Thank you for taking the feedback into account and for developing V-Shell with great dedication! 

I keep my V-Shell updated via the Github repository and test changes. I will provide more detailed feedback when I find more time. Some bug reports and also some ideas to improve V-Shell.

**Comment by G-dH** [comment]
Can we close this issue?

**Comment by meybonomme** [comment]
I'm sorry I haven't found time to answer more thoroughly.

> But honestly, I don't understand why anyone would open the app grid just to close it. How often do you actually use the app grid, and how often do you need to close it without launching an application?

For example, to use the search and if you don't find what you want, to leave the App Grid. I use it very often for various reasons. Yes, I can also use the Super key or the Esc key, but the mouse click is much more intuitive.

However, I have found time to test and think about the concept of navigating with mouse buttons:

- The logic of closing App Folders is very good and intuitive. A primary click outside the folder closes the folder, similar to the logic of using Android. Secondary click on an empty area inside of folder also closes the folder, using a secondary mouse click to go back/close seems perfectly logical. For example, Dahua NVRs use the same logic for navigation, that a second mouse click takes you back.
- We could use the exact same logic for App Grid. Since the Application Grid doesn't have clear outlines, exiting could only work with a secondary mouse click. As you said and you are absolutely right:

> ...preventing closing the overview when interacting with it.

If you accidentally click past the icon area, the Application Grid will close immediately, which is really not good. The primary mouse click outside of the App Grid also doesn't feel good as there are no clear lines where App Grid starts or ends.

**Comment by G-dH** [comment]
Thanks.

**Comment by meybonomme** [comment]
Would you consider removing the primary click to exit the app grid and leaving only the secondary click option? I'm getting more and more aware that your original concept was better, and it's starting to bother me that accidentally clicking past the icon closes the app grid.

**Comment by G-dH** [comment]
Sure :)

**Comment by meybonomme** [comment]
Thank you. Issue can be closed now.
