### ISSUE TITLE
Application menu move down to top after lockscreen

### ISSUE THREAD

**Issue by galen1423** [G-dH/vertical-workspaces#15]
Hi,

Context: I have tweak my dock settings for than application menu to be as top instead bottom; then I lock my screen (Win + L).
Bug:       After unlocked screen to return active session, this menu is back to bottom.
OS:        Ubuntu 22.10 (development branch) with Gnome Shell 43

Thanks for this very useful extension. :)

**Comment by G-dH** [comment]
You mean Ubuntu dock? What exactly did you do with the menu?

**Comment by galen1423** [comment]
The "Show applications" menu is defaulted bottom placed and I've check the box Dash to Dock extension to place it at top.

**Comment by G-dH** [comment]
I'm sorry, I'm not a DtD user. What version of DtD are you using? Where I can find the option? Add screenshots if needed.

**Comment by galen1423** [comment]
Dash to Dock is version 73 (last version up to date)
[https://pix.cyber-nux.fr/?img=1662409603.png](url)

**Comment by G-dH** [comment]
So you mean 'Show applications' icon. Open VW settings and set the position on the `Layout` tab - option `Show Apps Icon Position` `Start/End`
