### ISSUE TITLE
[BUG] "Updating V-Shell" notification at session startup

### ISSUE THREAD

**Issue by meybonomme** [G-dH/vertical-workspaces#151]
If "Smooth App Grid Animation" is active, there is "Updating V-Shell" notification at every session startup. This notification is useful when changing V-Shell settings, but it is annoying and looks unprofessional when the session starts. Can you hide this notification at session startup?

It's more like enhancement not a bug.

**Comment by G-dH** [comment]
That's because V-Shell is enabled after the Shell's startup, which happens because of DtD ;)

**Comment by meybonomme** [comment]
I know, you are doing a good job to avoid conflicts between V-Shell and DtD. But my question was, can you hide/remove this notification from session startup?

**Comment by meybonomme** [comment]
Your fix works very well, thank you!
