### ISSUE TITLE
[BUG] Click behaviour on app grid / search panel items changed in 46.1

### ISSUE THREAD

**Issue by pcercuei** [G-dH/vertical-workspaces#152]
**Describe the bug**
Before 46.1 (not sure what I was using - the first version that supported Gnome 45), I had the extension configured so that a click on an application icon in the dash, in the menu grid or on in the search panel would always open a new window.

This still works (and the option is still here) when clicking on an application icon in the dash, but it does not work anymore when clicking on an application in the search panel.

**Basic debug information**
 - Did disabling all other extensions help?
 - Did you find conflicting extension?

No and no.

**To Reproduce**
1. Launch e.g. a terminal using the dash, the grid menu or the search menu
2. Launch the same application from the search menu
3. The application won't launch a new window.

**Expected behavior**
This is an expected behavior because it used to be configurable before V-Shell 46.1.
There should be an "App Icon - Click behavior" option for items in the grid menu and the search panel, just like the one that exists already for the dash icons.

**System:**
 - OS: Debian testing
 - Version of V-Shell extension: 46.1
 - Source of installation: extension.gnome.org
 - Other installed and enabled extensions: Emoji Copy, Freon

**Comment by G-dH** [comment]
You're right, I've moved the override from the `AppIcon` to `DashIcon`. I'll look into it.

**Comment by pcercuei** [comment]
Yep, that works now. Thanks!
