### ISSUE TITLE
[BUG] Conflict w/Dash2Dock Animated

### ISSUE THREAD

**Issue by Aqua1ung** [G-dH/vertical-workspaces#153]
**Describe the bug**
Looks like there's a conflict with @icedman's [Dash2Dock Lite](https://github.com/icedman/dash2dock-lite), whereby the dock labels for the mounted drives disappear upon enabling the V-Shell extension. Disabling V-Shell makes the labels re-appear. More details [here](https://github.com/icedman/dash2dock-lite/issues/141).

**Basic debug information**
See description above.

**Comment by G-dH** [comment]
Simply disable the `Dash` module on the `Modules` tab in V-Shell Settings. I'll add the extension to the blacklist later.

**Comment by icedman** [comment]
Fix for this should be at Dash2Dock Lite. The mounted devices icon is a special icon and should faithfully mimic app icons for better compatibiliy.

**Comment by G-dH** [comment]
@icedman Thanks for the info. In any case, I doubt that all of V-Shell's options for the dash are compatible with DtD Animated.
