### ISSUE TITLE
[BUG] Alphabetical and Usage settings for App Folder Order are broken

### ISSUE THREAD

**Issue by fotnite-vevo** [G-dH/vertical-workspaces#154]
**Describe the bug**
No matter what the "App Folder Order" setting is set to, folders will always be sorted as though it were set to "Custom". The folder preview uses the correct order, but the app icons seen once opening the folder will always be in custom order.

The Main App Grid "Sorting" setting works as expected, only the App Folder Order setting is broken.

**Basic debug information**
 - Did disabling all other extensions help?
          No.
 - Did you find conflicting extension?
          No.

**To Reproduce**
1. Open extension settings
2. Go to App Grid > App Folders > App Folder Order and set it to anything that isn't Custom

**Expected behavior**
App Folder Order setting is reflected when a folder is opened

**Screenshots**
Folder when "App Folder Order" is set to Alphabet (follows ordering that was set when using Custom):

![Screenshot from 2024-05-12 07-25-37](https://github.com/G-dH/vertical-workspaces/assets/68102115/0c5f2e2f-afdb-49ab-bb7d-2444ab46daa0)

Preview of same folder with the same settings (behaves as expected, uses follows alphabetical ordering):

![Screenshot from 2024-05-12 07-25-26](https://github.com/G-dH/vertical-workspaces/assets/68102115/0900fb5f-dbcc-4316-9227-90acaf079c1c)

**System:**
 - OS: Fedora 40
 - Version of V-Shell extension: 46.1
 - Source of installation: extension.gnome.org
 - Other installed and enabled extensions: Nonc

**System log output**
open terminal, execute:
`journalctl /usr/bin/{gjs,gnome-shell} -fo cat`
reproduce the bug, copy the output from terminal if any.

**Comment by G-dH** [comment]
Thanks! I'll fix.
