### ISSUE TITLE
[BUG] V-Shell overrides Dash to Dock's background style

### ISSUE THREAD

**Issue by Davidekiller1999** [G-dH/vertical-workspaces#155]
when the PC restarts, although the transparent background of the dash is set in the "dash to dock" extension, the latter remains clearly visible, as if the setting had never been activated. this doesn't happen when I disable your extension. however, by restarting the dash to dock extension every time the PC starts, the problem does not arise.
I tried various solutions both via your extension and via "dash to dock"; for example, I turned off "dash" in v-shell settings, but nothing changed.
Thanks for the attention. Your extension is really great! good job!

Debian 12.5

**Comment by G-dH** [comment]
Thanks.
