### ISSUE TITLE
Problem with version 11 und Dash to Dock

### ISSUE THREAD

**Issue by MasterPJ** [G-dH/vertical-workspaces#16]
With the last update (11), the compatibility "fix" for dash to dock is enabled by default even after a reboot. This option introduce an error which make icons not appear in the dock if an application is launched from the app grid. Fixing the issue: disable the compatibility option, disable und re-enable dash to dock (it happens with both DtD and DtD for Cosmic).
Can replecate 100% of the time. Please just dont let the compatibility option be enable automatically by default, or let me disable it but saving my choice at reboot! Using Ubuntu 22.04. 
Tnx

**Comment by G-dH** [comment]
Without the option enabled the VW overview crashes because the DtD repeatedly injects the overview allocation method, so I don't see a point in disabling it. It's the same code as in v10, the only difference is that the option is being automatically enabled if VW detects the DtD running, to avoid unnecessary bug reports.

I'm unable to reproduce the issue on my U22.04 and Fedora 36/37.
- In the terminal execute:
`journalctl /usr/bin/gnome-shell -fo cat`
reproduce the issue and check the log output
- Wayland or X11?
- What other extensions are enabled? Disable them all and check if the issue persists.

**Comment by MasterPJ** [comment]
I'm on X11 because i have a Nvidia card, Wayland is not an option yet. I disabled all, re-enabled only DtD and vertical workspaces and the issue is still there. If i disable manually the compatibility option of your extension everything runs just perfect, but with update 11 the option will be re-enabled on startup and that's my problem here. The command you gave me shows me this:

`Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
JS ERROR: Invalid work id 3: Error: Invalid work id 3
queueDeferredWork@resource:///org/gnome/shell/ui/main.js:910:18
_queueRedisplay@resource:///org/gnome/shell/ui/dash.js:476:14

JS ERROR: Invalid work id 4: Error: Invalid work id 4
queueDeferredWork@resource:///org/gnome/shell/ui/main.js:910:18
_queueRedisplay@resource:///org/gnome/shell/ui/dash.js:476:14
_queueRedisplay@/home/masterpj/.local/share/gnome-shell/extensions/dash-to-dock-cosmic-@halfmexicanhalfamazing@gmail.com/dash.js:321:52

JS ERROR: Invalid work id 3: Error: Invalid work id 3
queueDeferredWork@resource:///org/gnome/shell/ui/main.js:910:18
_queueRedisplay@resource:///org/gnome/shell/ui/dash.js:476:14

JS ERROR: Invalid work id 4: Error: Invalid work id 4
queueDeferredWork@resource:///org/gnome/shell/ui/main.js:910:18
_queueRedisplay@resource:///org/gnome/shell/ui/dash.js:476:14
_queueRedisplay@/home/masterpj/.local/share/gnome-shell/extensions/dash-to-dock-cosmic-@halfmexicanhalfamazing@gmail.com/dash.js:321:52
`

**Comment by G-dH** [comment]
Change the Dash placement in the VW settings to top or bottom while you're using DtD. The problem here is VW redirects redisplay to the modified Dash. I'll fix it.

**Comment by MasterPJ** [comment]
Just tried, it didn't fix the problem... i wish you could just maybe enable your fix by default if you think it's better for most people, but also let us disable that fix and save this choice permanently in case of issues like mine.

**Comment by G-dH** [comment]
It fixes the problem DtD 73. The option is not the culprit, if you use DtD, you need it and it only restores VW code inside the Shell.

**Comment by G-dH** [comment]
Please, try the latest version from the repository and let me know.

**Comment by MasterPJ** [comment]
> Please, try the latest version from the repository and let me know.

Sorry but i dont know how to do that -.- i always install or update extensions from extensions.gnome.org

**Comment by G-dH** [comment]
It's in the README:

    git clone https://github.com/G-dH/vertical-workspaces.git
    cd vertical-workspaces/
    make install

**Comment by MasterPJ** [comment]
updated, and IT WORKS!
The issue is gone, even with the fix option enabled like with the last version.

Thank you very much for your patience and for your (quick and very good) work :D

**Comment by G-dH** [comment]
Thank you for the bug report and testing ;)
