### ISSUE TITLE
[FEATURE] Search field position if workspace thumbnails are disabled

### ISSUE THREAD

**Issue by meybonomme** [G-dH/vertical-workspaces#161]
When workspace thumbnails are disabled, the search box appears too pushed up. This is especially noticeable from the first screenshot. There is empty space and "air" everywhere, but the search field is pushed almost against the top panel. I think there could be more top margin/padding.

I know the search field could be hidden altogether, but I like it visible. In addition, if you hide it, there is no search at all for the regular user.

![Screenshot from 2024-05-22 02-48-38](https://github.com/G-dH/vertical-workspaces/assets/147217565/0c2076bc-857e-4b29-9a73-d4b110719f41)
![Screenshot from 2024-05-22 01-57-41](https://github.com/G-dH/vertical-workspaces/assets/147217565/4e4bd2d7-b72c-411b-8cf9-da98f58c877b)

**Comment by G-dH** [comment]
If you need more space above the search entry, you can adjust `margin-top` of the `search-entry` css class.
