### ISSUE TITLE
[BUG] error in ubunu 24.04

### ISSUE THREAD

**Issue by kurokirasama** [G-dH/vertical-workspaces#163]
**Describe the bug**

It cannot be activated. 

**Basic debug information**
 - Did disabling all other extensions help?
 no
 - Did you find conflicting extension?
no

**To Reproduce**
In settings I got this error:
```
The settings of extension vertical-workspaces@G-dH.github.com had an error:

GLib.FileError: Failed to open file “/home/kira/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/schemas/gschemas.compiled”: open() failed: No such file or directory

Stack trace:
  getSettings@resource:///org/gnome/Shell/Extensions/js/extensions/sharedInternals.js:100:53
  fillPreferencesWindow@file:///home/kira/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/prefs.js:77:34
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:41:18
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:26:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:17:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

```

**Expected behavior**
It should work.

**Screenshots**

**System:**
 - OS: [e.g. Fedora 38] Ubuntu 24.04
 - Version of V-Shell extension: [e.g. 25] 46.2
 - Source of installation: [e.g. extension.gnome.org, GitHub] extension.gnome.org
 - Other installed and enabled extensions: ...
Bluetooth quick connect
blur my shell
frippery move clock
logo menu
unite
auto move windows
removable drive menu
ubuntu tiling assistant
user themes

**System log output**
open terminal, execute:
`journalctl /usr/bin/{gjs,gnome-shell} -fo cat`
reproduce the bug, copy the output from terminal if any.

**Comment by G-dH** [comment]
It should work, but it needs to be properly installed. If you just copied the files from the archive, you need to compile the schema:

    glib-compile-schemas ./schemas/
