### ISSUE TITLE
[BUG] Folders in app grid sometimes open on the upper left corner of the screen.

### ISSUE THREAD

**Issue by TulparBey** [G-dH/vertical-workspaces#166]
**Describe the bug**
Sometimes folders in app grid open on the upper left corner of the screen.

**Basic debug information**
I didn't find a conflicting extension. I believe it usually happens when I log out and log in or suspend the PC and wake it up.

**To Reproduce**
(like I mentioned it might be due to locking/suspending but I am not %100 sure.)
1. Go to app grid
2. Click on any folder
3. See the error

**Expected behavior**
Folders should open centered.

**Screenshots**
![Ekran Görüntüsü - 2024-05-29 01-20-09](https://github.com/G-dH/vertical-workspaces/assets/114747838/5fa6625f-1536-4510-8b4c-545e8be278a3)

**System:**
 - OS: Ubuntu 24.04
 - Version of V-Shell extension: 62
 - Source of installation: Extension manager by mjakeman.
 - Other installed and enabled extensions: user-themes, blur my shell, ddcutil, quick setting tweaker, caffeine, gsconnect, ubuntu dock and ubuntu appindicators.

**System log output**
Object .Gjs_ui_calendar_NotificationSection (0x6226e3c2aae0), has been already disposed — impossible to connect to any signal on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x6226db9c9670 ==
#0   7fffa2916060 b   resource:///org/gnome/shell/misc/signalTracker.js:123 (1582ca0fc880 @ 101)
#1   7fffa2916120 b   resource:///org/gnome/shell/misc/signalTracker.js:157 (33e43a66a380 @ 47)
#2   7fffa2916220 b   resource:///org/gnome/shell/misc/signalTracker.js:245 (33e43a6d0880 @ 727)
#3   7fffa29162f0 b   resource:///org/gnome/shell/ui/environment.js:246 (33e43a6861f0 @ 126)
#4   6226dba8d148 i   resource:///org/gnome/shell/ui/calendar.js:869 (3b118c340b50 @ 48)
#5   6226dba8d090 i   resource:///org/gnome/shell/ui/messageTray.js:857 (3b118c337970 @ 155)
#6   6226dba8cff0 i   resource:///org/gnome/shell/ui/messageTray.js:876 (3b118c337ab0 @ 98)
#7   6226dba8cf50 i   resource:///org/gnome/shell/ui/messageTray.js:846 (3b118c3378d0 @ 210)
#8   6226dba8cea8 i   file:///home/lightubuntu/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:99 (1582ca07e2e0 @ 479)
#9   6226dba8ce18 i   resource:///org/gnome/shell/ui/init.js:21 (33e43a670bf0 @ 48)
JS ERROR: TypeError: this._settings is null
_sync@resource:///org/gnome/shell/ui/dateMenu.js:795:28
_updateCount@resource:///org/gnome/shell/ui/dateMenu.js:791:14
_onSourceAdded@resource:///org/gnome/shell/ui/dateMenu.js:778:14
_addSource@resource:///org/gnome/shell/ui/messageTray.js:857:14
_onSourceEnableChanged@resource:///org/gnome/shell/ui/messageTray.js:876:22
add@resource:///org/gnome/shell/ui/messageTray.js:846:14
_onWindowDemandsAttention@file:///home/lightubuntu/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:99:26
@resource:///org/gnome/shell/ui/init.js:21:20

Object .Gjs_ui_calendar_NotificationSection (0x6226e2b7f0b0), has been already disposed — impossible to connect to any signal on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x6226db9c9670 ==
#0   7fffa2916060 b   resource:///org/gnome/shell/misc/signalTracker.js:123 (1582ca0fc880 @ 101)
#1   7fffa2916120 b   resource:///org/gnome/shell/misc/signalTracker.js:157 (33e43a66a380 @ 47)
#2   7fffa2916220 b   resource:///org/gnome/shell/misc/signalTracker.js:245 (33e43a6d0880 @ 727)
#3   7fffa29162f0 b   resource:///org/gnome/shell/ui/environment.js:246 (33e43a6861f0 @ 126)
#4   6226dba8d148 i   resource:///org/gnome/shell/ui/calendar.js:869 (3b118c340b50 @ 48)
#5   6226dba8d090 i   resource:///org/gnome/shell/ui/messageTray.js:857 (3b118c337970 @ 155)
#6   6226dba8cff0 i   resource:///org/gnome/shell/ui/messageTray.js:876 (3b118c337ab0 @ 98)
#7   6226dba8cf50 i   resource:///org/gnome/shell/ui/messageTray.js:846 (3b118c3378d0 @ 210)
#8   6226dba8cea8 i   file:///home/lightubuntu/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:99 (1582ca07e2e0 @ 479)
#9   6226dba8ce18 i   resource:///org/gnome/shell/ui/init.js:21 (33e43a670bf0 @ 48)
JS ERROR: TypeError: this._settings is null
_sync@resource:///org/gnome/shell/ui/dateMenu.js:795:28
_updateCount@resource:///org/gnome/shell/ui/dateMenu.js:791:14
_onSourceAdded@resource:///org/gnome/shell/ui/dateMenu.js:778:14
_addSource@resource:///org/gnome/shell/ui/messageTray.js:857:14
_onSourceEnableChanged@resource:///org/gnome/shell/ui/messageTray.js:876:22
add@resource:///org/gnome/shell/ui/messageTray.js:846:14
_onWindowDemandsAttention@file:///home/lightubuntu/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:99:26
@resource:///org/gnome/shell/ui/init.js:21:20

Object .Gjs_ui_calendar_NotificationSection (0x6226e30df8f0), has been already disposed — impossible to connect to any signal on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x6226db9c9670 ==
#0   7fffa2916060 b   resource:///org/gnome/shell/misc/signalTracker.js:123 (1582ca0fc880 @ 101)
#1   7fffa2916120 b   resource:///org/gnome/shell/misc/signalTracker.js:157 (33e43a66a380 @ 47)
#2   7fffa2916220 b   resource:///org/gnome/shell/misc/signalTracker.js:245 (33e43a6d0880 @ 727)
#3   7fffa29162f0 b   resource:///org/gnome/shell/ui/environment.js:246 (33e43a6861f0 @ 126)
#4   6226dba8d148 i   resource:///org/gnome/shell/ui/calendar.js:869 (3b118c340b50 @ 48)
#5   6226dba8d090 i   resource:///org/gnome/shell/ui/messageTray.js:857 (3b118c337970 @ 155)
#6   6226dba8cff0 i   resource:///org/gnome/shell/ui/messageTray.js:876 (3b118c337ab0 @ 98)
#7   6226dba8cf50 i   resource:///org/gnome/shell/ui/messageTray.js:846 (3b118c3378d0 @ 210)
#8   6226dba8cea8 i   file:///home/lightubuntu/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:99 (1582ca07e2e0 @ 479)
#9   6226dba8ce18 i   resource:///org/gnome/shell/ui/init.js:21 (33e43a670bf0 @ 48)
JS ERROR: Error: No property notifications on Gjs_ui_messageTray_Notification
Notification@resource:///org/gnome/shell/ui/messageTray.js:354:9
_onWindowDemandsAttention@file:///home/lightubuntu/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:103:30
@resource:///org/gnome/shell/ui/init.js:21:20

JS ERROR: TypeError: this._settings is null
_sync@resource:///org/gnome/shell/ui/dateMenu.js:795:28
_updateCount@resource:///org/gnome/shell/ui/dateMenu.js:791:14
_onSourceRemoved@resource:///org/gnome/shell/ui/dateMenu.js:783:14
_removeSource@resource:///org/gnome/shell/ui/messageTray.js:863:14
_addSource/<@resource:///org/gnome/shell/ui/messageTray.js:855:35
destroy@resource:///org/gnome/shell/ui/messageTray.js:585:14
destroy@file:///home/lightubuntu/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:156:56
_init/<@file:///home/lightubuntu/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:130:33
@resource:///org/gnome/shell/ui/init.js:21:20

JS ERROR: TypeError: this._settings is null
_sync@resource:///org/gnome/shell/ui/dateMenu.js:795:28
_updateCount@resource:///org/gnome/shell/ui/dateMenu.js:791:14
_onSourceRemoved@resource:///org/gnome/shell/ui/dateMenu.js:783:14
_removeSource@resource:///org/gnome/shell/ui/messageTray.js:863:14
_addSource/<@resource:///org/gnome/shell/ui/messageTray.js:855:35
destroy@resource:///org/gnome/shell/ui/messageTray.js:585:14
destroy@file:///home/lightubuntu/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:156:56
_init/<@file:///home/lightubuntu/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:130:33
@resource:///org/gnome/shell/ui/init.js:21:20

JS ERROR: TypeError: this._settings is null
_sync@resource:///org/gnome/shell/ui/dateMenu.js:795:28
_updateCount@resource:///org/gnome/shell/ui/dateMenu.js:791:14
_onSourceRemoved@resource:///org/gnome/shell/ui/dateMenu.js:783:14
_removeSource@resource:///org/gnome/shell/ui/messageTray.js:863:14
_addSource/<@resource:///org/gnome/shell/ui/messageTray.js:855:35
destroy@resource:///org/gnome/shell/ui/messageTray.js:585:14
destroy@file:///home/lightubuntu/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:156:56
_init/<@file:///home/lightubuntu/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:130:33
@resource:///org/gnome/shell/ui/init.js:21:20

JS ERROR: TypeError: this._settings is null
_sync@resource:///org/gnome/shell/ui/dateMenu.js:795:28
_updateCount@resource:///org/gnome/shell/ui/dateMenu.js:791:14
_onSourceRemoved@resource:///org/gnome/shell/ui/dateMenu.js:783:14
_removeSource@resource:///org/gnome/shell/ui/messageTray.js:863:14
_addSource/<@resource:///org/gnome/shell/ui/messageTray.js:855:35
destroy@resource:///org/gnome/shell/ui/messageTray.js:585:14
destroy@file:///home/lightubuntu/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:156:56
_init/<@file:///home/lightubuntu/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:130:33
@resource:///org/gnome/shell/ui/init.js:21:20

**Comment by G-dH** [comment]
Are you able to reproduce the bug with all other extensions disabled?

**Comment by TulparBey** [comment]
Thx for the reply but as of now, I can't reproduce the error anymore. Maybe it was related to my system or sth I don't know but it's fine now.

**Comment by G-dH** [comment]
For the `windowAttentionHandler` errors, you can test the latest repository version.
