### ISSUE TITLE
[BUG] switching to the overview directly shows the first workspace, and not the current workspace

### ISSUE THREAD

**Issue by JE-Amouel** [G-dH/vertical-workspaces#167]
**Describe the bug**
when i am toggle to overview, some time,  it show the first workspace and not the current one.

**Basic debug information**
 - Did disabling all other extensions help? no
 - Did you find conflicting extension? no

**To Reproduce**
1.  open multiple workspaces  
3. go to any of the workspace but not the first.
4. toggle overview

**Expected behavior**
toggling the overview within the workspace number N should  always show this workspace.

**Screenshots**

[Screencast from 2024-05-29 15-28-36.webm](https://github.com/G-dH/vertical-workspaces/assets/146543282/fd8a55c8-bb6b-40e3-abcb-46ae65e4f61d)

**System:**
 - OS: ubuntu 23.10
 - Version of V-Shell extension: 62
 - Source of installation: extension.gnome.org
 - Other installed and enabled extensions: 

**System log output**

value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'

**THANKS**

**Comment by G-dH** [comment]
This usually happens in GNOME Shell after restarting the X11 session. V-Shell should fix this behavior if enabled upon session startup.

**Comment by JE-Amouel** [comment]
It's been a while, I no longer notice this kind of behavior, especially since I don't tinker too much with my extensions.
now i understand why.
THANKS.
