### ISSUE TITLE
[BUG] no responsive behavior with dash-to-panel

### ISSUE THREAD

**Issue by JE-Amouel** [G-dH/vertical-workspaces#168]
Hi,
**Describe the bug**
when dash-to-panel is in intellihide mode it overlaps with workspace thumbnails

**Basic debug information**
N/A

**To Reproduce**
1. put, dash-to panel panel and v-shell workspace thumbnail on the same side of the screen.
2. enable intellihide option in dash to panel
3. toggle overview

**Expected behavior**

**Screenshots**

[Screencast_06_03_2024_07:42:32_PM.webm](https://github.com/G-dH/vertical-workspaces/assets/146543282/de909963-4f4b-41ae-ab96-98683568c96b)

**System:**
 - OS: ubuntu 23.10 (GNOME 45)
 - Version of V-Shell extension: 62
 - Source of installation:  extension.gnome.org
 - Other installed and enabled extensions: ...

**System log output**
open terminal, execute:
`journalctl /usr/bin/{gjs,gnome-shell} -fo cat`

JS ERROR: TypeError: this._settings is null
_sync@resource:///org/gnome/shell/ui/dateMenu.js:781:28
_updateCount@resource:///org/gnome/shell/ui/dateMenu.js:777:14
_onSourceAdded@resource:///org/gnome/shell/ui/dateMenu.js:764:14
_addSource@resource:///org/gnome/shell/ui/messageTray.js:989:14
_onSourceEnableChanged@resource:///org/gnome/shell/ui/messageTray.js:1008:22
add@resource:///org/gnome/shell/ui/messageTray.js:979:14
_onWindowDemandsAttention@file:///home/jason/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:99:26
@resource:///org/gnome/shell/ui/init.js:21:20

Object .Gjs_ui_calendar_NotificationSection (0x56b9ac3eb8f0), has been already disposed — impossible to connect to any signal on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x56b9a73b1c10 ==
#0   7ffcbe5d62f0 b   resource:///org/gnome/shell/misc/signalTracker.js:123 (5219fc80ba0 @ 101)
#1   7ffcbe5d63b0 b   resource:///org/gnome/shell/misc/signalTracker.js:157 (5219fc80d80 @ 47)
#2   7ffcbe5d64b0 b   resource:///org/gnome/shell/misc/signalTracker.js:245 (5219fc80f60 @ 727)
#3   7ffcbe5d6580 b   resource:///org/gnome/shell/ui/environment.js:264 (5219fc7d6a0 @ 126)
#4   56b9a747d700 i   resource:///org/gnome/shell/ui/calendar.js:856 (2eb3851366a0 @ 48)
#5   7ffcbe5d7c90 b   resource:///org/gnome/shell/ui/messageTray.js:989 (2eb38512e3d0 @ 125)
#6   7ffcbe5d83d0 b   resource:///org/gnome/shell/ui/messageTray.js:1008 (2eb38512e510 @ 98)
#7   7ffcbe5d8b10 b   resource:///org/gnome/shell/ui/messageTray.js:979 (2eb38512e330 @ 210)
#8   56b9a747d658 i   file:///home/jason/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:99 (3892410c2290 @ 479)== Stack trace for context 0x56b9a73b1c10 ==
#0   7ffcbe5d6c80 b   resource:///org/gnome/shell/misc/signalTracker.js:123 (5219fc80ba0 @ 101)
#1   7ffcbe5d6d40 b   resource:///org/gnome/shell/misc/signalTracker.js:157 (5219fc80d80 @ 47)
#2   7ffcbe5d6e50 b   resource:///org/gnome/shell/misc/signalTracker.js:245 (5219fc80f60 @ 727)
#3   7ffcbe5d6f30 b   resource:///org/gnome/shell/ui/environment.js:264 (5219fc7d6a0 @ 126)
#4   56b9a747d7a8 i   resource:///org/gnome/shell/ui/calendar.js:866 (2eb3851366f0 @ 174)
#5   56b9a747d700 i   resource:///org/gnome/shell/ui/messageTray.js:763 (2eb38512dc90 @ 267)
#6   7ffcbe5d8b10 b   resource:///org/gnome/shell/ui/messageTray.js:770 (2eb38512dce0 @ 30)
#7   56b9a747d658 i   file:///home/jason/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:113 (3892410c2290 @ 851)
#8   56b9a747d5c8 i   resource:///org/gnome/shell/ui/init.js:21 (5219fc70ba0 @ 48)
Object .Gjs_ui_calendar_NotificationSection (0x56b9ac3eb8f0), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
JS ERROR: TypeError: this._settings is null
_sync@resource:///org/gnome/shell/ui/dateMenu.js:781:28
_updateCount@resource:///org/gnome/shell/ui/dateMenu.js:777:14
_onNotificationShow@resource:///org/gnome/shell/ui/messageTray.js:1050:22
showNotification@resource:///org/gnome/shell/ui/messageTray.js:776:18
_onWindowDemandsAttention@file:///home/jason/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/windowAttentionHandler.js:113:20
@resource:///org/gnome/shell/ui/init.js:21:20

**Comment by G-dH** [comment]
How is this different from #164?

**Comment by JE-Amouel** [comment]
:facepalm: I thought I hadn't told you yet! Sorry, I will be more careful about the request I send. Sorry again !
