### ISSUE TITLE
[BUG] Dragging an icon out of a folder sometimes causes icons to overlap/misplace

### ISSUE THREAD

**Issue by meybonomme** [G-dH/vertical-workspaces#172]
I don't see a pattern to reproduce this bug, it just happens sometimes:

https://github.com/G-dH/vertical-workspaces/assets/147217565/6d9944df-7339-42b2-b504-79a2852d9c8c

Anyway, you've done a great job removing the bugs and even fixed several upstream bugs! All major app grid issues seem to be resolved now :+1:

**Comment by G-dH** [comment]
I appreciate your feedback, I really do. But you can leave out the "great job" / "well done" part in every comment, I'm too old for that ;)

**Comment by meybonomme** [comment]
No one is ever too old to be praised for a job well done.

**Comment by G-dH** [comment]
I'm unable to reproduce this issue.

**Comment by meybonomme** [comment]
I will try to find some pattern how to reproduce this issue.

**Comment by G-dH** [comment]
Don't forget to test it on the default Shell as well.

**Comment by meybonomme** [comment]
This issue can be closed for now. If I have found new and more accurate information, I will let you know.
