### ISSUE TITLE
[BUG] drag and drop of windows has a  small issue

### ISSUE THREAD

**Issue by JE-Amouel** [G-dH/vertical-workspaces#175]
Hi,
**Describe the bug**
I noticed that sometimes the drag and drop of windows has trouble working correctly.

**Basic debug information**
 - Did disabling all other extensions help? 
 - >NO
 - Did you find conflicting extension? 
 - >NO

**To Reproduce**
1. open 2 or 3 apps window
2.  trigger window picker
3.  try to drag and drop window to any workspace through workspace thumbnails

**Expected behavior**

**Screenshots**

[vshell.webm](https://github.com/G-dH/vertical-workspaces/assets/146543282/cac3f15d-a383-4ac5-8e53-a7e95d1d0acd)

**System:**
 - OS Ubuntu 23.10
 - Version of V-Shell extension: 65
 - Source of installation:  extension.gnome.org
 - Other installed and enabled extensions: 
 - >pano@elhan.io
dash-to-panel@jderose9.github.com
arcmenu@arcmenu.com
vertical-workspaces@G-dH.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
cronomix@zagortenay333
forge@jmmaranan.com
workspaces-by-open-apps@favo02.github.com
EasyScreenCast@iacopodeenosee.gmail.com
tweaks-system-menu@extensions.gnome-shell.fifi.org
space-bar@luchrioh
advanced-alt-tab@G-dH.github.com
gsconnect@andyholmes.github.io
quick-settings-tweaks@qwreey
ubuntu-appindicators@ubuntu.com
ubuntu-dock@ubuntu.com

**System log output**
open terminal, execute:
`journalctl /usr/bin/{gjs,gnome-shell} -fo cat`
reproduce the bug, copy the output from terminal if any.

THANKS

**Comment by G-dH** [comment]
Have you tested the Shell without any extensions (including V-shell and all built-in Ubuntu extensions)?
Btw, you should update your Ubuntu to 24.04 LTS.

**Comment by JE-Amouel** [comment]
>Have you tested the Shell without any extensions (including V-shell and all built-in Ubuntu extensions)?
I just tried, everything looks normal,
I have the impression that this only happens with vshell.
>Btw, you should update your Ubuntu to 24.04 LTS.
Okay thanks, i will do it.

**Comment by JE-Amouel** [comment]
I just reactivated vshell and the other extensions and everything works better now.

**Comment by G-dH** [comment]
Just a note: When testing the system after disabling any extensions, don't forget to restart the Shell. Simply disabling the extensions is not sufficient in many cases.

**Comment by JE-Amouel** [comment]
I just restarted, and the previous behavior returned.

**Comment by G-dH** [comment]
Enable only V-Shell, restart, and then test.

**Comment by JE-Amouel** [comment]
now it work good.

**Comment by JE-Amouel** [comment]
after leaving vshell as the only active extension, I tried to start  others extensions one after  others, to see if it was due to a conflict, and I just noticed that, this issue only appears when dash to panel is enabled.

**Comment by G-dH** [comment]
DtP always caused similar issues on my systems, especially when multiple monitors were active.

**Comment by JE-Amouel** [comment]
DTP :facepalm:  , at least now we know the source of this issue !
thank you very much for your support. :smiley:  :+1:
