### ISSUE TITLE
[BUG] Folder height calculation issue

### ISSUE THREAD

**Issue by meybonomme** [G-dH/vertical-workspaces#176]
App Grid Page Height Scale - 95
Rows Per Page is adaptive for Main App Grid and for App Folders
V-Shell is latest from Github repo, as always.

With internal 1920x1080 monitor and 100% scaling I have 4 app grid rows and 4 folder rows. With 125% scaling 3 and 3.

With external 2560x1440 monitor and 100% scaling I have 6 and 6 rows. As it should be and it looks good too. Using 125% scaling I have 5 app grid rows, but only 4 folder rows and there is a lot of empty space under the folder.

In addition, folder content looks bit out of a place. Page dots are too close to folder bottom edge and the folder's app grid also seems too close to the bottom edge.

![Screenshot from 2024-06-29 21-15-05](https://github.com/G-dH/vertical-workspaces/assets/147217565/07756f65-8c71-443c-92e0-dacdae5bd303)

**Comment by G-dH** [comment]
There's nothing "out of place", there's simply not enough space for another row.

**Comment by G-dH** [comment]
Try this.

**Comment by meybonomme** [comment]
If the external monitor has five lines on the main app grid, the folder now also has five lines, mostly. Sometimes there are only four lines again. If I reload the V-Shell profile it fixes the problem and there are five lines in the folder again.

**Comment by meybonomme** [comment]
Every time I drag an icon into or out of a folder, there are four lines instead of five:

https://github.com/G-dH/vertical-workspaces/assets/147217565/e36c5bf8-ab97-4f37-aad1-74e37e824ff3

**Comment by meybonomme** [comment]
Seems to be fixed.
