### ISSUE TITLE
[BUG] Small folders are too wide

### ISSUE THREAD

**Issue by meybonomme** [G-dH/vertical-workspaces#178]
After the latest update from Github repo small folders are too wide.
For example, the contents of this folder used to be divided into four columns and three rows, which was much nicer:

![Screenshot from 2024-07-05 19-40-45](https://github.com/G-dH/vertical-workspaces/assets/147217565/c30e7ef7-5917-4794-a146-1d3c32dd084b)

**Comment by G-dH** [comment]
What is your folder configuration?

**Comment by meybonomme** [comment]
> What is your folder configuration?

![pilt](https://github.com/G-dH/vertical-workspaces/assets/147217565/a5c1a769-8f1d-4a5f-a73d-2d2d12e7fdd6)

**Comment by meybonomme** [comment]
Every time I drag an icon into or out of a folder, there are four lines instead of five:

https://github.com/G-dH/vertical-workspaces/assets/147217565/e36c5bf8-ab97-4f37-aad1-74e37e824ff3

**Comment by meybonomme** [comment]
I can't see any difference.

**Comment by meybonomme** [comment]
Now the issue is solved and small folders are again with the expected aspect ratio.
