### ISSUE TITLE
[BUG] Strange behavior when exiting the app grid

### ISSUE THREAD

**Issue by meybonomme** [G-dH/vertical-workspaces#181]
My Super-key single-press action is "Applications".  When I open the the app grid using Dash to Dock "Show apps" button and then will press the Super key, the app grid closes as expected. When I open the app grid using the Super key and then click the "Show apps" button in the Dash to Dock, the app grid is not closed, but Overview mode appears.

**Comment by G-dH** [comment]
Before filling an issue related to another extension, always test the behavior without V-Shell.

**Comment by meybonomme** [comment]
I have to agree that this is not a V-Shell problem. Sorry.
