### ISSUE TITLE
[BUG] Folders in App Grid Randomly Open in Top Left Corner of Screen

### ISSUE THREAD

**Issue by nsurvance** [G-dH/vertical-workspaces#183]
I saw this bug report here, #166, but their issue seemed to resolve itself.  For me, the issue seemed to resolve itself and then reappeared.  Apologies if I could have reopened the old issue, this is my first time reporting bugs.

**Bug**
The bug seems to appear with folders in the center of the app grid, but switching them around did not change which folder is affected.  You can see this in the older bug report.
When selected, the folder will open in the top left corner of the screen rather than the center.
I tried to rename the folder while it was opened and it crashed my session.

https://github.com/G-dH/vertical-workspaces/assets/58082491/8850df76-6131-40fb-9961-cdf3daf7ba60

**System:**
Fedora Workstation 40
Version 65
Installed from Gnome Extensions

**Other Extensions Enabled**
AppIndicator and KStatusNotifierItem Support
Blur my Shell
Caffeine
Hot Edge
Luminus Shell Y
Tiling Shell
Week Start Modifier

**System log output**
This was the output right after opening the folder.  I'm no expert so I'm hoping this actually pertains to this issue.  Ran using `journalctl /usr/bin/gnome-shell`

```
Jul 09 18:48:56 fedora gnome-shell[24170]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Jul 09 18:49:06 fedora gnome-shell[24170]: Error in size change accounting.
Jul 09 18:49:08 fedora gnome-shell[24170]: Error in size change accounting.
Jul 09 18:50:38 fedora gnome-shell[24170]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Jul 09 18:52:17 fedora gnome-shell[24170]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Jul 09 18:52:19 fedora gnome-shell[24170]: JS ERROR: TypeError: this.actor is null
                                           _syncEnabled@resource:///org/gnome/shell/ui/windowManager.js:145:25
                                           onStopped@resource:///org/gnome/shell/ui/windowManager.js:157:35
                                           _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:65:22
                                           _easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:232:60
                                           _destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1607:21
                                           onStopped@resource:///org/gnome/shell/ui/windowManager.js:1575:39
                                           _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:65:22
                                           _easeActor/<@resource:///org/gnome/shell/ui/environment.js:154:64
                                           @resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by G-dH** [comment]
Please, disable all other extensions, restart Shell and try to reproduce the issue.
Blur My Shell overview/app grid blur may be in conflict with V-Shell.

**Comment by nsurvance** [comment]
I believe disabling Blur My Shell did fix the issue.  I also disabled all other extensions as mentioned.  However, without Blur My Shell, the background overview will not blur on my second monitor when I enable the app grid.  It's fine for the normal desktop overview though.

https://github.com/G-dH/vertical-workspaces/assets/58082491/9d340f5e-ad73-419a-8f51-ad9757b982ca

**Comment by G-dH** [comment]
V-Shell supports secondary monitors. If you adjust the background blur, it should be applied to all monitors.

**Comment by nsurvance** [comment]
Yes but you can see here that with Blur My Shell disabled, the blur on the second monitor disappears when I open the app grid.  It doesn't happen in the main window.  I'm also including my settings window.  I tried adjusting the value but the problem persisted.

https://github.com/G-dH/vertical-workspaces/assets/58082491/8cff46b1-8e39-4098-85e0-f6408e94dd71

![Screenshot from 2024-07-11 01-17-16](https://github.com/G-dH/vertical-workspaces/assets/58082491/e6b184e7-3eb9-4c47-ad0b-ba26cbe2b62e)

**Comment by G-dH** [comment]
This is a bug. The blur effect should stay on the "window picker" level on the secondary monitor. Can you open a new issue for this one?
