### ISSUE TITLE
[BUG] Overview - delete icon disappears if mouse cursor is above window

### ISSUE THREAD

**Issue by litemotiv** [G-dH/vertical-workspaces#188]
When opening the overview, if the mouse cursor is above a certain window, the delete icon will immediately disappear. The icon can then only be restored by moving the cursor outside of the window and re-entering it. 

Expected behaviour is that the delete icons stays visible regardless of whether the mouse cursor is above the window.

Version: 46.3.1 / 65

Demonstration:

[Screencast from 2024-08-18 13-20-08.webm](https://github.com/user-attachments/assets/980de780-eb0e-46b0-a4f9-5edc6adc8050)

**Comment by G-dH** [comment]
Are you able to reproduce this issue with V-Shell disabled?

**Comment by litemotiv** [comment]
> Are you able to reproduce this issue with V-Shell disabled?

Good call, it appears this also happens with V-Shell disabled. Perhaps that makes it a Gnome-Shell issue instead?
