### ISSUE TITLE
Search Results Width options are ignored until the extension is reloaded. Eventually, it ignores it again

### ISSUE THREAD

**Issue by mits-haruko** [G-dH/vertical-workspaces#189]
I would like the file search results to be displayed as a long list with all the results, instead of a single line and the "Files N more" text beside it. I can configure this by increasing the width under the Search Results Width option (I currently have it at 110). However, this option doesn't do anything until I manually reload the extension (i.e., turn it on and off on Extension Manager). Moreover, after a while like when resuming from sleep, rebooting or reloading the session, the search results will not appear as a long list anymore **although the width is still set as 110 in the extension's menu**.   Search results will still appear, but as mentioned before, under the "N more" option, instead as in a long list. Turning the extension on and off as before makes it work as intended again.

Currently observed under the latest version of Gnome (shell version 46.4) on Fedora 40, V-Shell 46.3.1/65 installed via Extension Manager.  I don't have many hardcore customization made to the extension's default: I mostly changed the workspace view to vertical, otherwise using all Defaults when coming to the Overview tab. Not using any other extension that might affect the behavior of search or overview, either.

**Comment by G-dH** [comment]
The 'Search results width' option should not affect the number of rows displayed by search providers. There's the 'Max search results rows' option in the Appearance tab to control this. The maximum number of results is 50.

**Comment by mits-haruko** [comment]
Oh, thank you. This might be the right setting to increase the number of search result rows, but still, after something as simple as locking the screen due to inactivity, the setting gets ignored anyway and I still have to toggle the extension to make it "remember" the setting.

**Comment by G-dH** [comment]
I’m unable to reproduce this behavior on my systems. Just to be sure, could you please disable all other extensions, restart Gnome and try to reproduce the issue?

**Comment by mits-haruko** [comment]
Yeah, after tweaking with extensions a bit more, I found out that Just Perfection is somehow causing the issue, even though I only use it to remove a specific icon on the panel. But probably not a bug with this extension, though, just some weird interaction :(.

**Comment by G-dH** [comment]
You should report this to JustPerfection, as that extension shouldn’t affect the number of search results when set to the default.

**Comment by mits-haruko** [comment]
Actually Just Perfection also has a number of search results option hidden among its many options. Probably overrides the one from this extension. I'm going to close this issue since it's not a bug after all. 

Thanks for your time :).
