### ISSUE TITLE
[BUG] Startup State option stopped working

### ISSUE THREAD

**Issue by sanse-temerario** [G-dH/vertical-workspaces#190]
**Describe the bug**
I have the option behavior -> startup state set to "Desktop", but when the session starts I have what I think is the default Gnome behaviour (the workspace overview on the secondary monitor, a blurry screen on the primary). If I close and reopen the overview I get the expected behaviour (workspaces on both monitors, visible dash).
In the past the option used to work: on startup I could notice a flash when gnome tried to directly open the overview, then the extension came into play and was able to switch to the desktop as expected. I supposed something has changed with a gnome update

**Basic debug information**
I tried disabling all extensions but v-shell, but nothing changed

**To Reproduce**
1. Go to tab "behavior"
2. Set the option "Startup State" to "Desktop"
3. Terminate session
4. Log in
5. Desktop is not shown

**Expected behavior**
I expect the desktop to be shown instead of the overview

**Screenshots**
This is what I see at startup:
![Schermata del 2024-08-17 10-27-22](https://github.com/user-attachments/assets/45e5e78f-9b57-4c3f-9848-12005c0928d2)

This is the overview after v-shell kicks in:
![Schermata del 2024-08-20 09-10-38](https://github.com/user-attachments/assets/66320d9c-b0ac-4e1d-bd4f-79dd4572be34)

**System:**
 - OS: Arch
 - Gnome shell version: 46.4
 - Version of V-Shell extension: 46.3.1
 - Source of installation: extension.gnome.org
 - Other installed and enabled extensions: "AppIndicator and KStatusNotifierItem Support", "Removable Drive Menu"

**System log output**
Since the problen happens on session start I wasn't able to capture relevant logs. Anyway, there are no stacktraces in the journal. I can attach standard log, if they can help.

**Comment by G-dH** [comment]
Have you tried reproducing the issue with a single monitor?

**Comment by sanse-temerario** [comment]
I tried this morning, but the result is the same. I get Gnome overview at startup instead of desktop
![Schermata del 2024-08-27 09-07-39](https://github.com/user-attachments/assets/b8327d38-1d31-427f-afcb-47817666a847)

**Comment by sanse-temerario** [comment]
I just updated to 47.0 and it's working again, thank you
I'm closing this issue

**Comment by G-dH** [comment]
Thanks for the feedback!
