### ISSUE TITLE
[FEATURE] Add option to sort folders in app grid inline with apps 

### ISSUE THREAD

**Issue by bradthornborrow** [G-dH/vertical-workspaces#191]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
As noted in subject, add option to alpha sort app grid with folders sorted inline, rather than at start or end.

**Describe alternatives you've considered**
None, currently manually sorting app list, or resetting in gsettings to force resort from time-to-time.

**Comment by G-dH** [comment]
OK, I'll add this option.

**Comment by bradthornborrow** [comment]
Wow, thanks!.

**Comment by G-dH** [comment]
Added to the `main` branch. I would appreciate it if you could test the latest version from the repository.

**Comment by G-dH** [comment]
Sorry, my bad, I forgot to add `prefs.js` to the commit. I will upload it when I get home today.

[Installation instructions](https://github.com/G-dH/vertical-workspaces?tab=readme-ov-file#installation-from-github-repository)

**Comment by G-dH** [comment]
Done.

**Comment by bradthornborrow** [comment]
Confirmed and tested.  Works great! Thanks for the quick response.

**Comment by G-dH** [comment]
Thanks! In addition, the app grid now allows drag-and-drop between folders and adds an option to filter app grid icons when you start typing, instead of showing the default search view. Any bug reports are greatly appreciated.
