### ISSUE TITLE
GNOME 47 support - Testing needed

### ISSUE THREAD

**Issue by G-dH** [G-dH/vertical-workspaces#192]
Hello to all V-Shell fans! I would appreciate it if you could test the latest V-Shell from the main branch on GNOME 47 beta and report back with your experience and any issues. Thanks!

**Comment by JE-Amouel** [comment]
:+1:

**Comment by romgrk** [comment]
Was there recent changes on this? I've just updated and the extension doesn't work anymore, the overview mode shows like this:

![image](https://github.com/user-attachments/assets/0ce2d0bd-ccf0-4e5a-94ed-8c7b87bba00f)

**Comment by G-dH** [comment]
@romgrk Changes since when? Have you tried disabling other extensions?

**Comment by romgrk** [comment]
No but I barely have any extension. I've rolled back to gnome 46 for the time being, arch updated to 47.

**Comment by G-dH** [comment]
@romgrk You can open a new issue, but I need all requested info.
