### ISSUE TITLE
[BUG] Cannot open folders from the AppGrid after the Gnome 47 update

### ISSUE THREAD

**Issue by italoghost** [G-dH/vertical-workspaces#195]
**Describe the bug**
I cannot open folders from the AppGrid after the Gnome 47 update. I tried using the latest git, but it didn't work either. 

**Basic debug information**
 - Did disabling all other extensions help? No. I have disabled all other extensions, but it didn't work.
 - Did you find conflicting extension? No.

**To Reproduce**
1. Go to AppGrid
2. Click on a folder.
3. It won't open.

**Expected behavior**
The folders should open when I click on them.

**Screenshots**
N/A.

**System:**
 - OS: Arch Linux, with the Gnome 47 update.
 - Version of V-Shell extension: Latest git, probably 67.
 - Source of installation: GitHub.
 - Other installed and enabled extensions: Extension List, Freon, Quick Setting Tweaker, AppIndicator and KStatusNotifieritem Support, Pop Shell.

**System log output**
open terminal, execute:
`journalctl /usr/bin/{gjs,gnome-shell} -fo cat`
reproduce the bug, copy the output from terminal if any.

```
clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
JS ERROR: TypeError: this._removePopdownTimeout() is undefined
after__init@file:///home/ghost/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/appDisplay.js:1372:38
overrideProto/proto[actualSymbol]@file:///home/ghost/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/util.js:90:29
AppFolderDialog@resource:///org/gnome/shell/ui/appDisplay.js:2493:4
_ensureFolderDialog@resource:///org/gnome/shell/ui/appDisplay.js:2466:28
open/<@file:///home/ghost/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/appDisplay.js:1103:18
@resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by G-dH** [comment]
Thanks, typo. Can you please test the latest update from this repository?

**Comment by italoghost** [comment]
Hi! It now open but it does not show the icons!

![image](https://github.com/user-attachments/assets/8460a787-7844-4b7a-878f-706401cd8dc5)

Another thing is that the AppGrid seems to be misaligned to the bottom of the screen:

![image](https://github.com/user-attachments/assets/7fde0f95-6494-4c79-953c-bc9842deef75)

**Comment by italoghost** [comment]
Log:

```
Can't update stage views actor unnamed [StWidget] is on because it needs an allocation.
Can't update stage views actor unnamed [Gjs_ui_iconGrid_BaseIcon] is on because it needs an allocation.
Can't update stage views actor unnamed [StBoxLayout] is on because it needs an allocation.
Can't update stage views actor unnamed [StBin] is on because it needs an allocation.
Can't update stage views actor unnamed [StIcon] is on because it needs an allocation.
Can't update stage views actor unnamed [ClutterActor] is on because it needs an allocation.
Can't update stage views actor unnamed [StLabel] is on because it needs an allocation.
Can't update stage views actor unnamed [ClutterText] is on because it needs an allocation.
Can't update stage views actor unnamed [Gjs_ui_appDisplay_AppIcon] is on because it needs an allocation.
```

**Comment by italoghost** [comment]
Ops, changing the icon size to 128 seems to have resolved the issue (it was set to Adaptive before).

**Comment by italoghost** [comment]
Regarding the AppGrid being misaligned to the bottom of the screen, it was the height scale. I adjusted that and it is now ok!

**Comment by G-dH** [comment]
Thanks. There is still some problem with folders in 47, I must have missed something in the GS commits...

**Comment by KSTRTK** [comment]
Hello, I'm experiencing something I believe is related, the v-shell seems to be only supported on gnome 46, and not 47.. is there an expectation to have it supported on 47? Thanks in advance!

**Comment by G-dH** [comment]
@KSTRTK How did you get it to work?

I wasn't able to reproduce this issue today on Fedora.

**Comment by KSTRTK** [comment]
@G-dH I went to add/remove software (after installing pamac) and searched for this extension. After installing it, it worked just fine for me. I think it maybe something related to syncing via git? Attached is a screenshot:
![image](https://github.com/user-attachments/assets/4118d684-71e3-4737-a1c3-5e45b402d384)

**Comment by G-dH** [comment]
@KSTRTK The AUR package has its own maintainer, and I am not sure how it gets updated. If you want to test the latest version, you need to install V-Shell directly from this repository. [Instructions are in the README](https://github.com/G-dH/vertical-workspaces?tab=readme-ov-file#installation-from-github-repository).

**Comment by italoghost** [comment]
> Thanks. There is still some problem with folders in 47, I must have missed something in the GS commits...

Hi, @G-dH! Everytime I start a new session, my folders doesn't show the icons, as I have mentioned above. The workaround that I have found (and that is why I thought that I had solved the issue) is to change the icon size from one valor to another.

**Comment by G-dH** [comment]
The folder issue after login should be resolved now. Please try the latest update and let me know if it works for you.

**Comment by italoghost** [comment]
It is working! Thanks, @G-dH!

**Comment by G-dH** [comment]
Thanks for your help. Sending it to ego.
