### ISSUE TITLE
[BUG] No default profile option

### ISSUE THREAD

**Issue by r0ckarong** [G-dH/vertical-workspaces#197]
Sorry if this is the wrong place to ask but I can not find any other communications channel about this extension other than the comments on gnome.org and I don't think that's the right place either.

How do I set "my" profile to load on login? 

I've modified the first profile of the four default slots to work like I want. I've given it a new name. Every time I log into my machine the settings are reverted to the previous settings and I have to open up the Extensions app, open the Settings and click on the reload button to load the actual profile preferences. I can't find a setting for "make this default" or "load this profile on launch".

I want to customize a profile and then set it so V-Shell loads it every time I login to my GNOME session. What am I doing wrong here?

**Comment by G-dH** [comment]
V-Shell always uses the current configuration and does not load any profile at startup.

**Comment by G-dH** [comment]
That's not related to the profile, but it seems like something is overriding the V-Shell code. Check the built-in extensions (disable all related to dash).
