### ISSUE TITLE
(Shift + ) Super + Page Up/Down keys don't work

### ISSUE THREAD

**Issue by sr258** [G-dH/vertical-workspaces#2]
When enabling the extension the "Super + Page Up" and "Super + Page Down" to switch to the previous / next workspace don't work anymore. The same is true for moving a window to a different workspace with "Super + Shift + Page Up / Down". It would be great if these hotkeys still worked.

**Comment by sr258** [comment]
@G-dH Thank your for pointing to the fix. It would still be great from a usability perspective, if this could be somehow done automatically or from the extension settings.

**Comment by G-dH** [comment]
I added the option to the Adjustments page. Enabling this option will automatically remove / add  Page shortcuts based on the current workspace orientation and updates the shortcuts every time the extension is enabled or disabled. If you only use the Vertical Workspaces, you can immediately disable the option to save resources during screen lock / unlock.
