### ISSUE TITLE
upgrade broken on Ubuntu 22.04 / Gnome 42

### ISSUE THREAD

**Issue by donpdonp** [G-dH/vertical-workspaces#20]
Gnome warned me that Vertical Workspaces needed an update. I opened the web page, pushed upgrade, and the gear-icon for upgrade was replaced with a big red button 'ERROR'. I use gnome-shell  42.2-0ubuntu0.2 on Ubuntu 22.04.

**Comment by G-dH** [comment]
GNOME informed you that the extension "will be upgraded on next login". There is no need to update the extension manually, in any case the GNOME Shell needs to be restarted.

**Comment by donpdonp** [comment]
I went to upgrade the extension after logging in multiple times, each time being alerted that the extension needs to be upgraded. In fact thats the only reason I went to upgrade it, to stop the warning from showing up each time I logged in. I also tried removing the extension and adding it again - that too resulting in an ERROR button on extensions.gnome.org

**Comment by G-dH** [comment]
I have not encountered such a problem on my Ubuntu installations. Try to install the extension directly from the source:

    git clone https://github.com/G-dH/vertical-workspaces.git
    cd vertical-workspaces/
    make install

**Comment by G-dH** [comment]
Any news?

**Comment by donpdonp** [comment]
I installed from source...and its working fine now!

**Comment by G-dH** [comment]
Looks like a problem with your extensions subsystem..
