### ISSUE TITLE
[BUG] super key + page up and page down do not work for vertical workspace

### ISSUE THREAD

**Issue by SaurabhGurde** [G-dH/vertical-workspaces#204]
**Describe the bug**
While using horizontal workspace super key + pageup work properly for switching workspaces but it do not work for vertical  workspace.
**Basic debug information**
 - Did disabling all other extensions help?
 - Did you find conflicting extension?

**To Reproduce**
use default vertical workspace and try to use super key + pageup 

**Expected behavior**
super key + pageup or pagedown should work for both vertical and horizoltal workspace.

**System:**
 - OS: Ubuntu 24
 - Version of V-Shell extension: 47
 - Source of installation: gnome extension manager 
 - Other installed and enabled extensions: Dash to panel, coverflow alt tab, wallpaper slideshow, vitals, add to desktop.

**Comment by G-dH** [comment]
`Settings` > `Misc` > `Keyboard` > `Override Page Up/Down Shortcuts`
?

**Comment by SaurabhGurde** [comment]
Huh! i did not see that well its working
