### ISSUE TITLE
[BUG] missing tag for version 47.1

### ISSUE THREAD

**Issue by carlwgeorge** [G-dH/vertical-workspaces#206]
**Describe the bug**
Version 47.1 is available on https://extensions.gnome.org, but there is no corresponding tag here in this repo.  Distros such as Fedora usually use this tag for creating native system packages.

**To Reproduce**
1. Observe version 47.1 in https://extensions.gnome.org/extension/5177/vertical-workspaces/
2. Observe the lack of version 47.1 in https://github.com/G-dH/vertical-workspaces/tags

**Expected behavior**
Tag 3ef988512be37ff7d7a196655f70425aecfb9231 as `v47.1`.

**Comment by carlwgeorge** [comment]
See also #14.

**Comment by G-dH** [comment]
Thanks for the reminder.
