### ISSUE TITLE
[feature-request] toggle/switch to show search bar

### ISSUE THREAD

**Issue by Muqtxdir** [G-dH/vertical-workspaces#25]
hi,

I know that even without search-bar being present it is still possible to search just by simply typing. However search-bar visually being absent in both overview and app-grid makes me think that search functionality is absent or hidden due to enabling this extension

if it's possible please present the option in the preferences to toggle the search-bar's visibility.

**Comment by G-dH** [comment]
Hi,
I'm sorry, the search entry is just a waste of space for me, so adding it to the layout would also be a waste of time for me.

**Comment by Muqtxdir** [comment]
no problem, I personally like having it visible all the time but I understand and agree with your reasoning as well. 

at the moment I've commented out `Main.overview.searchEntry.visible = false;` (_line 159 in verticalWorkspaces.js_) and it seems to be hit or miss and when it's visible the margin/space between searchbar and the current workspace is bit low. how may I resolve this?

#### screenshot showing less space/margin between search and current workspace:
![Screenshot from 2022-10-04 00-06-45](https://user-images.githubusercontent.com/54065734/193653233-20a54a4e-03cc-45a3-af4e-9c1f1ac900f0.png)

**Comment by G-dH** [comment]
The truth is that the vertical dash/dock also wastes space in this case, so the entry can fill the empty space. Try the latest github version of the extension, I've added the option.

**Comment by Muqtxdir** [comment]
thanks! for adding an option for searchEntry. tried it out from master branch, it works well
