### ISSUE TITLE
[feature-request] Static background image option

### ISSUE THREAD

**Issue by benscruton** [G-dH/vertical-workspaces#27]
When in the overview, the background (for me at least) becomes a solid dark gray screen.  I'd love an option to keep a full-size wallpaper as the background image for the overview screen as well.

Totally just an aesthetic preference though, so of course no worries if this would be difficult to do

**Comment by G-dH** [comment]
It's not difficult, but the "Blur My Shell" extension does a great job in this regard so I'm not motivated to implement it in VW.

**Comment by G-dH** [comment]
Option `Show Static Background` has been added, including blur adjustment scale.
