### ISSUE TITLE
Feature request: Default workspace thumbnails position

### ISSUE THREAD

**Issue by CleoMenezesJr** [G-dH/vertical-workspaces#29]
Would it be possible to implement an option to keep the workspace thumbnails in their original position as well as I can have the Dash in its position by default?

**Comment by G-dH** [comment]
I'm sorry, that doesn't make sense for this extension.
If you want default overview and just switch the orientation of workspace switcher, you can try my other extension [Workspace Switcher Manager](https://extensions.gnome.org/extension/4788/workspace-switcher-manager/) that offers `Reverse Workspace Orientation` option.

**Comment by CleoMenezesJr** [comment]
Thanks, that's exactly what I'm looking for.
