### ISSUE TITLE
Version 21 blocks some keyboard/mouse input if dash position is disable

### ISSUE THREAD

**Issue by Pinetrax** [G-dH/vertical-workspaces#33]
Since version 21 when setting the option `Dash Position` to `Disable`, the extension screws up the desktop massively after an initial login. Changing the option or activating the extension after logging in does not yield this behavior, it works fine in that case.

### Steps to reproduce
* set `Dash Position` to `Disable`
* log out
* log back in

### Observed behavior
* now only shows an overview with one workspace and no panel (on machine, VM shows panel), mouse interactions completely gone
* only search possible until launching the first app
* super key is not working, most interactions are not possible among keyboard shortcuts

### Tested on
* Fedora Silverblue 37
* fresh Fedora Silverblue 37 VM inside Boxes
* all settings of "Vertical Workspaces" extension reset (doesn't actually matter)
* all other extensions disabled (doesn't actually to matter)
* demo video: https://youtu.be/VyM_ufrppZA

**Comment by G-dH** [comment]
Sorry, I was forced by EGO reviewer to add unnecessary code and I also added the error :D
