### ISSUE TITLE
overview ws scroll animation 

### ISSUE THREAD

**Issue by allaeddineomc** [G-dH/vertical-workspaces#35]
the workspace switching animation in the overview is beautiful as is but i think it will be very cool to have the option for an alternative animation where the app windows move to the workspace preview (like when showing the app grid) as the user scrolls away from the workspace while the windows from the next workspace move from the preview to the center (like when hiding the app grid) .
also i guess it will make it look much better for both the proposed animation and the show/hide app grid animation to make the preview for the current workspace empty .

**Comment by G-dH** [comment]
It's more complicated than it looks, to do this. On the other hand, what I did with the app grid transition animation is actually incredibly simple ;) The workspace preview (the big one, not ws thumbnails) is actually in one strip with all other workspaces, as you can see in the original app grid view, the only difference is that inactive previews are hidden during the app grid transition and the whole strip with workspaces scales down to the size of the ws thumbnails box and moves over it.

**Comment by allaeddineomc** [comment]
i got it , i think the animation can be made way simpler by making the windows from the next workspace appear after hiding the current workspace windows ends , this way it can still be done using the same hack

**Comment by G-dH** [comment]
Sure, but it's still more complicated than it looks and you have to do two animations in the same amount of time, so visually it wouldn't be better than the default animation.
