### ISSUE TITLE
Custom keyboard shortcut for switching workspaces?

### ISSUE THREAD

**Issue by Jodom988** [G-dH/vertical-workspaces#36]
This extension is awesome. Works flawlessly and easy to install. 

An enchancement suggestion is to customize shortcuts for switching between workspaces. Right now we're stuck with using (shift +) super + page up/down to move between worksapces and move windows between workspaces.

**Comment by G-dH** [comment]
Thanks for the feedback, you can set your keyboard shortcuts in GNOME Settings.

**Comment by Jodom988** [comment]
Ah I see. I didn't realize 'left' corresponded to 'up' and 'right' to 'down'. Thank you!

**Comment by G-dH** [comment]
I'm sorry, you're right there's only left/right. Use `dconf-editor`, to set up/down shortcuts. I only implemented automatic swap of `Super+Page`, since Ctrl+Alt+Arrows for switching ws works without any customization.

    /org/gnome/desktop/wm/keybindings
