### ISSUE TITLE
Dash and ws preview animation when double pressing super button

### ISSUE THREAD

**Issue by RocketRide9** [G-dH/vertical-workspaces#38]
When you double press super button dash and ws thumbnails moves back a little during animation.
https://user-images.githubusercontent.com/70429241/212543383-5219853f-a2ed-477c-8e26-1e754c8448e7.mp4

**Comment by G-dH** [comment]
Use _Super+A_ instead ;)

**Comment by VBBr** [comment]
I can live comfortably without double super and app grid (i use search in overview instead), but this little animation fault ruins a bit the feel of polishness

**Comment by G-dH** [comment]
I agree, I hate these little glitches too. Thanks for the report, I don't use the shortcut, so didn't notice.
