### ISSUE TITLE
Secondary Monitor Workspace preview appears bigger because there is no top bar

### ISSUE THREAD

**Issue by SamuelBorn** [G-dH/vertical-workspaces#40]
I have the dash on the left of my primary monitor.
The workspace preview is both left/right of the monitors to see every workspace with one glance.
But because the second monitor has no top bar (for the activities button, clock, quick settings, ...) it appears bigger.

![image](https://user-images.githubusercontent.com/58636569/213240395-94932283-e71a-4a80-966b-d2899565a474.png)

**Could you maybe add an option to make them the same size, so also the workspace previews will be aligned?**

**Comment by G-dH** [comment]
I added some options for the secondary monitors (now in the separate section at the end of the layout page), let me know if it helped.

**Comment by SamuelBorn** [comment]
Thank you! I will test it as soon your update hits the extensions store.
Currently, I don't have much time “compiling”/testing the source.

**Comment by G-dH** [comment]
I would appreciate it if you could test the features before I release it, my monitors are different sizes and resolutions and I added this just for you. It takes a few seconds to install from source.

**Comment by SamuelBorn** [comment]
Okay :D I did it.

This was the best way I could get it to work.

![image](https://user-images.githubusercontent.com/58636569/221912934-5046da23-96b2-499e-8bd6-cd383108ae52.png)

It required some fiddling around, but the results are quite promising.

The workspace thumbnails are dead center and almost the same size (optimal value is between two integers)

The workspace preview I could not get quite centered or the same height, even with the shift option.

But still, this is a big improvement over the last version!

**Comment by G-dH** [comment]
Thanks. Another option would be adding fake panel that will reduce the work area..

**Comment by G-dH** [comment]
Now it should be better ;)

**Comment by SamuelBorn** [comment]
![image](https://user-images.githubusercontent.com/58636569/222200067-ab694305-ab71-454d-8647-6d5f37e60ffb.png)

yay! now its 99% perfect :) thank you!

**Comment by SamuelBorn** [comment]
I am closing this :)
