### ISSUE TITLE
Workspace indicator

### ISSUE THREAD

**Issue by Susensio** [G-dH/vertical-workspaces#42]
I would be nice if a workspace indicator could be shown in panel.
I used to have an extension, [Workspace Indicator](https://gitlab.gnome.org/GNOME/gnome-shell-extensions), that shows a preview as this image:
![Screenshot from 2023-01-25 09-32-36](https://user-images.githubusercontent.com/11474625/214517277-aab2ab2d-8eb3-4f15-8e46-be769b9e7383.png)
It's like a small minimap of workspaces, very convenient.

---------
But with Vertical Workspaces enabled, the indicator became this:
![Screenshot from 2023-01-25 09-18-54](https://user-images.githubusercontent.com/11474625/214517256-990ec004-35e9-41dc-b622-83443015f346.png)
Just a number, not even a box around it to make it feel more _workspacy_.

I know this is the result of two extensions colliding, and neither could be blamed for this behaviour, but It would be nice if Vertical Workspaces could show a proper indicator on his own.

**Comment by G-dH** [comment]
Just replace this line: https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/blob/main/extensions/workspace-indicator/extension.js#L335
with this:

    const vertical = false;

You can also ask the author of the extension to add an option to choose between list and thumbnails.

**Comment by Susensio** [comment]
Thanks! That was fast and easy!
It works perfectly.
However, how does this work? Why was it working fine with horizontal workspaces?
Maybe the thumbnails were coming from a different extension?

**Comment by G-dH** [comment]
The line is testing workspaces orientation and in case it's vertical, you get the original list indicator, like in GNOME 3.xx.  The author added thumbnails for GS 40+. The line just skip the test and always return false as for horizontal orientation.
