### ISSUE TITLE
Activating extension disables super-pgup/pgdn keys

### ISSUE THREAD

**Issue by Halfwalker** [G-dH/vertical-workspaces#45]
This is on a clean install of Ubuntu 22.04, and installing `ubuntu-desktop`, using either Wayland or Xorg, Gnome 42.5.0.  Installed into virtualbox VM via debootstrap from ubuntu-22.04.1-live-server ISO, then `apt install ubuntu-desktop`

The extension is installed with `gnome-shell-extension-manager` but not activated.  At this point all workspace switching functions as expected per defaults : super-pgup/pgdn, super-mousewheel.  Once the extension is activated though, the key switching now does nothing.  super-mousewheel works fine though.

Modifying the keybinding (Settings -> Keyboard -> View and customize shortcuts -> Navigation -> Move to workspace on left) doesn't change things.  Disabling the extension restores key switching

**Comment by G-dH** [comment]
VW Settings > Misc > Keyboard. You can also use Ctrl+Alt Arrow Up/Down.
Workspaces in GNOME Shell 40+ are stacked horizontally, so the keyboard shortcuts are assigned to left/right switching and therefore don't switch up/down. VW won't touch your shortcuts unless you say so.

**Comment by Halfwalker** [comment]
Hrm - I tried that and noticed it changed the `Move to workspace on the right` to `alt-super-right`, as well as the `Move window one workspace to the right` to `shift-alt-super-right` (and left ones).

Regardless, with that activated as `alt-super-right` or modified to my own preference like your as `ctl-alt-down` nothing happens with changing workspace view or moving windows :(

Must have something blocking it somewhere.

**Comment by G-dH** [comment]
VW just moves Super+(Shift)+PageUp/Down shortcuts between Move (window} to ws left/right and up/down. The Shell registers more than one shortcut to each action, so if VW removes the one, you can see the second one in GNOME Settings. Also, in the GNOME Settings you can only see left/right shortcuts. If you want to see/set all available shortcuts, open Dconf editor and find relevant keys in `/org/gnome/desktop/wm/keybindings/`.

**Comment by Halfwalker** [comment]
Ah, I see now.  Moving up/down works fine with `super-pgup/pgdn`

Pity `Settings -> Keyboard -> View and customize shortcuts -> Navigation` doesn't show the `switch-to-workspace-up/down` settings - have to modify manually to change to `ctl-alt-up/dn`

**Comment by G-dH** [comment]
That's how it is, GNOME officially doesn't support vertically stacked workspaces.
Have you tried the latest version from the repository? Not that it changes anything related to the shortcuts, but offers a lot more options than the last official release and fixes some bugs.

**Comment by Halfwalker** [comment]
No, not yet - will definitely check it out.  I have my ansible playbooks for setting up the workstation with schema overrides etc. so will be easy enough to incorporate.

Thanks for the teachings :)

**Comment by G-dH** [comment]
No problem, I want it perfect, so feel free to report bugs and glitches ;)
