### ISSUE TITLE
Extension causes gnome-shell to freeze and lag after resuming from suspend

### ISSUE THREAD

**Issue by VBBr** [G-dH/vertical-workspaces#46]
Most times after resuming from suspend gnome-shell freezes for some time. Also sometimes first `three finger swipe` after resume or long idle opens app grid instead of overview.
Video:

https://user-images.githubusercontent.com/70429241/218818162-83b89fc0-f477-4f4e-ad24-16db39515dcf.mp4

**Comment by G-dH** [comment]
This kind of freezing is usually related to updates of keybindings or updating the app indicators extension. If you're using vertical orientation of workspaces, try to disable 'Override Page Up/Down Shortcuts' option to avoid switching the shortcuts on every lock/unlock.

**Comment by VBBr** [comment]
`Override Page Up/Down Shortcuts` was already disabled. And after disabling app indicators extension (`appindicatorsupport@rgcjonas.gmail.com`) or VW I can't reproduce this issue.

**Comment by G-dH** [comment]
Try the latest version, I removed app grid realization. VW needs to replace part of the shell on lock/unlock and it's not for free.

**Comment by VBBr** [comment]
it helped. great job
