### ISSUE TITLE
I cant select workspaces and Windows arent appearing in Overview mode

### ISSUE THREAD

**Issue by i7sreact** [G-dH/vertical-workspaces#47]
Overview mode looks like its bugged, in the config of the extension, overview mode is set to default

https://youtu.be/7Jzl44wMlvI

I never made an issue before so sorry if this is shallow, with little explanation

And how can i get some log that you can see to find the problem?

**Comment by G-dH** [comment]
What other extensions you have enabled? Open terminal, execute:
`journalctl /usr/bin/{gjs,gnome-shell} -f`
open/close the overview and look if it show any errors. Paste the log here.
Try to disable all other extensions, test if it helps.

**Comment by i7sreact** [comment]
I disabled other extensions and looks like i found it what extension was causing this, it was just perfection

And here is the log

```
journalctl /usr/bin/{gjs,gnome-shell} -f

Hint: You are currently not seeing messages from other users and the system.
      Users in the 'systemd-journal' group can see all messages. Pass -q to
      turn off this notice.
fev 19 23:55:50 dnasc-suse-acer gnome-shell[2585]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
fev 19 23:55:50 dnasc-suse-acer gnome-shell[2585]: Can't update stage views actor <unnamed>[<StIcon>:0x56101546bf00] is on because it needs an allocation.
fev 19 23:55:50 dnasc-suse-acer gnome-shell[2585]: Can't update stage views actor <unnamed>[<ClutterActor>:0x561011a10ab0] is on because it needs an allocation.
fev 19 23:55:50 dnasc-suse-acer gnome-shell[2585]: Can't update stage views actor <unnamed>[<StIcon>:0x561011a0be90] is on because it needs an allocation.
fev 19 23:55:50 dnasc-suse-acer gnome-shell[2585]: Can't update stage views actor <unnamed>[<ClutterActor>:0x561011a11110] is on because it needs an allocation.
fev 19 23:55:50 dnasc-suse-acer gnome-shell[2585]: Can't update stage views actor <unnamed>[<StIcon>:0x5610119ffb60] is on because it needs an allocation.
fev 19 23:55:50 dnasc-suse-acer gnome-shell[2585]: Can't update stage views actor <unnamed>[<ClutterActor>:0x561011a10de0] is on because it needs an allocation.
fev 19 23:55:50 dnasc-suse-acer gnome-shell[2585]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
fev 19 23:55:50 dnasc-suse-acer gnome-shell[2585]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
fev 19 23:55:50 dnasc-suse-acer gnome-shell[2585]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
```

**Comment by G-dH** [comment]
Reset all JP options that may conflict with VW.

**Comment by i7sreact** [comment]
Ok, thank you

And one more thing before closing the issue

What i need to learn to make an gnome extension?

I use openSUSE here in my hybrid laptop and it has suse-prime for switching GPUs, but there isnt any extension, so im thinking to learn to make a extension to switch GPUs through the quick settings

**Comment by G-dH** [comment]
I won't help you with GPU switching, but the basics for developing extensions you can find here:
https://gjs.guide/
GNOME Shell's source code may be useful:
https://github.com/GNOME/gnome-shell/tree/main/js/
We also have an `Extensions` matrix chat room for extension developers:
https://matrix.to/#/#community:gnome.org

**Comment by i7sreact** [comment]
Thank you

**Comment by real-or-random** [comment]
For anyone else encountering this: For me, the "bad" setting in Just Perfection was "Visibility" ->"Search".
