### ISSUE TITLE
GNOME 44 support

### ISSUE THREAD

**Issue by carlwgeorge** [G-dH/vertical-workspaces#48]
I'm aware this extension doesn't yet advertise support for GNOME 44 in the metadata.json file, but when I saw that GNOME 44 beta was released I figured I'd give it a shot anyways to start the conversation about adding support.  I loaded up a Fedora 38 nightly image in a virtual machine, installed the [packaged extension](https://src.fedoraproject.org/rpms/gnome-shell-extension-vertical-workspaces) (version 23), and set `/org/gnome/shell/disable-extension-version-validation` to true to allow loading the extension.

![Screenshot from 2023-02-22 21-09-52](https://user-images.githubusercontent.com/12187228/220814218-ac358f66-610a-49a2-88b8-b5dc78d223a0.png)

The extension appears to load, but the workspace indicator is missing, and there are no animations.

**Comment by G-dH** [comment]
Try the latest version from the GitHub repository, works for me on Fedora Rawhide with 44.beta. No animations is usually a problem of virtualization, 3D never worked for me in Boxes, VirtualBox is better.
![Screenshot from 2023-02-23 11-29-12](https://user-images.githubusercontent.com/73719686/220882056-c55edb29-043f-4491-b67e-140502c56469.png)

**Comment by carlwgeorge** [comment]
Thanks for the pointer.  I've updated the Fedora package to a snapshot of commit 0a0e31475ea3516cdf5a4e588ad6530383a01320 and things work much better.  I also switched my testing from virt-manager to boxes and the animations are working as well.

**Comment by G-dH** [comment]
New release 26 is available, hopefully stable enough, conflicts with other extensions can be solved with the implemented module control that allows parts of the extension to be disabled.
