### ISSUE TITLE
There is no option to change workspace orientation

### ISSUE THREAD

**Issue by SyhanX** [G-dH/vertical-workspaces#49]
When looking at the screenshots of the settings page  in README.md, there seems to be an option to change the workspace orientation from vertical to horizontal and vice versa (as shown in the 1st screenshot). However, when I installed this extension and opened the settings, such option was completely absent (2nd screenshot). 

![Screenshot from 2023-02-24 16-32-00](https://user-images.githubusercontent.com/114600551/221144879-314b678e-7863-4f77-9684-49d2d21307c3.png)
![Screenshot from 2023-02-24 16-29-32](https://user-images.githubusercontent.com/114600551/221144929-96f40b00-154b-46c2-a811-a214207e5ee1.png)

**Comment by G-dH** [comment]
Version 24 has not been officially released yet, you can install the development version from this repository.
