### ISSUE TITLE
Breaks gestures on wayland (3 fingers swipe up to open overview)

### ISSUE THREAD

**Issue by mbousq** [G-dH/vertical-workspaces#5]
This extension looks great, many thanks !

However, when I enable it, I lose the 3 fingers swipe up to open overview (log-in and log-out does not help) on my notebook. Disabling the extension brings it back. No idea what could be the issue...

Config:
- Ubuntu 22.04, GNOME Shell 42.2
- installed through gnome extension website

If you need anything, please ask

**Comment by G-dH** [comment]
3 finger gestures should work: Up / Down switches workspaces, Left / Right enters / leaves overview / app grid.

**Comment by mbousq** [comment]
Right, I was on the last workspace when I enabled it... sorry about that :sweat_smile:
