### ISSUE TITLE
Edge case: If .cache is on different filesystem (eg btrfs subvolume), make install won't work

### ISSUE THREAD

**Issue by nadir-yttrium** [G-dH/vertical-workspaces#51]
Hey, 
first: thank you for your extension. Love it!

When I tried to install from a current commit, I got the error `Can't recursively copy directory` at the `make install` step.

I first thought the issue was somehow with the extension, but I found out it's [actually a Gnome issue.](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2821)

I have my .cache directory on a different subvolume to exclude it from btrfs snapshots. Kind of an edge case, but I thought you might want to add that to the readme so that people don't think it's the fault of your extension.

I installed it by just manually unzipping directly into `~/.local/share/gnome-shell/extensions` and it worked just fine.

Thanks again!

**Comment by G-dH** [comment]
Hey, thanks for the heads up! Glad you like V-Shell, feel free to report any bug you find.
