### ISSUE TITLE
Compatibility problems with Dash to Panel

### ISSUE THREAD

**Issue by notpeelz** [G-dH/vertical-workspaces#52]
Since the last update (v25), the panel breaks completely (disappears) when the extension is enabled alongside [Dash to Panel](https://github.com/home-sweet-gnome/dash-to-panel). Is there a way to disable the panel layout features, so to prevent it from interfering with Dash to Panel?

GNOME: 43.3
Distro: Arch
Vertical Workspaces: v25
Dash to Panel: v52

**Comment by G-dH** [comment]
If you leave the panel on defaults, it shouldn't be in such conflict, works for me. What is your DtP configuration?
There is however conflict with dash, but you can hide it manually..

**Comment by notpeelz** [comment]
https://user-images.githubusercontent.com/920910/222921694-d92cd506-22ee-4c2e-9e7e-972dba45c75c.mp4

Here's my exported Dash to Panel config: [dtp_config.txt](https://github.com/G-dH/vertical-workspaces/files/10889306/dtp_config.txt)

**Comment by G-dH** [comment]
Available soon:
![Screenshot from 2023-03-04 20-34-30](https://user-images.githubusercontent.com/73719686/222925424-d051d07f-8faa-44ab-9a0b-23a06ceb6fe7.png)

**Comment by notpeelz** [comment]
Great! I will downgrade to the previous release in the meantime.

**Comment by G-dH** [comment]
An update that allows to disable expendable modules is available in the repository.

**Comment by notpeelz** [comment]
Seems to work. Thanks a bunch!
