### ISSUE TITLE
update breakes but does not replace functionality of hide top bar

### ISSUE THREAD

**Issue by fnordmorph** [G-dH/vertical-workspaces#53]
as above. functionality of hide top bar would be completely replaced if there was an option to not show the top bar unless the cursor approaches top of screen.

**Comment by G-dH** [comment]
Thanks for the report. The option is on my to-do list, but also a control over the V-Shell's modules, so you'll be able to disable parts of the extension that you don't like or collide with other extensions that you like better. The module controller will be available soon, it's almost finished.

**Comment by fnordmorph** [comment]
cool! I'm sticking with v-shell over hide-top-bar for now. look forward to
updates.

**Comment by G-dH** [comment]
An update offering disabling expendable modules is available in the repository.

**Comment by G-dH** [comment]
The latest version has been released today, the panel module can be disabled. Did it help?

**Comment by fnordmorph** [comment]
functionality of hide top bar not (completely) restored. top bar pushes windows out of the way when it drops down, rather than coming down over them as it does when vshell is disabled.

**Comment by G-dH** [comment]
Did you disable the panel modul in the settings?

**Comment by fnordmorph** [comment]
Hadn't restarted. Did that and hide-to-bar seems to have gone back to its previous behavior (which recently broke, but I think that's on them -- bar has erratic flashing behavior with full screen browser windows). Hoping you implement something that looks like hide-top-bar in v-shell. Thanks for spending time on this.

**Comment by G-dH** [comment]
I had no problen with the top bar extension on GS 42.5 and V-Shell with disabled Panel module.
