### ISSUE TITLE
If "Show Workspaces Thumbnails Labels" is set to "Disable", no thumbnails are visible at all

### ISSUE THREAD

**Issue by abi278** [G-dH/vertical-workspaces#56]
![Screenshot from 2023-03-07 09-46-42](https://user-images.githubusercontent.com/121675121/223385346-ea76cf4d-2769-4026-a808-00ad19e2f97a.png)
![Screenshot from 2023-03-07 09-47-01](https://user-images.githubusercontent.com/121675121/223385362-99f40219-0103-4a10-8649-f99d3226e2c8.png)

**Comment by G-dH** [comment]
Feel free to reopen the issue if you find a reason, for now I'm closing it as related to the issue #57.
Bug reports appreciated, I've added a template that will help you with it.
