### ISSUE TITLE
Changing the "Overview Mode" setting froze everything

### ISSUE THREAD

**Issue by abi278** [G-dH/vertical-workspaces#57]
I ended up stuck in the overview, with nothing responding to mouse movements or clicks.

I uninstalled the extension as I can't figure out any useful way of either fixing this or debugging it.

**Comment by G-dH** [comment]
Disable all other extensions and try to find which of them are in conflict. I can't make it compatible with everything.

**Comment by G-dH** [comment]
Compare the style of your "bug report" and my answer ;) Thanks for the info.
