### ISSUE TITLE
Ubuntu-Style side dock

### ISSUE THREAD

**Issue by el-calavera** [G-dH/vertical-workspaces#59]
I always liked the Ubuntu side dock, which is a straight bar from top to bottom. The new V-Shell is awesome, but when used as a side dock, the edges are rounded, which looks weird in comparison.

It would be nice to have an option of styling the bar like in the vanilla Ubuntu Dock, i.e. a bar stretching the whole screen without ending in rounded edges before reaching the edge of the screen.

![image](https://user-images.githubusercontent.com/13186252/223996854-fb446ade-2537-4227-81bd-5fbce18500a1.png)

Thanks for considering!

**Comment by G-dH** [comment]
This is not the style provided by V-Shell where corners at the screen edge should not be rounded at all if dash is vertical. V-Shell also offers control over the corner radius in its settings window. I've seen it on other user screenshot, do you use a custom GNOME Shell theme?

**Comment by el-calavera** [comment]
Thanks for the feedback!

I did some more digging: I am not using a custom shell theme, but I am using Ubuntu which to my understanding brings its own Yaru theme. I tried to switch everything to GNOME defaults using Tweaks and user-theme extension, but that didn't change the edges.

When disabling the ubuntu-dock addon (which is needed to make the dock stay on screen), the dock changes appearance like you see here:
![Screenshot from 2023-03-09 12-34-22](https://user-images.githubusercontent.com/13186252/224013969-8074b8b4-d229-49f8-a375-6aec59563033.png)

That is for a "Dash Background Radius" default setting of 0. When I turn it to the maximum of 50, it looks like this:
![Screenshot from 2023-03-09 12-34-11](https://user-images.githubusercontent.com/13186252/224014059-227c9b79-ca44-4095-a63e-e016c8005372.png)

The permanent dock provided by ubuntu-dock does not seem to heed V-Shell's configuration options at all.

(Note: when doing this testing, I was logging out and in when trying every setting.)

I guess this boils down to some weird interaction between the ubuntu-dock and/or theme and V-Shell.

So I am still looking for a way to have the pretty "panel mode" with the dock extending to the screen edge like in ubuntu-dock, but with all the V-Shell configuration goodness :)

**Comment by G-dH** [comment]
> The new V-Shell is awesome, but when used as a side dock, the edges are rounded, which looks weird in comparison.

I thought you were talking about the built-in dash, not the Ubuntu Dock / Dash to Dock extension.
V-Shell is not touching the dock at all (just trying to survive..), but there seems to be a conflict in the stylesheet. I'll try to fix it.

**Comment by el-calavera** [comment]
> And of course I'll add what you want if it means you'll disable DtD :)

You mean like an option to have the dash/dock always on? Deal :D

**Comment by G-dH** [comment]
The truth is that DtD is conflicting with V-Shell because it's overriding the same core parts of the Shell repeatedly and affects layout allocations in the overview. So V-Shell must react on any such sabotage and keep the Shell usable.
