### ISSUE TITLE
Dock style reset on startup overview

### ISSUE THREAD

**Issue by matmicha** [G-dH/vertical-workspaces#6]
After startup, the style of the dock resets when I toggle overview mode on the main monitor (1st screenshot). 
The only solution I found was to toggle Vertical Overview off and on again (and the style stays normal after that).
The 2nd screenshot show the normal appearance of my dock, which isn't changed on my 2nd monitor. 
![image](https://user-images.githubusercontent.com/16545424/180252587-2acd7097-e10c-4577-82ad-d64d38e06d6a.png)
![image](https://user-images.githubusercontent.com/16545424/180252828-4a48de62-b923-47cb-8d20-468e0f1d1847.png)

**Comment by G-dH** [comment]
`Dash Background Opacity` option on `Adjustments` page in Settings window?

**Comment by matmicha** [comment]
that's not exactly the issue
in fact, the apps drawer shortcut isn't on the dash usually ...

it seems like Vertical Workspaces overrides the Dash to Dock style

**Comment by G-dH** [comment]
VW is not touching the dock at all and the only "stylish" action it does is the background opacity control.
There may be some allocation errors, I was just dealing with it today when I was testing Ubuntu Dock (Cosmic Dock is fine).
Please try the latest version of VW from this repository, it has option `Fix for Ubuntu Dock`, which should help overcome the mess the dock can do.

Additional information may also help me track down the problem:
1. distro, version
2. shell version
3. extensions in use
4. configuration of DtD

If problem persists, disable all other extensions (except VW and DtD), restart shell, test, watch log:
`journalctl /usr/bin/gnome-shell -fo cat`

**Comment by matmicha** [comment]
I won't have access to my PC during the next 2 weeks, but sure will test all this as soon as I get back from vacation.

all the information I recall are : 
- Distro : Manjaro Linux
- DE : GNOME 42.2
- WM : I use X11 but also tested Wayland, dunno if it may affect the outcome but I'll check it
- Shell : zsh

Also using this extension without issues on my professional laptop running on Fedora 36 (GNOME), but the issue may come from other extensions as they are not exactly the same on both systems. 

Sorry I don't recall more, I'll provide more informations asap (early in August).

**Comment by G-dH** [comment]
I did a quick test in virtual box and it seems that the Fix option is useful to keep VW consistent, but I can't test 2 monitor setup. I'll wait for your feedback.

**Comment by matmicha** [comment]
I'm back and I tested the issue. 
With the last update, the dock issue is fixed, but I now have a display problem at every startup (see below) 
![image](https://user-images.githubusercontent.com/16545424/184299527-ea360ae2-04ac-4f67-bd4d-dd99fb037e18.png)
The issue is easily fixable by toggling VW off/on. 

It eems like another issue, but I didn't take time to search in issues if it was already encountered (probably). I'll check this.

**Comment by G-dH** [comment]
Option _Misc > Compatibility > Fix for Dash to Dock_. I'll add DtD detection into VW to force enable the option when the dock is present.
