### ISSUE TITLE
My open windows and workspace background do not appear (V-Shell)

### ISSUE THREAD

**Issue by mevan11** [G-dH/vertical-workspaces#61]
Hi ,
I have a problem with the V-shell extension.
The workspace preview does not appear . When I click on the activities button, my open windows and workspace background do not appear. Only workspace switcher popup appear. I work with a laptop. What is weird is that when I connect a monitor, the workspace normally appears on the second monitor but not on the main one. How to solve this problem? I'm on Ubuntu 22.10

**Comment by G-dH** [comment]
Hi, the bug report template is here to save us both time. Please, look at it and add more info: https://github.com/G-dH/vertical-workspaces/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by G-dH** [comment]
Should I close it or will you add the debug info I'm asking for? ;)

**Comment by G-dH** [comment]
Closing, feel free to reopen if you decide to cooperate.
