### ISSUE TITLE
[FEATURE REQUEST] Launch new instance does not work with V-Shell enabled

### ISSUE THREAD

**Issue by andrewguertin** [G-dH/vertical-workspaces#63]
**Describe the bug**
The [Launch new instance](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/tree/main/extensions/launch-new-instance) extension makes it so when you click an app icon in the dash, a new instance of that app is launched (e.g. a new terminal opens, instead of switching to an existing terminal).

V-Shell overrides this behavior, making the Launch new instance extension not work.

As far as I can tell, V-Shell also does not re-implement the behavior itself. In Settings -> Behavior -> Dash -> App Icon - Click Behavior, neither of the options implement this behavior, and I did not find any other options that looked relevant.

**To Reproduce**
1. Install Launch new instance (possibly through the gnome-shell-extensions package from your distro)
2. Verify that clicking on an icon in the dash opens a new instance of that app
3. Install V-Shell
4. Click on an icon in the dash

**Expected behavior**
Expected that a new instance of the window would open

**System:**
 - OS: Gentoo
 - Version of V-Shell extension: 27
 - Source of installation: extensions.gnome.org
 - Other installed and enabled extensions: Launch new instance

**System log output**
None

**Other information**
Middle clicking on the icon does (still) launch a new instance with V-Shell enabled.

**Comment by G-dH** [comment]
Done.

**Comment by andrewguertin** [comment]
This is wonderful, thank you!

**Comment by G-dH** [comment]
No problem. If this option is enabled middle click activates the app instead of opening new window.
