### ISSUE TITLE
[BUG] Keyboard focus does not switch to newly launched application

### ISSUE THREAD

**Issue by robin-a-meade** [G-dH/vertical-workspaces#64]
**Describe the bug**
When an application is launched from _Activities Overview_, keyboard focus stays where it was prior. Keyboard focus should switch to the newly launched application.

**Basic debug information**
 - Did disabling all other extensions help?  No
 - Did you find conflicting extension? N/A

**To Reproduce**
1. Install Fedora Linux Workstation 38 Beta (has Gnome 44)
2. Clone this repo and install and enable this extension
3. Launch _Gnome Text Editor_. Type "hello" or something to verify that it has keyboard focus
4. Press the Super key to enter _Activities Overview_
5. Launch an application, such as _Gnome Terminal_ or _Gnome Calculator_. For example, type "Calculator" + ENTER to launch _Calculator_.
6. Type something on the keyboard. Notice that _Text Editor_ still has keyboard focus, not the application you launched.

**Expected behavior**
I expected the newly launched app to have keyboard focus, like what happens without this extension enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/1343270/230791550-18f6d775-8ffe-474a-a786-f27f9b08986d.png)

**System:**
 - OS: Fedora 38 beta (has Gnome 44)
 - Version of V-Shell extension: v28 plus all commits to main branch as of Apr 8, 2023
 - Source of installation: GitHub
 - Other installed and enabled extensions: No other extensions are enabled. Although not enabled, Fedora Linux Workstation has these extension packages installed by default:
     - gnome-shell-extension-apps-menu  
       https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/tree/main/extensions/apps-menu
     - gnome-shell-extension-launch-new-instance  
       https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/tree/main/extensions/launch-new-instance
     - gnome-shell-extension-places-menu  
       https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/tree/main/extensions/places-menu
     - gnome-shell-extension-window-list  
       https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/tree/main/extensions/window-list
     - gnome-shell-extension-background-logo  
       https://pagure.io/background-logo-extension

**System log output**
open terminal, execute:
`journalctl /usr/bin/{gjs,gnome-shell} -fo cat`
reproduce the bug, copy the output from terminal if any.

```
JS LOG: Characters Application started
Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _doProviderSearch@resource:///org/gnome/shell/ui/search.js:653:28
  _doSearch/<@resource:///org/gnome/shell/ui/search.js:680:18
  _doSearch@resource:///org/gnome/shell/ui/search.js:678:25
  _onSearchTimeout@resource:///org/gnome/shell/ui/search.js:690:14

Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _doProviderSearch@resource:///org/gnome/shell/ui/search.js:653:28
  _doSearch/<@resource:///org/gnome/shell/ui/search.js:680:18
  _doSearch@resource:///org/gnome/shell/ui/search.js:678:25
  _onSearchTimeout@resource:///org/gnome/shell/ui/search.js:690:14

Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _doProviderSearch@resource:///org/gnome/shell/ui/search.js:653:28
  _doSearch/<@resource:///org/gnome/shell/ui/search.js:680:18
  _doSearch@resource:///org/gnome/shell/ui/search.js:678:25
  _onSearchTimeout@resource:///org/gnome/shell/ui/search.js:690:14

Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _doProviderSearch@resource:///org/gnome/shell/ui/search.js:653:28
  _doSearch/<@resource:///org/gnome/shell/ui/search.js:680:18
  _doSearch@resource:///org/gnome/shell/ui/search.js:678:25
  _onSearchTimeout@resource:///org/gnome/shell/ui/search.js:690:14

Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _doProviderSearch@resource:///org/gnome/shell/ui/search.js:653:28
  _doSearch/<@resource:///org/gnome/shell/ui/search.js:680:18
  _doSearch@resource:///org/gnome/shell/ui/search.js:678:25
  _onSearchTimeout@resource:///org/gnome/shell/ui/search.js:690:14

meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
JS LOG: Characters Application exiting
```

**Comment by robin-a-meade** [comment]
When this extension is NOT enabled and I repeat the same steps, producing the expected result, the logs look different:

```
JS LOG: Characters Application exiting
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
JS LOG: Characters Application started
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
JS LOG: Characters Application exiting
```

**Comment by G-dH** [comment]
The log is not relevant to your issue (it's related to the search, I know about it), however, I'm not able to reproduce the issue on any of my systems, including Fedora 38 Wayland/X11.
Are you using different input keyboards?

**Comment by robin-a-meade** [comment]
I installed Fedora 38 Beta using a wired keyboard. After installation, I connected my Bluetooth keyboard. I still had the wired keyboard connected, but not actively used, when I made my initial report.

I've since tried turning off bluetooth and using the wired keyboard exclusively. I also tried disconnecting the wired keyboard and using the bluetooth keyboard exclusively. In both cases, I'm able to reproduce the problem.

I'll try the extension on a 2nd system I have and report back.

**Comment by G-dH** [comment]
What is your V-Shell setup? Can you reproduce the problem in any of the default profiles?

**Comment by robin-a-meade** [comment]
Regarding my V-Shell setup, I tested using a new linux account and, for testing purposes, I did not make any changes to the default V-Shell settings.

I do get an error report in ABRT that may be relevant:

https://retrace.fedoraproject.org/faf/reports/640785/

That error report seems to be related to focus, which is what I'm experiencing.

On my 2nd system, I could not reproduce the problem. 

I'll close this bug report, as it seems likely something specific to my Fedora 38 beta installation. I'll do a fresh install after Fedora 38 is released and test again then.

**Comment by G-dH** [comment]
@DanMan I can't reproduce it.
Wayland or X11?
What other windows are open? Does it happen with no other windows on a workspace?
Are you sure that it behaves differently from the default GS?

**Comment by DanMan** [comment]
How did you launch it? If I start typing "terminal" and press enter, the window comes up out of focus. It doesn't matter, if other windows are open.

This is on X11.  It doesn't happen, if I have the extension disabled. The window comes up in focus, ready to receive keyboard input.

**Comment by G-dH** [comment]
@DanMan Try disabling the *search* module on the *Misc* tab of the *Settings* window if that makes a difference.

I'm not sure how V-Shell could affect the window manager and I'm unable to reproduce the problem on any of my systems, so I have nothing to debug.

**Comment by DanMan** [comment]
I've just found out that changing the animation speed has an effect. If I turn it down to 1, the window receives focus as it should. If I increase it to around 40, the problem comes back. So maybe something's out of sync?

**Comment by robin-a-meade** [comment]
Thanks @DanMan . Setting the animation speed below 40 solves the issue for me too.

**Comment by DanMan** [comment]
Time to re-open this issue then? It's just a workaround after all, not a fix.

**Comment by G-dH** [comment]
Does disabling the Search module in the V-Shell settings change anything in this behavior?

**Comment by robin-a-meade** [comment]
Disabling
- **V-Shell settings > Behavior > Enable Window Search Provider** and 
- **V-Shell settings > Behavior > Enable Window Search Provider** 

had no effect on this behavior in my testing. 

---
I should mention that I have two computers running Fedora 38. I have the problem only on _one_ of the two systems. 

**System that exhibits the problem uses AMD graphics:**
```
$ inxi -G
Graphics:
  Device-1: AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Display: wayland server: X.Org v: 22.1.9 with: Xwayland v: 22.1.9
    compositor: gnome-shell v: 44.2 driver: dri: radeonsi gpu: amdgpu
    resolution: 1920x1200~60Hz
  API: OpenGL v: 4.6 Mesa 23.1.2 renderer: AMD Radeon Graphics (renoir LLVM
    16.0.5 DRM 3.52 6.3.8-200.fc38.x86_64)
```
**System that works uses Intel graphics:**
```
$ inxi -G
Graphics:
  Device-1: Intel Iris Pro Graphics 580
    driver: i915 v: kernel
  Display: wayland server: X.Org v: 22.1.9 with: Xwayland v: 22.1.9
    compositor: gnome-shell v: 44.2 driver: dri: iris gpu: i915
    resolution: 1920x1200~60Hz
  API: OpenGL v: 4.6 Mesa 23.1.2 renderer: Mesa Intel Iris Pro Graphics 580 
   (SKL GT4)
```

**Comment by G-dH** [comment]
V-Shell settings > Misc > V-Shell Modules > Search

**Comment by G-dH** [comment]
OK, looks like I've found a way to reproduce the bug in my Fedora installation. I'll let you know when I find out the cause.

**Comment by G-dH** [comment]
Please try the latest update and let me know haw it works.
I'm still not sure what makes the difference in behavior of V-Shell and the default Shell, but the root of this issue seems to be deeper in the window manager, as I was also able to reproduce the bug even without V-Shell in Arch with a Wayland session.

**Comment by robin-a-meade** [comment]
The latest update fixes the issue for me. Newly launched apps now consistently receive keyboard focus. I'm using default settings in my testing.

**Comment by G-dH** [comment]
@robin-a-meade Thank you very much for the coffees!
It's still just a workaround, I have to find a better fix.

**Comment by G-dH** [comment]
I've improved the code of the workaround and made it optional to avoid unnecessary collateral damages. Now it's available in *Settings* > *Misc* tab > *Workarounds*

**Comment by robin-a-meade** [comment]
@G-dH Thank you. The workaround in _Settings > Misc tab > Workarounds_ is working great for me.

**Comment by DanMan** [comment]
LGTM

**Comment by G-dH** [comment]
Btw, it's upstream bug: https://gitlab.gnome.org/GNOME/mutter/-/issues/2690
