### ISSUE TITLE
[FEATURE] Disable the small workspace previews in app grid

### ISSUE THREAD

**Issue by 343i** [G-dH/vertical-workspaces#68]
Hello,

Greetings, the extension provides the small window previews both in overview and app grid. could you please add a on/off switch to enable and disable the small workspace previews in app grid. 

Many thanks for the extension as well.

**Comment by G-dH** [comment]
You can control size of the workspace thumbnails separately for window picker and app grid. A size of 0 for the app grid means the same size as for the window picker view, but try setting the size to 1.

**Comment by 343i** [comment]
Thanks for the tip, but shouldn't zero represent no thumbnails?
Setting it to one is working for me but please change zero size because it confused me for a bit
