### ISSUE TITLE
Workspace Switcher Position And Max Height has no effect on primary monitor

### ISSUE THREAD

**Issue by sr258** [G-dH/vertical-workspaces#7]
Hi,

Since a recent release (I think v6), the workspace switcher is always on the top of the screen of my primary monitor and not where I selected it to be in the "Workspace Switcher Position" setting. The settings works fine on the secondary monitor.

Here's an example (left part of the screen is my primary monitor, right part the secondary monitor):
![2022-07-24_12-21](https://user-images.githubusercontent.com/15268740/180642837-ba267e7f-d3d1-48b0-8c0f-d5aeab53baf2.png)

**Comment by G-dH** [comment]
In v7 try to enable `Fix for Dash to Dock` option.

**Comment by sr258** [comment]
Excellent, this fixed the issue!
