### ISSUE TITLE
[BUG] Last version broke Ctrl-Enter to launch a new instance behavior

### ISSUE THREAD

**Issue by mordae** [G-dH/vertical-workspaces#70]
**Describe the bug**
Ctrl+Enter should launch a new instance of the application, not switch to a running one.

**Basic debug information**
 - Disabling this extension resolved the issued.

**To Reproduce**
1. Open Firefox.
2. Go to overview.
3. Type "firefox".
4. Press Ctrl+Enter with the Firefox icon highlighted.
5. No new window opened.

**Expected behavior**
- A new window should have opened.

**System:**
 - OS: Fedora 37
 - Version of V-Shell extension: 29
 - Source of installation: extensions.gnome.org

**Comment by G-dH** [comment]
Sorry, I noticed that, it should be fixed already. Try to install the
latest repository version.

**Comment by mordae** [comment]
Fixed.
