### ISSUE TITLE
[FEATURE]: add build faramework

### ISSUE THREAD

**Issue by kloczek** [G-dH/vertical-workspaces#71]
Like for example has https://github.com/gicmo/gamemode-extension/ which is meson based (which is Gnome standard).
It will allow easier build, maintaine (translations) and package.

**Comment by G-dH** [comment]
I'm not familiar with meson, what are its advantages over my makefile?

**Comment by kloczek** [comment]
> easier build, maintaine (translations) and package

As I wrote easier build, maintaine (translations) and package.

**Comment by G-dH** [comment]
Thank you, then I have better things to do.
