### ISSUE TITLE
CTRL+Enter in overview is no longer working

### ISSUE THREAD

**Issue by ppareit** [G-dH/vertical-workspaces#75]
Before this extension, I was able to start typing nautilus and then CTRL+ENTER would start a new nautilus, even when nautilus was already open. 

1. Go to WINDOW-KEY
2. Type the name of a yet running app (terminal/nautilus/...)
3. Press CTRL+ENTER

There should a new instance of the app be started.

 - OS: latest Fedora
 - Version of V-Shell extension: latest version from extensions.gnome.org
 - Source of installation: extension.gnome.org

**Comment by G-dH** [comment]
Fixed already, you can install the fixed V-Shell from the GitHub repository.

**Comment by ppareit** [comment]
That is great! Just as your extension.
