### ISSUE TITLE
[BUG] "Launch new instance" extension seems not to work with "vertical-workspaces" installed

### ISSUE THREAD

**Issue by CanWood** [G-dH/vertical-workspaces#78]
**Describe the bug**
Since installing "vertical-workspaces", my "Launch new instance" extension seems to not launch new instances.

**Basic debug information**
Yes, disabling the "vertical-workspaces" extension and starting an already open app with "Launch new instance" enabled does start new instances
 - Did you find conflicting extension?

**To Reproduce**
1. Have "Launch new instance" v 36 installed
2. Have "V-Shell (Vertical Workspaces)" 29 installed
3. Bring up your list of available applications with hot corners, windows button, whatever way you prefer
4. Select a application that you already have an open instance of
5. Notice that the open instance attains focus

**Expected behavior**
Previously, a new instance would start

**Screenshots**
N/A

**System:**
 - OS: Fedora 38
 - Version of V-Shell extension: 39
 - Source of installation: Originally installed with a git clone and then checkout of v28.  In an attenpt to resolve the issue, it has since been updated through the brave browser using https://extensions.gnome.org/local/, selecting the upgrade button next to the extension and re-logging ion to my Fedora session
 - Other installed and enabled extensions: 
   Frippery Move Clock 26
   GSConnect 55
   Launch new instance 36

**System log output**
With both extensions runing, the opening of an app that i already have an instance open, produces:
```
Can't update stage views actor <unnamed>[<StBin>:0x5625ca278b00] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBin>:0x5625c751a750] is on because it needs an allocation.
```

Thanks!

**Comment by G-dH** [comment]
Install V-Shell from GitHub, disable *Launch new instance* extension and set the `App Icon - Click Behavior` option on `Behavior Tab` of V-Shell Settings window to `Open New Window`.

**Comment by CanWood** [comment]
Love it.  Cheers!
