### ISSUE TITLE
Add option to display workspace number in Switcher

### ISSUE THREAD

**Issue by leogallego** [G-dH/vertical-workspaces#8]
When using the Workspace Switcher and trying to send a specific Window to a specific Workspace it would be useful to have some sort of visual indicator for which workspace it is in the Workspace Switcher. This could use the naming from the Workspace Indicator if defined as well (check [1], [2] for reference)

Attached screencap with rough example of 3 numbered workspaces, this could be made with transparency to be less disruptive.

![image](https://user-images.githubusercontent.com/993814/181357768-ec2e9e7f-250e-4f3c-b509-0c0d3d8b3e4c.png)

[1] https://extensions.gnome.org/extension/3851/workspaces-bar/
[2] https://extensions.gnome.org/extension/21/workspace-indicator/

**Comment by G-dH** [comment]
This one was on my to-do list. Now you can choose between `Index`, `Index + Workspace Name` and `Index + App Name`. I've also added `Show on Hover` option.
