### ISSUE TITLE
[BUG] Can't drag window to monitor left from the main display

### ISSUE THREAD

**Issue by M4rtinK** [G-dH/vertical-workspaces#82]
**Describe the bug**
I have a three monitor setup, like this:
1) portrait screen
2) landscape screen
3) landscape screen (laptop)

I have screen 2 set as the main screen in Gnome Shell.

Today (May 22) I have updated to the latest version of vertical-workspaces from Git and have noticed I no longer can drag windows to the monitor to the left (nr. 1) from my main monitor (nr. 2). I can drag windows just fine to the monitor to the right (nr. 3).

**Basic debug information**
 - Did disabling all other extensions help?
 - Did you find conflicting extension?

Right now vertical-workspaces is the only extension enabled. Disabling it fixes the issue - I can again drag windows from main screen to the left one. 

**To Reproduce**
1. open an application (lets say gnome terminal) on the main screen
2. try to drag the window to the left screen
3. window can't be dragged to the left screen & shell acts like left edge of the workspace has been reached and tries to expand the window (see screenshot)

**Expected behavior**
The window is moved to the left screen.

**Screenshots**
![vertical_workspaces_error](https://github.com/G-dH/vertical-workspaces/assets/829558/3e18709c-c858-40f3-a143-c463459f30ef)

**System:**
 - OS: Fedora 38
 - Version of V-Shell extension: db7d2d2549945055b12493ca5a322dbbe4986869 from git
 - Source of installation: GitHub
 - Other installed and enabled extensions: none

**System log output**
open terminal, execute:
`journalctl /usr/bin/{gjs,gnome-shell} -fo cat`
reproduce the bug, copy the output from terminal if any.

I got:

```
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea59669e0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaa266880] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea9412310] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea69e0a50] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaab2be40] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea9412310] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaa5df600] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea72e5c40] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaac2ae70] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaa5f8270] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea576a310] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea53a3ab0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea72e5c40] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea576a310] is on because it needs an allocation.
meta_wayland_buffer_process_damage: assertion 'buffer->resource' failed
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaa687000] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea8a02320] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaad2aa10] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaa687000] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaab25800] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea71a8fa0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea68bab00] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaa6f84a0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaa743d80] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaafd1d40] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaa74c4f0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eab03ab20] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea586fc80] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea5901350] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaa6f9480] is on because it needs an allocation.
JS LOG: Characters Application started
Can't update stage views actor <unnamed>[<ClutterActor>:0x557eaacb2e30] is on because it needs an allocation.
Received error from D-Bus search provider org.gnome.Photos.desktop during GetResultMetas: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: V cestě „/org/gnome/Photos/SearchProvider“ objekt neexistuje
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea54b1830] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x557ea7dd4a70] is on because it needs an allocation.
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
JS LOG: Characters Application exiting
```

**Comment by M4rtinK** [comment]
Looks like I can't actually even move the cursor to the monitor to the left of the main one.

**Comment by M4rtinK** [comment]
One more thing - tried to set screen number 3 (the right most one) as the main one - then both screens to the left of it became inaccessible.

**Comment by M4rtinK** [comment]
For the meantime I have downgraded to the packaged version in Fedora (gnome-shell-extension-vertical-workspaces) & it does not manifest the issue. Look like the package contains version 26.

**Comment by G-dH** [comment]
Thanks, I don't see anything relevant in the log and I can't reproduce the bug.
First, try to Reset All Options on the About tab in the Settings window of the latest V-Shell, restart GNOME Shell and try again.

**Comment by robymus** [comment]
Same things happens to me, here are my details:
- Main monitor is on the right, secondary on the left
- I set the layout to have dash position on the left
- I disable hot corner (even when enabled, mouse can't move to the next monitor, but then the dock shows when hitting the edge)
- Try to move from the main monitor on the right to the secondary on the left, the mouse is blocked at the left edge of the main monitor
- Moving the dock to the bottom enables mouse to move left again.

(all this in Fedora 38)

**Comment by G-dH** [comment]
@robymus Do you use a dock extension, or the default dash?

**Comment by robymus** [comment]
@G-dH I use the default dash.

**Comment by G-dH** [comment]
What is your *Hot Corner Position* in V-Shell Settings?

**Comment by robymus** [comment]
It is "Disable", but the mouse blocking happens at every setting - except that if I set to something else (like Overview), the dock shows and the action happens. With Disable, mouse just stops at the left edge.

**Comment by G-dH** [comment]
*Hot Corner Position* doesn't have *Disable* option.

**Comment by robymus** [comment]
My bad, didn't read it properly :) It was Follow Dash - Hot Edge, and switching to any other option fixes the issue and I can move the mouse to the left monitor. Thanks for the tip.

**Comment by G-dH** [comment]
Thanks for feedback, the fix is already in the repository.
