### ISSUE TITLE
Search doesn't work after disabling the extension when Dash to Dock is enabled

### ISSUE THREAD

**Issue by 343i** [G-dH/vertical-workspaces#84]
My setup has dozens of gnome-shell extensions and they work perfectly fine with V-Shell, but when I disable V-Shell extension some overview widgets or functionality freezes or don't appear until I logout and log back in.

On Xorg session I can resolve this with Alt+F2 and then r but this is not possible on wayland, so could you restart/refresh/reload gnome-shell or just the overview aspect of gnome-shell when Extension is disabled.

**Comment by G-dH** [comment]
Is it about V-Shell 29 from e.g.o or 29.5 from GitHub? What extensions do you use?
Every extension, including V-Shell, must restore the Shell to the state before it was activated on disable. If you use extensions incompatible with V-Shell and V-Shell is forced to reset itself to maintain its integrity, things can get complicated. I can't restart Shell on disable, it's not even possible on Wayland.

**Comment by 343i** [comment]
I used 29.5 from github and I think from my setup these extensions dont play well with V shell:
- dash-to-dock (from github)
- night theme switcher (from gitlab)
- caffeine (from e.g.o)
- desktop icons (from ubuntu package)

also on side note how do I find out if extension is incompatible with V-Shell

**Comment by G-dH** [comment]
I believe that Dash to Dock is the only problematic extension here, it's overriding parts of the V-Shell. Don't use it or expect issues..

**Comment by G-dH** [comment]
Is this still a problem?

**Comment by 343i** [comment]
When I disable the extension and then type something in search bar it does not load any search results in normal overview.

my setup has dash to dock with this extension but you've said that dash to dock can be troublesome with this extension

**Comment by 343i** [comment]
I've changed the title of this issue

**Comment by G-dH** [comment]
Please, try the latest version from this repository and let me know if it helped with this issue.
