### ISSUE TITLE
[BUG] Generic (non-localized) app names are not considered for search

### ISSUE THREAD

**Issue by intelfx** [G-dH/vertical-workspaces#85]
#### Describe the bug

If one is using a localized GNOME UI, when the Search module is enabled, it becomes impossible to search for applications by their generic (non-localized) names.

This works when the Search module is disabled or when the extension is disabled.

#### Basic debug information

 - Did disabling all other extensions help? - No
 - Did you find conflicting extension? - N/A

#### To Reproduce

1. Set up a non-English locale (for example, `ru_RU`)
2. Enable Vertical Workspaces, enable Search module
3. Go into Overview
4. Start typing "расширения" to search for the Extensions app by its localized name ("Расширения")
5. Observe valid result
6. Clear entry, start typing "extensions" to search for the Extensions app by its non-localized name
7. Observe empty result

#### Expected behavior

I expected the Extensions app to appear in the search results for the "extensions" query regardless of the locale.

#### Screenshots

With Search module:
![Снимок экрана от 2023-06-09 02-05-31](https://github.com/G-dH/vertical-workspaces/assets/1158172/5ccc5134-e858-40df-9d31-d560b798e1c6)

Without Search module:
![Снимок экрана от 2023-06-09 02-06-43](https://github.com/G-dH/vertical-workspaces/assets/1158172/0b799f34-565e-4f79-9d74-25010750c9b0)

#### System:
 - OS: Arch Linux
 - Version of V-Shell extension: 29
 - Source of installation: extensions.gnome.org
 - Other installed and enabled extensions:
   - `appindicatorsupport@rgcjonas.gmail.com`
   - `lockkeys@vaina.lt`
   - `tailscale-status@maxgallup.github.com`

#### System log output

<empty, no new log lines>

**Comment by G-dH** [comment]
Thanks for reporting this, I'll look into it.

**Comment by G-dH** [comment]
Please try the latest GitHub version and let me know if it fixes the issue for you.

**Comment by intelfx** [comment]
@G-dH yes, that formally works, albeit I can see from the code that you're matching against the id. I wonder if there are cases where it'll break.

Maybe it'd be a better idea to use `DesktopAppInfo.get_string('Name')`? That method is supposed to return non-localized keys from the desktop file. Or is this just how the default GNOME Shell search works? ~~(if so that's lame lol)~~

---

BTW, there's the same issue with the GNOME Maps app, except that it doesn't even work on vanilla GNOME (neither it works with current vertical-workspaces master, nor with my suggestion). I'm not sure what's up, maybe you have an idea.

**Comment by G-dH** [comment]
Thanks, I missed this method. Updated.

**Comment by intelfx** [comment]
> The app's name is just "Maps".

Yep, still, it's not found via a "Maps" search query...

Anyway, that's just a tangent. The search works as intended now on the initial test-case, thanks!

**Comment by G-dH** [comment]
![maps-search](https://github.com/G-dH/vertical-workspaces/assets/73719686/0131d5b6-a820-41f6-970e-ca76921631c7)

**Comment by intelfx** [comment]
That's really weird — mine does not work that way at all. I'll be looking for the issues on my end then :)
