### ISSUE TITLE
[BUG] Dash-to-dock compatibility

### ISSUE THREAD

**Issue by zazy** [G-dH/vertical-workspaces#86]
**Describe the bug**
Dash-to-dock is set to display the dock on all monitors. As soon as I activate V-Shell, the dash is shown on the secondary monitor only. I have to configure the setting again every time.

**Basic debug information**
 - Did disabling all other extensions help? No
 - Did you find conflicting extension? No

**To Reproduce**
1. Enable Dash-to-dock extension
2. Go to Dash-to-dock  settings > Size & position and enable the "Show on all monitors"
3. Hit the Meta key to show V-Shell (now the Dash is shown on the secondary monitor only)
4. Return to the desktop and see that the dash is also shown on the secondary monitor only
5. Go to Dash-to-dock settings > Size & position and you can see that the "Show on all monitors" option is still enabled
6. Uncheck and check again the setting to show Dash on all monitors again

Please note that settings had been translated from Italian so may be not as accurate. This bug was not present on v29

**Expected behavior**
If Dash-to-dock is set to be shown on all monitors I expect it to be shown on all monitors also in the overview and to find dash on all monitors again when I return to the desktop

**Screenshots**
I attach a screen recording. Cursor is not shown because of a bug in Gnome, sorry.

**System:**
 - OS: Ubuntu 22.04.2
 - Version of V-Shell extension: v30
 - Source of installation: extensions.gnome.org

[Video del 09-06-2023 15:22:12.webm](https://github.com/G-dH/vertical-workspaces/assets/10668286/c01fbe91-3fdc-47ea-b59f-632da2b8fe11)

**Comment by G-dH** [comment]
Thanks, please try the latest GitHub version and let me know if it fixes for you.

**Comment by zazy** [comment]
The problem seems resolved with the github version. Thank you for the really quick fix!

**Comment by Aqua1ung** [comment]
Sorry to say, but something's really wrong with V-Shell version #30, and it needs to be disabled (I'm on Gnome 44.2 if it makes a difference). Unfortunately I cannot seem to be able to disable the extension update, as I'd rather use ver. 28, which seemed to be working fine.

**Comment by G-dH** [comment]
@Aqua1ung : If you want to help me to fix it, please elaborate on the "something's really wrong". Did you try the updated GitHub version? Do you use Dash to Dock or Ubuntu Dock?

**Comment by Aqua1ung** [comment]
Apologies for my apparently flippant remark, i was in a bit of a hurry and didn't have time to elaborate. Yes, I tried the GitHub version you recommended above, and it worked for a bit, until it got automatically updated/overwritten. And yes, I am using Dash to Dock. At this point I have it disabled, but I certainly look forward to your ironing out the bugs and updating the release.

Many thanks for a great piece of software!

**Comment by G-dH** [comment]
> until it got automatically updated/overwritten

I can't imagine how it could be overwritten, the version was the same as the official one.
Installation:

    git clone https://github.com/G-dH/vertical-workspaces.git
    cd vertical-workspaces
    make install

You may need to install _gettext_ and _make_ packages.

It's still not perfect on startup with the DtD, but after closing the overview for the first time it should be fine.
I'll improve it later.

**Comment by zazy** [comment]
@Aqua1ung I got the same problem when cloned from github few days ago. Just do this and the autoupdate will be stopped:

1. Open a terminal
2. cd .local/share/gnome-shell/extensions/
3. vi vertical-workspaces@G-dH.github.com/metadata.json
4. find the "version": 28 and replace that 28 with 30

**Comment by G-dH** [comment]
The problem with overwriting can happen only in this situation:
- you install older version and restart session
- system will find a newer version on ego, download the code and prepare it for installation on next restart
- you install github version and restart session
- GNOME overwrites the installation with ego version

**Comment by zazy** [comment]
@G-dH that is exactly what happens. I edited metadata.json before restarting session to avoid the ego version overwrite. 
Mine was just a fast test and was ok to edit and set version to 30 so when the patch will be relased to ego the installed github version will be overwritten. 
I updated my comment to be more specific.

**Comment by G-dH** [comment]
The easiest way is to remove the older version on ego web page and enable/install it again, then install the github version ;)

**Comment by Aqua1ung** [comment]
Like I said, I feel much more comfortable waiting until this compatibility bug is completely and officially ironed out, no skin off my back to do that. Nothing essential hinges on Vertical Workspaces for me, so I'll keep it disabled until then.

Thank you all for the advice.

**Comment by zazy** [comment]
@G-dH true and that is what I've done on first instance. But somehow my Ubuntu 22.04 installation found a way to search for updates and match with the github version updating it ¯\_(ツ)_/¯

**Comment by G-dH** [comment]
@Aqua1ung : Yeah, everyone wants flawless products for free, me too. But without testers I have only one option - release it to find out what I've missed. And believe me, I hate it when my extension fails, even if it's not my fault.

**Comment by axkibe** [comment]
git version works fine at first glance.

**Comment by G-dH** [comment]
Please, try the latest update from the repository and let me know how it works for you. Now it's about the broken overview on startup.

**Comment by Aqua1ung** [comment]
> Please, try the latest update from the repository and let me know how it works for you. Now it's about the broken overview on startup.

Latest update (#37, I think) works fine with the "Improve compatibility with Dash to Dock" set to "on." (Haven't tried without though.) No issues so far. Many thanks!
