### ISSUE TITLE
[BUG] QuickSettings Icon Small.

### ISSUE THREAD

**Issue by MylesGit** [G-dH/vertical-workspaces#87]
**Describe the bug**
The quick settings panel pill icons become very small for some reason. Unsure if this is a new feature, I've changed no settings recently. 

**Basic debug information**
 - Did disabling all other extensions help? A: No
 - Did you find conflicting extension? A: No

**To Reproduce**
1. Enable Extension
2. Open Quick Settings

**Expected behavior**
Pill Icons should be their default size.

**Screenshots**
![image](https://github.com/G-dH/vertical-workspaces/assets/118321243/cfc98326-3692-4b5a-8586-fd9d73003416)

**System:**
 - OS: Fedora 38
 - Version of V-Shell extension: 19
 - Source of installation: extension.gnome.org
 - Other installed and enabled extensions: Pop Shell, App Hider, App Indicator, Blur my Shell, Caffeine, Dash to Panel, Grand Theft Focus, Just Perfection, Lineup, Pano, QSTweak, Rounded Window Corners, and, Weather O'clock.

**System log output**
`JS ERROR: RangeError: Provided GType name 'qwreey.quick-settings-tweaks.prefs.quickTogglesPage' is not valid; automatically sanitized to 'qwreey_quick-settings-tweaks_prefs_quickTogglesPage'
_createGTypeName@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:185:22
registerGObjectType@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:532:41
registerWidgetType@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:92:39
_init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:515:33
_init/Gtk.Widget._classInit@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:75:31
registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:74:23
@/home/myles124/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/prefPages/quickToggles.js:11:32
@/home/myles124/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/prefs.js:10:5
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

JS ERROR: RangeError: Provided GType name 'qwreey.quick-settings-tweaks.prefs.otherPage' is not valid; automatically sanitized to 'qwreey_quick-settings-tweaks_prefs_otherPage'
_createGTypeName@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:185:22
registerGObjectType@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:532:41
registerWidgetType@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:92:39
_init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:515:33
_init/Gtk.Widget._classInit@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:75:31
registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:74:23
@/home/myles124/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/prefPages/other.js:11:25
@/home/myles124/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/prefs.js:11:5
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

JS ERROR: RangeError: Provided GType name 'qwreey.quick-settings-tweaks.prefs.aboutPage' is not valid; automatically sanitized to 'qwreey_quick-settings-tweaks_prefs_aboutPage'
_createGTypeName@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:185:22
registerGObjectType@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:532:41
registerWidgetType@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:92:39
_init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:515:33
_init/Gtk.Widget._classInit@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:75:31
registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:74:23
@/home/myles124/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/prefPages/about.js:10:25
@/home/myles124/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/prefs.js:12:5
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
JS LOG: Characters Application exiting
JS LOG: Characters Application started
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Window manager warning: Ping serial 951721 was reused for window W0, previous use was for window W6.
JS LOG: Characters Application exiting
`

**Comment by G-dH** [comment]
It's not a bug, it's a feature ;) The height is the same as in GNOME Shell 43 to make the menu fit better on low resolution screens.
You can disable Grand Theft Focus extension, V-Shell offers its own _Window Attention Handler_ options in _Behavior_ settings.

**Comment by MylesGit** [comment]
> It's not a bug, it's a feature ;) The height is the same as in GNOME Shell 43 to make the menu fit better on low resolution screens.
> You can disable Grand Theft Focus extension, V-Shell offers its own _Window Attention Handler_ options in _Behavior_ settings.

How do I disable this feature then?

**Comment by G-dH** [comment]
You can't, unless you edit _quick-menu-toggle_ class in the _stylesheet.css_ file.

**Comment by G-dH** [comment]
I removed the class from *stylesheet*.
