### ISSUE TITLE
Add option to disable Workspace Switcher on Secondary Monitor

### ISSUE THREAD

**Issue by leogallego** [G-dH/vertical-workspaces#9]
Feature request: If possible, it would be useful to add an option to disable the Workspace Switcher in the second monitor.

This would be particularly useful for dual monitor setups where one of them is in a vertical position.

As an alternative, adding the option for Top or Bottom positioning would probably help with Vertical setups too, as we could have a side (Left or Right) Workspace Switcher on the main monitor and a Top or Bottom on the Secondary.

**Comment by G-dH** [comment]
Option to disable the secondary ws thumbnails is available in its position menu.

**Comment by negesti** [comment]
The option is available but I had to restart gnome-shell. Without the restart, the workspace switcher is still available on secondary monitor

**Comment by G-dH** [comment]
@negesti : Re-enabling the extension (instead of restarting Shell) should help. If you update V-Shell form this repository, the option should work immediately.
