### ISSUE TITLE
[BUG] Dash to Panel breaks overview layout

### ISSUE THREAD

**Issue by jjshoots** [G-dH/vertical-workspaces#91]
**Describe the bug**
The layour settings do not persist across reboot, but everything automagically clicks back into place when I start editing anything in the layout again. Almost like layout settings must be reloaded after reboot.

**Basic debug information**
 - All extensions disabled, same behaviour.
 - Gnome 42.5

**To Reproduce**
1. Change layout.
2. Reboot.
3. Layour disappears but comes back when layout settings are messed with again.

**Expected behavior**
Settings to persist across reboot.

**System:**
 - OS: Ubuntu 22.04
 - Version of V-Shell extension: 30
 - Source of installation: extensions.gnome.org
 - Other installed and enabled extensions: Pop shell, user themes, dash to panel. Disabled all but problem persists.

**System log output**
```
Window manager warning: Overwriting existing binding of keysym ff99 with keysym ffb2 (keycode 58).
Window manager warning: Overwriting existing binding of keysym ff98 with keysym ffb6 (keycode 55).
Window manager warning: Overwriting existing binding of keysym ff98 with keysym ffb6 (keycode 55).
Window manager warning: Overwriting existing binding of keysym ff97 with keysym ffb8 (keycode 50).
unable to update icon for software-update-available
unable to update icon for livepatch
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a0000b
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55cc17e90300] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55cc1a64b300] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55cc1a64dbe0] is on because it needs an allocation.
```

**Comment by jjshoots** [comment]
@G-dH It ends up looking like this:
![image](https://github.com/G-dH/vertical-workspaces/assets/38184875/3f304417-7ed0-405e-b5d3-1e2e37cfc2b2)

Actually it reverts to that stage as long as the screen is allowed to go dark, and I have to go into the extension settings page to load a profile for it to recover.

**Comment by jjshoots** [comment]
I've just gone through disabling all extensions and then rebooting with two of them at a time to figure out what's wrong. You're right, I think the bug is caused by a conflict between dash to panel and v shell. In any case, this would probably be out of the scope of v shell, thanks for the assistance! Feel free to close this as you see fit. :)

**Comment by G-dH** [comment]
I thought so. This conflict is actually common with Dash to Dock, although I wasn't able to reproduce it with DtP. With the latest version from the GitHub repository, I can just close the overview and everything is ok when I open it again.
I will work around this eventually, thank you for the feedback.

**Comment by jjshoots** [comment]
Is that the latest version of VShell from GH? Or DtP?

**Comment by G-dH** [comment]
I'm referring to V-Shell's main branch.

**Comment by G-dH** [comment]
Please, try the latest update from the repository and let me know if it's OK with DtP.
[Installation](https://github.com/G-dH/vertical-workspaces#installation-from-github-repository)

**Comment by jjshoots** [comment]
@G-dH seems to work without issues now. Cheers!
