### ISSUE TITLE
[BUG] Dash is displayed horizontally on the left, rather than vertically

### ISSUE THREAD

**Issue by stuarthayhurst** [G-dH/vertical-workspaces#94]
**Describe the bug**
 - The dash on the left is shown horizontally, when it's configured to be vertical on the left.
 - Downgrading to version 30 fixed the problem for now.

**Basic debug information**
 - Did disabling all other extensions help? No
 - Did you find conflicting extension? No

**To Reproduce**
1. Set the dash to be positioned on the left, vertically

**Expected behavior**
 - It to be placed vertically, not horizontally

**Screenshots**
![image](https://github.com/G-dH/vertical-workspaces/assets/33733427/bb740bb7-6080-403e-8434-4f5b28a370e9)

**System:**
 - OS: Debian 12
 - Version of V-Shell extension: 35
 - Source of installation: e.g.o
 - Other installed and enabled extensions:
```
vertical-workspaces@G-dH.github.com
Hide_Activities@shay.shayel.org
RemoveAppMenu@Dragon8oy.com
appindicatorsupport@rgcjonas.gmail.com
apps-menu@gnome-shell-extensions.gcampax.github.com
ding@rastersoft.com
launch-new-instance@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
```

**System log output**
```
Jul 01 19:43:28 argon gnome-shell[6422]: [V-Shell (Vertical Workspaces)]: resetting extension...
Jul 01 19:43:28 argon gnome-shell[6422]: [V-Shell (Vertical Workspaces)] Dash module suspended due to potential conflict with another extension
```

**Comment by G-dH** [comment]
Disable all other extensions and restart (log out/in) GNOME Shell. For example *Window List* extension seems to be a problem, disabling it without restart doesn't help. But in your log I see that V-Shell detected some dock extension enabled. If dock (DtD, DtP, ) is not installed, check `enabled-extensions` key in the *dconf editor* - extension removed while enabled can remain in the list, unfortunately.
Also *Launch New Instance* should be disabled, V-Shell has its own option for this.

**Comment by nickles95** [comment]
> Disable all other extensions and restart (log out/in) GNOME Shell. For example _Window List_ extension seems to be a problem, disabling it without restart doesn't help. But in your log I see that V-Shell detected some dock extension enabled. If dock (DtD, DtP, ) is not installed, check `enabled-extensions` key in the _dconf editor_ - extension removed while enabled can remain in the list, unfortunately. Also _Launch New Instance_ extension should be disabled, V-Shell has its own option for this.

Same problem, just started on the newest version, disabling all of my other extensions didn't help and I would very much like to keep using them anyway.

![Screenshot from 2023-07-01 18-30-34](https://github.com/G-dH/vertical-workspaces/assets/9562687/14123903-2b31-4239-8ed8-1eabc4c7712f)

**Comment by stuarthayhurst** [comment]
> Also Launch New Instance extension should be disabled, V-Shell has its own option for this.

I'll pass that on, thanks

**Comment by G-dH** [comment]
> Same problem, just started on the newest version, disabling all of my other extensions didn't help and I would very much like to keep using them anyway.

The point is to find out where is a conflict, if any.

What about the log? Is there still the information about suspended dash?

**Comment by Kawazu0** [comment]
Let's make it simple : Debian 12 with Gnome 43
I installed the extension a few days ago, it worked perfectly, then today I had an update notification and now I have the same issue. I don't think I'm using the same extensions as OP.

**Comment by G-dH** [comment]
@Kawazu0 It's nice to know what you think, but I need the data ;)

    gsettings get org.gnome.shell enabled-extensions

**Comment by G-dH** [comment]
Update from the github repository, or remove all unused extensions from the `enabled-extensions` gsettings key, specifically Dash to Dock/Panel.

**Comment by Kawazu0** [comment]
> 

Oops sorry :

`gsettings get org.gnome.shell enabled-extensions`
['user-theme@gnome-shell-extensions.gcampax.github.com', 'simplenetspeed@biji.extension', 'gnome-shell-screenshot@ttll.de', 'RemoveAppMenu@rastersoft.com', 'activities_icons@fawtytoo', 'appindicatorsupport@rgcjonas.gmail.com', 'apps-menu@gnome-shell-extensions.gcampax.github.com', 'freon@UshakovVasilii_Github.yahoo.com', 'harddiskled@bijidroid.gmail.com', 'RecentItems@bananenfisch.net', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'RemoveAppMenu@Dragon8oy.com', 'vertical-workspaces@G-dH.github.com']

Regards

**Comment by G-dH** [comment]
@Kawazu0 Do you still have this problem with V-Shell 37?

**Comment by Kawazu0** [comment]
> @Kawazu0 Do you still have this problem with V-Shell 37?

@G-dH Sorry, I didn't notice the update because of my usual trick (download previous extension, install it by hand, change version number to a fake one )

Real version 37 seems to work nicely. Thank you !

**Comment by G-dH** [comment]
@stuarthayhurst Can I close this issue?

**Comment by stuarthayhurst** [comment]
Sorry for the delay. As I was reporting on behalf of a friend, I've sent another reminder to update and test, I'll let you know as soon as they respond.

**Comment by stuarthayhurst** [comment]
Got a reply, it's all working.

Thanks :)
