### ISSUE TITLE
[BUG] White screen after login

### ISSUE THREAD

**Issue by Majo111** [G-dH/vertical-workspaces#95]
When I login to Gnome desktop, I get only whole white screen without dash and panel. Only after hard reset I can to login classic Gnome session and disable extensions. After that I can login to regular Gnome session.

**System:**
 - OS: Manjaro
 - Version of V-Shell extension: 36
 - Source of installation: Extension manager

**Comment by G-dH** [comment]
This is a new problem after updating to 36? You tested the development version before the update, without this problem?

**Comment by francesco-borsatti** [comment]
I have this problem too, black screen after login. 
- Everything works (I can open terminal and type gnome-session-quit to exit) but I don't see anything.
- The only thing I can see is the mouse cursor
- Of all the applications I can open, the only one I can visually see is google chrome
- **if I enable the extension AFTER the login, everything works fine**

Ubuntu 22.04.2 LTS on Wayland

#### Workaround
The workaround is logging in with Gnome Classic, disabling extensions, logging in your normal profile and enabling the extensions

**Comment by francesco-borsatti** [comment]
> @francesco-borsatti Have you tried installing the Dash to Dock extension and disabling the Ubuntu Dock (which is a fork of DtD)? The best solution is to not use any DtD ;)

Thank you for your swift response!

- I confirm that by disabling Ubuntu Dock and Dash to Dock the login goes as expected
- but enabling either Dash to Dock or Ubuntu Dock causes the problematic behavior

This is my list of enabled extensions:

```
['clear-top-bar@superterran.net',
 'no_activities@yaya.cout',
 'babar@fthx',
 'just-perfection-desktop@just-perfection',
 'ubuntu-appindicators@ubuntu.com',
 'places-menu@gnome-shell-extensions.gcampax.github.com',
 'NotificationCounter@coolllsk',
 'middleclickclose@paolo.tranquilli.gmail.com',
 'ssm-gnome@lgiki.net',
 'mediacontrols@cliffniff.github.com',
 'search-light@icedman.github.com',
 'blur-my-shell@aunetx',
 'nightthemeswitcher@romainvigier.fr',
 'logomenu@aryan_k',
 'sound-output-device-chooser@kgshank.net',
 'user-theme@gnome-shell-extensions.gcampax.github.com',
 'tweaks-system-menu@extensions.gnome-shell.fifi.org',
 'rounded-window-corners@yilozt',
 'unite@hardpixel.eu',
 'vertical-workspaces@G-dH.github.com',
 'dash-to-dock@micxgx.gmail.com']
```

**Comment by G-dH** [comment]
You are using some problematic extensions, Blur My Shell is one of them (at least turn off blur in Settings Overview tab), some of the Just Perfection options. V-Shell is an extension to the default GNOME Shell, and each of these extensions changes the default code and behavior more or less. V-Shell cannot be compatible with everything in all combinations, that is impossible. You need to find out what is causing the problems and find a combination of extensions that work together.

**Comment by Majo111** [comment]
I confirm, that there is a conflict with Just perfection extension. I have this extension also. I never have a problem with combination Just perfection and V-shell until now. Unfortunately, version 37 doesn't solve the problem.

**Comment by G-dH** [comment]
What options you use in JP?

**Comment by G-dH** [comment]
@Majo111 What extensions do you use?

**Comment by Majo111** [comment]
Thanks for reply G-dH. There are my extensions:

![Snímka obrazovky zo dňa 2023-07-03 20-02-01](https://github.com/G-dH/vertical-workspaces/assets/31368840/e41e83b1-994c-4ffc-92c5-93143d26aab8)
![Snímka obrazovky zo dňa 2023-07-03 20-02-49](https://github.com/G-dH/vertical-workspaces/assets/31368840/943c1322-c71a-4253-9636-7069203f7a29)
![Snímka obrazovky zo dňa 2023-07-03 20-03-07](https://github.com/G-dH/vertical-workspaces/assets/31368840/1a6147a8-bf1f-4a4c-8be6-6f1344ab510f)

**Comment by G-dH** [comment]
You have two extensions for the panel enabled, 'Hide Top Bar' disables the Panel module automatically.

**Comment by Majo111** [comment]
Thank you very much. I am going to try it. You are the most willing developer I have ever seen on internet.

**Comment by G-dH** [comment]
@francesco-borsatti I missed `search-light` in your list of extensions - definitely not compatible with V-Shell ;)

**Comment by francesco-borsatti** [comment]
@G-dH thank you! I'll use ULauncher instead 👍

**Comment by G-dH** [comment]
@francesco-borsatti  You can also try V-Shell in *Overview Mode > Static Workspace*
