### ISSUE TITLE
[FEATURE] Disable switcher popup

### ISSUE THREAD

**Issue by evenfrost** [G-dH/vertical-workspaces#96]
It would be great if the extension had the option to disable the workspace switcher popup completely. I know this is not a big deal since we got a separate [Disable Workspace Switcher](https://extensions.gnome.org/extension/4980/disable-workspace-switcher/) extension for that, but since V-Shell already has the settings for the popup, it could have the setting to disable it as well.

**Comment by G-dH** [comment]
It's on the *Behavior* tab ;)

**Comment by evenfrost** [comment]
Sorry, just found it myself as well. Great extension, thanks for making and maintaining it!
