### ISSUE TITLE
[BUG] Tapping on windows in the overview using a touch screen activates drag’n’drop

### ISSUE THREAD

**Issue by voxasz** [G-dH/vertical-workspaces#98]
**Describe the bug**
When using a touch screen and tapping on a window in the overview, it shrinks as if you had pressed and held to drag it

**Basic debug information**
 - Did disabling all other extensions help? No
 - Did you find conflicting extension? Not applicable

**To Reproduce**
Doing all of the following actions using a touch screen (in a wayland gnome session, haven’t tested x11),
1. Navigate to the activities overview
2. Tap on any open window in the current workspace
3. The window gets grabbed for drag’n’drop
4. A second tap releases it.

**Expected behavior**
The window should be activated when tapped.

**Screenshots**
Gnome won’t actually let me take screenshots while a window is grabbed.

**System:**
 - OS: Fedora 38
 - Version of V-Shell extension: 37
 - Source of installation: extension.gnome.org
 - Other installed and enabled extensions: 
    - gestureImprovements@gestures
    - blur-my-shell@aunetx
    - appindicatorsupport@rgcjonas.gmail.com
    - custom-hot-corners-extended@G-dH.github.com
    - clipboard-history@alexsaveau.dev
    - just-perfection-desktop@just-perfection
    - caffeine@patapon.info
    - screen-rotate@shyzus.github.io
    - improvedosk@nick-shmyrev.dev
    - unite@hardpixel.eu
    - peek-top-bar-on-fullscreen@marcinjahn.com
    - vertical-workspaces@G-dH.github.com
    - user-theme@gnome-shell-extensions.gcampax.github.com
    - gsconnect@andyholmes.github.io

**System log output**
```
JS LOG: Characters Application exiting
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
JS LOG: Characters Application started
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
JS LOG: activating result
JS LOG: Characters Application exiting
g_source_remove: assertion 'tag > 0' failed
JS ERROR: ReferenceError: assignment to undeclared variable item
_destroy@/home/admin/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/libs/streamSlider.js:260:9
_streamRemoved@/home/admin/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/libs/volumeMixerHandler.js:98:42

Failed to set the markup of the actor '<unnamed>[<ClutterText>:0x56296cfe7d60]': Erreur à la ligne 1, caractère 14 : « < » n’est pas un nom valide
Failed to set the markup of the actor '<unnamed>[<ClutterText>:0x562974c336c0]': Erreur à la ligne 1, caractère 14 : « < » n’est pas un nom valide

```

Note about the log: everything except the last two lines appeared as soon as I ran the command, so I don’t think that’s actually relevant for the bug.

The last two lines appeared the moment I clicked activities. The French part says "Error at line 1 character 14: "<" is not a valid name."

**Comment by G-dH** [comment]
I can't reproduce this issue on my system as I don't have a touch screen.
Just to make sure the bug is in V-Shell:
1. disable V-Shell, restart GNOME session, try to reproduce the issue - is all OK?
2. disable all other extensions, restart GNOME session, try to reproduce the issue - is it still there?
3. when V-Shell is enabled, disable `WindowPreview` module on `Misc` tab of V-Shell Settings window - does it help?

**Comment by voxasz** [comment]
The issue did not occur with V-Shell or all extensions disabled and disabling WindowPreview did fix the issue.

**Comment by G-dH** [comment]
Can you please try the refactored V-Shell from this repository?
[Installation instuctions](https://github.com/G-dH/vertical-workspaces#installation-from-github-repository)

**Comment by voxasz** [comment]
I tried it, it didn’t work, the same issue occurred.

**Comment by G-dH** [comment]
OK, thanks, I'll look into it.

**Comment by G-dH** [comment]
Can you please update V-Shell from the repository and let me know if it helped?
